### ISSUE TITLE
MoonReader only loads thumbnails - bbs on NAS

### ISSUE THREAD

**Issue by eRaz3r** [rvolz/BicBucStriim#107]
When I integrate my bbs-Library in MoonReaderPro, it only loads a thumbnail, when I click on "download". Via the Web-Interface in Firefox, it works correctly.

**Comment by JuergenBY** [comment]
Anything in progress? I get dayli pressure from wife, because she can`t reach their ebooks :-)

**Comment by eRaz3r** [comment]
I temporary use aldiko (works perfectly) till moonreader release a fix. Did
write them a mail and ask for help, but the customer dont seems to be King
there. I pay money for moonreader and get no answer. BBS is absolutly free
and after an incredible short time, the programmer himself answers me.
Thanks for that again.
Am 14.01.2015 20:59 schrieb "JuergenBY" <notifications@github.com>:

**Comment by JuergenBY** [comment]
Yep, i wrote him (Moonreader) 2 times an email, no responds since months so far...

**Comment by JuergenBY** [comment]
Vielen Dank für die Info und das Update. Leider bekomme ich das nicht 
hin. Ich habe auf dem NAS die beiden Files ausgetauscht und bekomme 
jetzt nur noch Fehlermeldungen...

Mit Freundlichen Grüßen,
Jürgen Herrmann

Jürgen Herrmann
Neubeurer Str. 18
83064 Raubling

08035/9659946

Am 29.01.2015 um 22:32 schrieb Rainer Volz:

**Comment by rvolz** [comment]
Es gibt zwei Möglichkeiten: entweder die komplette Github-Fassung herunterladen oder ein wenig warten, bis das Release kommt. Muss nur noch das Tolino-Problem erledigen.

**Comment by JuergenBY** [comment]
Hallo,
wie bekomme ich denn die "alte" Version wieder zum Laufen? Ich habe die 
alten Dateien wieder zurückgespielt, bekomme aber trotzdem die 
Fehlermeldung...
Ich habe so eine Ahnung, dass ich das nicht mehr hin bekomme.

Mit Freundlichen Grüßen,
Jürgen Herrmann

Jürgen Herrmann
Neubeurer Str. 18
83064 Raubling

08035/9659946

Am 01.02.2015 um 22:09 schrieb Rainer Volz:

**Comment by JuergenBY** [comment]
Irgendetwas hatte sich mit den Folder Rechten verhakt, jetzt geht es 
wieder mit den alten Dateien.

Mit Freundlichen Grüßen,
Jürgen Herrmann

Jürgen Herrmann
Neubeurer Str. 18
83064 Raubling

08035/9659946

Am 01.02.2015 um 22:09 schrieb Rainer Volz:
