### ISSUE TITLE
Tolino: Titel defect-error

### ISSUE THREAD

**Issue by JohnReader** [rvolz/BicBucStriim#114]
While calibres built-in Content-Server is working fine for Downloads, BicBucStriim (v1.2.4) seems not fully compatible with tolino Readers. After downloading a book, Tolino reads "Titel defect"-error and the book itself is displayed without cover and strange title, starting with numbers.
Is this a bug of BicBucStriim and can be corrected? 
Thanks and best regards,
John

**Comment by joeduck** [comment]
I also have a Tolino and cannot download epub Files. Are there any news about the support for Tolino (Vision 2)?

**Comment by rvolz** [comment]
I was able to check this with a Tolino recently, the problem is that Tolino tries to download the book files without sending the normal authentication headers. Disabling authentication for book downloads would be easy, but no real solution.

I guess I have to rebuild the authentication part of the app for devices using Android, that is Tolino amd others, see #107 .

**Comment by joeduck** [comment]
How can i disable the authentication as workaround?

Thanks, Joe

**Comment by rvolz** [comment]
Be warned: this patch allows **everybody** to download your book files. So please only apply it in a local LAN.

The patch is easy: in file `/lib/BicBucStriim/login_middleware.php` locate function `authBeforeDispatch` and add some lines, see below:

```php
 } elseif ($accept === 'application/json') {
$app->getLog()->debug('login: unauthorized JSON request');
$app->response->headers->set('WWW-Authenticate', sprintf('Basic realm="%s"', $this->realm));
$app->halt(401,'Please authenticate');

### ADD THESE LINES
 } elseif (preg_match ('/\/titles\/\d+\/file\/.+/', $resource)) {
                // OK
### END OF PATCH

} else {
$app->getLog()->debug('login: redirecting to login');
// now we can also use the native app->redirect method!
$this->app->redirect($app->request->getRootUri().'/login/');
}
...
```

**Comment by joeduck** [comment]
Many thanks. It works now.

**Comment by locutus29** [comment]
The above workaround did the trick for me - at least partially. The epub on my tolino is intact and the cover is correctly displayed - but the title is scrambled and cibtauns a lot of numbers - just like johnreader mentioned above. Is there mayba another workaround for this? Cheers locutus

**Comment by rvolz** [comment]
@locutus29 I just tried it repeatedly and I get my normal test epubs. The title with numbers you describe I only get with my failed attempts to download books with authentication. I tested that with a Tolino Vision.

That said: I tried all the tricks I know, but I couldn't get Tolino to work with authentication. I was able to force it to request one download with authentication, only to see that it immediately repeated the request without login data, and then, of course, failed. That device is obviously not meant to work with other libraries.

**Comment by rvolz** [comment]
I'll add a BBS version without authentication/login/users, see #88. I hope that this version will enable you to download books successfully.

**Comment by JohnReader** [comment]
Dear Rainer,

this version works now. But I have a strange behaviour after shifting 
the calibre-books into a new subdirectory. Previously it was in

/volume1/books

and now it's in:

/volume/books/calibre

to get some degrees of freedom. However - I cannot access the main-page 
anymore. The error message reported by any browser (FF, IE, Chrome) is: 
too many redirects / issues with cookies. When I call <ip>/bbs it 
displays <ip>/bbs/admin/configuration in the URL. I didn't change 
anything else and honestly, I do not have any clue on how to proceed.

/installcheck.php is running, showing green except for PHP intl (was 
never green, is yellow) and open_basedir, which is yellow as well but 
indicating the correct folder. The manual check on this page for the 
calibre directory shows green, access rights are granted.

Can you give me a hint on what to look at?

Thank you very much for the support,
John


Am 03.02.2015 um 22:38 schrieb Rainer Volz:

**Comment by JohnReader** [comment]
Dear Rainer,

issue solved: in debug mode I saw that the metadata.db was not 
accessible - so I removed this back, re-configured bbs and then it worked.

But maybe it's in any case worth to rethink the launching-strategy: if 
the db is missing, it should not run into an endless redirection.

Anyway, no blaming at all - I'm glad to see someone pushing smart tools 
ahead!

Best regards,
John

Am 25.03.2015 um 21:32 schrieb John Clarck:

**Comment by rvolz** [comment]
Strange, the new install check should have reported an inaccessible metadata.db.

**Comment by mitnam** [comment]
Hi,

I use the most recent version 1.2.5 and now I have the problem described above. ebooks will not download on my tolino and I get a message saying that the ebooks seems to be damaged. But the ebooks are ok; downloads via bbs on my mac (safari browser) work just fine.

I tried the above work around but still it doesn't work.

And ideas?

The strange thing is that it worked fine with one of the previous versions (probably 1.2.4, without the work around).

**Comment by rvolz** [comment]
As mentioned (somewhere) above Tolinos have problems with downloading ebooks when the multi-user login is enabled. They acted very strange. 

Switch the login off (as it was in older versions) in the configuration section and the download will work again.  Sorry, but that is the only solution I know currently.
