### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by apechman** [rvolz/BicBucStriim#116]
Hello
First of all, the app is awesome!
And to make it more awesome, I would like to suggest 2 upgrades:
1) Home screen (that show the recent items) would be nice to have an option to show more pages like in other tabs.
This is the tab i mainly use on my 10.000+ books library, and wish I could see more than 100 recent items in order.
2) Enabling to filter by Customized Calibre Data columns would also be interesting.
For ex: I have my own Tag column that I use to group the books, and would be cool to filter by that.

thanks a lot

ALEX

**Comment by Lheriss** [comment]
Actually, I'd like to have a complete choice of the email address where to send : I use a pocketbook, and they've got a similar system, with an address xxx@pbsync.com. Would it be possible? Thanks in advance.

**Comment by rvolz** [comment]
That is already built-in. When you press the "Send to Kindle" button you can anter any target address, not just xxx@kindle.com. The only problem is, that the current function will only send Kindle-compatible formats, no EPUB.

**Comment by Lheriss** [comment]
Thanks for the info... and I understand why it doesn't work, as I can only read epubs....

**Comment by rvolz** [comment]
Sending all formats is not difficult, the main problem is a simple UI solution for mailing/downloading a lot of formats.

**Comment by Lheriss** [comment]
why not use the "same" UI as for downloading? another tab, just under the tab "download", named "email", with a field for the email address, and a some buttons named "epub" "mobi" "pdf" or whatever, to choose the format to send?

**Comment by Lheriss** [comment]
Or on the same tab, some push buttons (that remain highlighted) for the format (eventually allowing to retain more than one, in order to mail/download more than one book format, if possible), and then two buttons (email / download) to choose the action to trigger?

**Comment by tlc** [comment]
As an example for 2), I have a #genre column.  It'd be great to have a Genre button in your navbar.  Of course there are probably custom columns people wouldn't want in their navbar, so it'd have to be configurable.

**Comment by apechman** [comment]
Hey Rainer
Any chance you could implement the 1) on the next version?

thanks man
All the best
Alex

**Comment by rvolz** [comment]
I'm thinking about it, but with the current layout it's difficult. Currently that page is also used to display the "Admin" and "Logout" buttons. Adding "prev"/"next" buttons for navigation would make the display crowded, at least for smaller devices.

**Comment by m0urs** [comment]
I rally would like to see "1) Home screen (that show the recent items) would be nice to have an option to show more pages like in other tabs." - Any chance to get that implemented (you wrote it should be easy t do .. :-)) And thanks for that great program!

**Comment by apechman** [comment]
Me 2 !!! I'm lost in so many books I've downloaded recently and best way would be to see more pages on Home screen

Anyway, thanks for the incredible good work you did already!

Thx
Alex from NL
