### ISSUE TITLE
Fresh install - search function BUG

### ISSUE THREAD

**Issue by derdigge** [rvolz/BicBucStriim#135]
I Just installed bbs like discribed here:
https://github.com/rvolz/BicBucStriim
(README)
and here:
https://github.com/rvolz/BicBucStriim/wiki/Webservers
(nginx)

And index.php redirects me to non existent location:

2015/01/01 11:38:40 [error] 29418#0: *1 "/platz/bbs/admin/configuration/index.php" is not found (2: No such file or directory), client: 192.168.2.160, server: 10.8.6.6, request: "GET /admin/configuration/ HTTP/1.1", host: "10.8.6.6"

There is no Folder called admin inside the installer zip.

**Comment by derdigge** [comment]
Fixed on my own. Was a path problem. Browsing/loading books works but search function gives 404.
Any idea on this?

192.168.2.160 - - [01/Jan/2015:18:03:34 +0100] "GET /search/?search=Passion HTTP/1.1" 404 1091 "http://10.8.6.6/titleslist/0/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"

**Comment by rvolz** [comment]
Search works like the rest of the functionality, so if the rest works ... it should work too. If your installation is in the web server root  then the request to 

    http://<server>/search/?=<search phrase> 

is correct. However version 1.2.4 has sometimes had problems when installed in the root. Currenly I would recommend to install it in a `bbs`location below the root. 

    http://<server>/bbs/search/?=<search phrase> 

Maybe that solves your problem too.

**Comment by derdigge** [comment]
Thanks for Your reply!

No i am sorry! Search function still shows in browser "Error Loading Page".
in the middle of the screen. The nginx error log is clear now. no entry.

Login/logout works as user x. Browsing books,loading books works.
But still the search function is broken.

i will try 1.2.3 now.

**Comment by joeduck** [comment]
Hi,

i have the same Problem. BBS is installed at OMV (Open Media Vault) with nginx. Here my nginx config an the .htaccess file:
----------------------
server {
    listen 88 default_server;
    set $root_path "/media/6a6700bb-331f-4c00-ba2a-620edb61605f/Calibre/";
    root $root_path;
    index index.html index.php;
    set $socket "unix:/var/run/fpm-022044d1-171f-4d10-a7ff-13965122211e.sock";
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass $socket;
        fastcgi_index index.php;
        include fastcgi_params;
    }
    access_log /var/log/nginx/4f7c5014-95e0-4997-9dd2-62a6ea258200-access.log;
    error_log  /var/log/nginx/4f7c5014-95e0-4997-9dd2-62a6ea258200-error.log;
    autoindex on;
    large_client_header_buffers 4 32k;
    location /bbs/ { try_files $uri $uri/ /bbs/index.php?$request_uri; }

}
---------------------
<IfModule !mod_rewrite.c>
    ErrorDocument 500 "mod_rewrite must be enabled"
</IfModule>

location /bbs/ {
        try_files $uri $uri/ /bbs/index.php?$request_uri;
}

# protect database
<FilesMatch data.db>
    Order allow,deny
    Deny from all
</FilesMatch>

# protect schema
<FilesMatch schema.sql>
    Order allow,deny
    Deny from all
</FilesMatch>
---------------------------------
All other Thing work. Installation check has everything green, but apache and URL rewriting (Changed manualy).

The Second issue ist allready known: download to Tolino Vision 2 does not work.

Thanks for the Work. Joe

**Comment by derdigge** [comment]
Good to hear that i am not the only one.
Today I have tried to setup bicbucstriim on a fresh debian installation inside
a virtual box. Apache2 fails also with the same behavior when using the search function.

This is really a great piece of software and I really want to make it work properly.
It would be nice if someone can provide any help. As its affecting multiple users now,
maybe someone has faced this behavior already in the past.


Danke für die gute Arbeit an diesem Projekt.

**Comment by rvolz** [comment]
My test system is a bit older, Ubuntu 12.04.3 LTS (GNU/Linux 3.8.0-29-generic i686), so maybe the world changed. I'll build a new test system and will check.

Sqlite is enough, MySQL is not required.

**Comment by derdigge** [comment]
Ok i tracked it down to nginx config.
Apache is just working fine now.
On a clean Debian7(nginx 1.2.1) install and on a clean Ubuntu 14.04 trusty(nginx 1.4.6) this behavior can be found. On both apache2 works flawlessly ootb.

**Comment by joeduck** [comment]
@derdigge
Do you know what is going wrong with nginx. Can´t change to Apache with my NAS.

**Comment by derdigge** [comment]
I tried several settings without success, sorry.

**Comment by rvolz** [comment]
Thx for the efforts, I'll try to check nginx during the week.

**Comment by joeduck** [comment]
Any news about this? Now I can download books on the tolino but it is hard to find the book I want...

**Comment by rvolz** [comment]
I was able to reproduce your problem. I am no ngninx user, so it may take a while to find the right configuration.

**Comment by joeduck** [comment]
Many Thanks. How can I help?

**Comment by rvolz** [comment]
That works for me now. Not elegant, but it works. Please check:
```
   location /bbs/ {
                rewrite ^/(bbs/img/.*)$ /$1 break;
                rewrite ^/(bbs/js/.*)$ /$1 break;
                rewrite ^/(bbs/style/.*)$ /$1 break;
                rewrite ^/bbs/$ /bbs/index.php last;
                rewrite ^/bbs/(admin/authors|authorslist|login|logout|metadata|search|series|serieslist|tags|tagslist|titles|titleslist|opds)/.*$ /bbs/index.php last;
 }
```

**Comment by joeduck** [comment]
Yessss :-). Many many Thanks! Now my Wife can search her Books with the Tolino in Our Personal Cloud.
