### ISSUE TITLE
Error loading Page on author tags and series

### ISSUE THREAD

**Issue by JPreacher** [rvolz/BicBucStriim#136]
Hi,
i m using your great prog for one year no problem occured on my qnap x53. However one week ago I have 'Error Loading Page' when I click on author or tags moreover when I search an author, bicbuc found it putting '1' front the field author and the number of books but line below is blank and when I click on it 'Error loading Page'. No photo or info about the author.
The only fonctional thing when I want info or photo (author) is to get through books tab or home tab.
I installed bicbuc 1.2.5a on bbs directorie as requested. I tried to downgrade but same issue
Thx to help me

**Comment by rvolz** [comment]
So what changed sosuddenly? Did you upgrade your QNAP?

**Comment by JPreacher** [comment]
Hello,

 

Thanks to answer me quickly. Yes I have upgraded it. As I said Bicbucstriim is still functionning but hyperlink author and tags not.

 

Thanks again try to help me.

 

De : Rainer Volz [mailto:notifications@github.com] 
Envoyé : dimanche 4 janvier 2015 20:21
À : rvolz/BicBucStriim
Cc : JPreacher
Objet : Re: [BicBucStriim] Error loading Page on author tags and series (#136)

 

So what changed sosuddenly? Did you upgrade your QNAP?

**Comment by rvolz** [comment]
I would need to know what was upgraded. Do you have any specifc information? 
Is there error information in you server log?

**Comment by JPreacher** [comment]
Hi,

 

The only thing upgrade is the QNAP 453 in QTS version 4.1.2 build 1231.

And there is no error on my server log.

Sorry for lack of information to help me.

I have no problem to log in bicbuc striim. All books appeared but there are no templates for authors and no links as usual since issue occured.

 

Thanks again to help me find a solution…

 

De : Rainer Volz [mailto:notifications@github.com] 
Envoyé : lundi 5 janvier 2015 23:54
À : rvolz/BicBucStriim
Cc : JPreacher
Objet : Re: [BicBucStriim] Error loading Page on author tags and series (#136)

 

I would need to know what was upgraded. Do you have any specifc information? 
Is there error information in you server log?

**Comment by rvolz** [comment]
Sorry, I looked at http://www.qnap.com/i/en/product_x_down/firmware_log.php?kw=TS-239%20Pro%20II&fsn=3900 but I can't se anything there. Maybe you should ask in the QNAP forum?
