### ISSUE TITLE
update 1.2.2. to 1.2.4 on Synology 5.1

### ISSUE THREAD

**Issue by d3dhemmer** [rvolz/BicBucStriim#137]
Hallo Herr  Rainer Volz,

Ich wende mich an sie da ich nicht so wirklich mit meiner Synology zurecht komme.
Also ich habe unter Version 5 der Systemsoftware von Synology ihre Software manuell installiert.
Jetzt möchte ich auf die neueste Version updaten.
Durch das Paketzentrum und die Community wird mir Version1.2.4- angeboten.
Nun habe ich versucht es einfach "drüber" zu Bügeln! (sorry für die Ausdrucksweise)
Keinen Erfolg hatte ich, siehe screenshoots.
Ich habe auch eine download ZIP gefunden. 
Bin mir aber unsicher wie ich sie Installieren soll.

Für etwas Hilfe währe ich sehr dankbar.

Mit freudlichem Gruß
Hans-Peter Hemmer

https://github.com/rvolz/BicBucStriim

http://d3dhemmer.synology.me/bbs/admin/version/

Hallo Herr  Rainer Volz,

Ich wende mich an sie da ich nicht so wirklich mit meiner Synology zurecht komme.
Also ich habe unter Version 5 der Systemsoftware von Synology ihre Software manuell installiert.
Jetzt möchte ich auf die neueste Version updaten.
Durch das Paketzentrum und die Community wird mir Version1.2.4- angeboten.
Nun habe ich versucht es einfach "drüber" zu Bügeln! (sorry für die Ausdrucksweise)
Keinen Erfolg hatte ich, siehe screenshoots.
Ich habe auch eine download ZIP gefunden. 
Bin mir aber unsicher wie ich sie Installieren soll.

Für etwas Hilfe währe ich sehr dankbar.

Mit freudlichem Gruß
Hans-Peter Hemmer

https://github.com/rvolz/BicBucStriim

http://d3dhemmer.synology.me/bbs/admin/version/

![1](https://cloud.githubusercontent.com/assets/2989345/5613146/e14cb5c6-94df-11e4-8ca6-d86027c24565.png)
![2](https://cloud.githubusercontent.com/assets/2989345/5613147/e7030902-94df-11e4-9626-b11fcc0f6f5f.png)

**Comment by rvolz** [comment]
Hallo Herr Hemmer,

bei dem Community-Paket bin ich etwas überfragt, das haben Leute von https://synocommunity.com/ gemacht. Ich konnte es bisher noch nicht ausprobieren. 

Ihr Screenshot weist nur daraufhin, dass das Verzeichnis mit der calibre-Bibliothek in den open_basedir-Pfad eingetragen werden muss. Wenn sie schon 1.2.2 laufen haben, sollte das ja schon erledigt sein.

Wenn bei der Installation Fehler auftreten, sollten sie vielleicht vorher die alte Installation löschen (oder zur Sicherheit umbenennen). Ich nehme mal an, dass die auch in das Verzeichnis /volume1/web/bbs schreiben wollen, das ich als Standardverzeichnis nutze. Eventuell reagiert das Paket allergisch, wenn an der Stelle schon etwas vorhanden ist.

Wenn das nicht funktioniert, und sie 1.2.4 via ZIP-Datei installieren wollen: die Vorgehensweise ist hier http://projekte.textmulch.de/bicbucstriim/ beschrieben. 

Hoffe, das hilft

**Comment by d3dhemmer** [comment]
Es hat geholfen, ich bin  begeistert ! Danke

Wie bei in Version 1.2.2 gibt es unten mittig unter Start keinen Button
Seitenzahl => [vor] welchen es unter Bücher/Autoren/Schlagwörter/Reihen
gibt.

HPH

Am 5. Januar 2015 um 23:49 schrieb Rainer Volz <notifications@github.com>:

**Comment by rvolz** [comment]
Ja, das war so geplant. Mit Issue #50 soll das geändert werden.

**Comment by d3dhemmer** [comment]
Hallo Herr Volz,

kann ich auch BicBus auf einer Synology laufen lassen.
Möchte einige Hörbücher in meiner Familie zur Verfügung stellen.
HPH

Am 6. Januar 2015 um 10:51 schrieb Hans-Peter Hemmer <d3dhemmer@gmail.com>:

**Comment by d3dhemmer** [comment]
Hallo Herr Volz

Habe soeben auf Synology-NAS mit BicBucStriim 1.2.4
<https://github.com/rvolz/BicBucStriim> das Admin PW geändert,
so wie 2 neue User angelegt.....
Leider sehen jetzt *alle *nur noch ein PDF Buch.
Würde mich über ihre Rat sehr freuen.

HPH

Am 7. Januar 2015 um 13:54 schrieb Hans-Peter Hemmer <d3dhemmer@gmail.com>:

**Comment by rvolz** [comment]
Ich kann das leider nicht reproduzieren. Habe es nachgestellt. Welche Synology, Firmware Version haben sie denn?

**Comment by d3dhemmer** [comment]
Es ist DSM 5.1-5021 Update 2

Habe noch die Version 1.2.2 unter
http://d3dhemmer.synology.me/xbbs/
da ist alles ok (admin-admin)
unter 1.2.4 also hier
http://d3dhemmer.synology.me/bbs/login/ (gerhard-ecvan)
nur eine Datei.
wenn ich unter Autoren/Schlagwörter schaue bekomme ich auch
die Zahlen gezeigt (zB. 3), selektiere ich diesen Bereich bekomme ich aber
kein Buch zusehen.



Am Donnerstag, 8. Januar 2015 schrieb Rainer Volz :

**Comment by rvolz** [comment]
Dann ist anscheinend ein Filter gesetzt. Bei der Benutzerkonfiguration in 1.2.4  kann ja nach Sprache und Schlagwort gefiltert werden.

**Comment by d3dhemmer** [comment]
Super Sie haben "Recht"
Hatte die Sprache auf deutsch gestellt.und Schlagwörter belassen.
(hatte nicht richtig geschaut, dachte damit stelle ich Menüsprache auf
deutsch ein)
Habe jetzt alle zurück gestellt und es funkt.
Herzlichen Dank.
PS. Wenn ich eine Buchtreihe nur für meine Neffen unter 10 Jahre
zusammenstelle,
Wie soll ich es Strukturieren?


Am 9. Januar 2015 um 07:23 schrieb Rainer Volz <notifications@github.com>:

**Comment by rvolz** [comment]
Die normale Vorgehensweise ist, alle unerwünschten Titel mit einem Schlagwort zu versehen, und das dann als Filter für den Benutzer einzustellen. Die Alternative ist, mit Calibre eine zweite Bibliothek anzulegen, und dann einfach eine zweite BBS-Intanz dafür laufen zu lassen.

**Comment by d3dhemmer** [comment]
Ich denke ich begebe mich an die Alternative.
Da einfacher und übersichtlicher, Schlagwörter sind für mich schwieriger zu
handeln und zu verfolgen.

Am 9. Januar 2015 um 09:02 schrieb Rainer Volz <notifications@github.com>:
