### ISSUE TITLE
Failed Calibre Library Check

### ISSUE THREAD

**Issue by joeylutes** [rvolz/BicBucStriim#138]
Hello, I have a new/fresh install of BBS on my Synology DS412+ DSM 5.1-5021 Update 2.
I've downloaded and installed bbs from Community ver 1.2.4-3 via Package Center

Upon running the Installation check, the calibre library remains red and no books display.  I can access the web interface, and login, however I continue to get the following message:  "The configured Calibre directory cannot be used. Is it really a Calibre directory? Is it readable? Does it exist?"

I have spent 3 days searching for a resolution.  Here are other pertinent facts:

Enable PHP Cache:  Checked
Enable display_errors to display PHP error message:   Checked
Customize PHP open_basedir:  Checked
open_basedir:  /etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1/books/calibre

SSH VIEW:
<SERVER>> pwd
/volume1/books/calibre
<SERVER>>ls -l metadata.db
-rwxrwxrwx    1 admin    users     90760192 Jan  4 13:39 metadata.db

After wading through hundreds of blogs/articles, the only one I've found that might have some info is here:  https://github.com/rvolz/BicBucStriim/issues/121
They talk about the metadata.db potentially creating an issue if it's over 32MB (last post).  Mine is almost 90MB.

On the Installation check page, here are results:

Calibre directory:  RED
Is Mcrypt enabled?:  Yellow.  No
Is PHP module intl enabled:  Yellow.  No
Is the open_basedir restriction in effect?:  Yellow Yes.  (reflects value pasted above)

Everything else is green.

I have rebooted the server several times.

Help?

Thank you

Joey Lutes

**Comment by rvolz** [comment]
There was issue #129 with the same/a similar? problem. The solution there was that now also the folder, in which metadata.db resides, most be executable. Something changed there. 

Could you please check this issue too?

**Comment by joeylutes** [comment]
It is.  See below
<SERVER>> pwd
/volume1/books
<SERVER>> ls -l
drwxrwxrwx 15279 admin    users       520192 Jan  4 18:53 calibre

**Comment by joeylutes** [comment]
Thoughts anyone?  I have re-installed the program and set it up again.  Also re-copied metadata.db over and ensured appropriate permissions - it's still not recognizing the file/directory.

**Comment by rvolz** [comment]
I'll add some tests to installcheck.php to get more information about such problems, probably during the weekend.

**Comment by rvolz** [comment]
There is a new installcheck.php. It shows some details when the library check fails. Could you please try that one?

**Comment by joeylutes** [comment]
be happy to - are there instructions, or?
Thanks for your help!

**Comment by rvolz** [comment]
No, just check the library path. If that fails the page will show more details, where it failed.

**Comment by joeylutes** [comment]
Complete - no change.
I noticed you added a couple new items:

Is the data directory writeable?
yes (green)
Is data/data.db writeable?
yes (green)
Only yellow items in Environment Checks are
Mcrypt, PHP module intl, and open_basedir
The rest are green.

Calibre library check still fails.

Let me know if I should be looking in a different location for errors.
Thanks

**Comment by rvolz** [comment]
The interesting part is below the Calibre library check. If you check the library path and this check fails, a couple of details should appear below, like:

* Directory exists? ...
* Directory is readable? ...
* ...
* Database opened?

What is displayed there?

**Comment by joeylutes** [comment]
![image](https://cloud.githubusercontent.com/assets/10409056/5712709/56b20ccc-9a7a-11e4-80a0-d665fa0e4dfa.png)

![image](https://cloud.githubusercontent.com/assets/10409056/5712716/6cae5814-9a7a-11e4-8a80-75bda2b0d420.png)

**Comment by joeylutes** [comment]
That's the entire page.  Hope that's what you're looking for?

**Comment by rvolz** [comment]
Sorry for the confusion: the new installcheck.php is here on Github. If you download the current version and run installcheck.php you should see additional detail below the library check, lhopefully more informative than this:
![firefoxscreensnapz020](https://cloud.githubusercontent.com/assets/1092531/5717290/7ebb7a8a-9afe-11e4-830b-ac500693b9ac.png)

**Comment by joeylutes** [comment]
I'm sorry - tried my best today, but having issues.
I've tried various things - the most logical of which was to download the new installcheck.php file that was edited 2 days ago, and I renamed the old one in /volume1/web/bbs and copied the new one to that directory (as root), and ran chmod 644 on it (to match the old one).  It did come up in the browser, however it does not show what you're showing above, so I'm assuming I didn't do something correct.  Instead, it looked just like the existing page.  I know it's reading off of the new file, because if I rename it and try to access it via a browser, it redirects me back to the admin page.

Sorry for not understanding . . . I also downloaded the newest repo of 1.2.4, but that installcheck.php is dated 7/20/14, so I'm sure that's not the answer.
Thoughts?

**Comment by rvolz** [comment]
Ah, ok. If you do it that way, you will also need to dowload the template file, https://github.com/rvolz/BicBucStriim/blob/master/templates/installcheck.html

With the system used here, the .php files contain the functionality and the template files visualize it.

**Comment by joeylutes** [comment]
Ok - now we're cookin' with gas . . 
Error on the top of the page:
Warning: file_exists(): open_basedir restriction in effect. File(/volume1/books/calibre) is not within the allowed path(s): (/etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1/books/calibre) in /volume1/web/bbs/installcheck.php on line 60

![image](https://cloud.githubusercontent.com/assets/10409056/5740722/a4fdc63a-9bcb-11e4-93a8-0f0fc7df660d.png)

**Comment by rvolz** [comment]
Interesting, the message is clear, the reason why is not. 

Your open_basedir path looks ok to me. Are there spaces or other characters in the paths? Or does it work if you move the library somewhere else?

**Comment by joeylutes** [comment]
I can try to move the library.  There are no spaces - I even stuck the path in the middle of the open_basedir to see if that changed anything - the error message updated, but the results were identical.  I have double-checked the path many times.  I will try moving the path.
