### ISSUE TITLE
error loading page @ configuration

### ISSUE THREAD

**Issue by rudyh** [rvolz/BicBucStriim#14]
Hi, I justed 'installed' BicBusStriim on my nas. (it says v 0.9.2 on the bottom of the page)

When I go to http://nas/bbs I get the configuration screen. But I'm not able to save my settings.
It keeps telling me: 'error loading page' after I've filled in the Calibre library path (being /volume1/ebooks) and hitting 'save'. So I didn't change anything else.

My bbs/data dir is set to '777' so it should be writable.

**Comment by t0000** [comment]
how can help me?
I have BicBucStriim installed from packages http://packages.synocommunity.com on my ds213j.
on installcheck.php is all green.
on /bbs/admin/configuration/ say by save "Änderungen gespeichert"
when i klick on start button
then "Error loading page"

I have nas restartet.
PHP open_basedir :
/etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1/books


Diskstation> ll
drwxr-xr-x   10 root     root          4096 Oct 21 19:37 .
drwxr-xr-x   23 root     root          4096 Oct 21 19:36 ..
drwxr-xr-x    2 root     root          4096 Oct 19 20:27 @S2S
drwxrwxrwx    3 root     root          4096 Oct 21 18:22 @appstore
drwxr-xr-x    4 admin    users         4096 Oct 19 20:27 @database
drwxrwxrwx    4 root     root          4096 Oct 21 18:13 @eaDir
drwxrwxrwt    4 root     root          4096 Oct 21 19:38 @tmp
-rw-------    1 root     root          7168 Oct 21 19:35 aquota.group
-rw-------    1 root     root          8192 Oct 21 19:35 aquota.user
d---------    4 root     root          4096 Oct 20 17:52 books
drwx------    2 root     root         16384 Oct 19 20:27 lost+found
-rw-------    1 root     root          5120 Oct 19 20:36 synoquota.db
d---------    5 root     root          4096 Oct 21 18:22 web

Diskstation> ll
d---------    5 root     root          4096 Oct 21 18:22 .
drwxr-xr-x   10 root     root          4096 Oct 21 19:37 ..
drwxrwxrwx    3 root     root          4096 Oct 21 19:37 @eaDir
drwxr-xr-x   11 http     root          4096 May 27 18:19 bbs
-rwxrwxrwx    1 root     root          1538 Oct 19 20:30 index.html
drwxr-xr-x    2 root     root          4096 Oct 19 20:30 web_images

Diskstation> ll
drwxr-xr-x   11 http     root          4096 May 27 18:19 .
d---------    5 root     root          4096 Oct 21 18:22 ..
-rw-r--r--    1 http     root           120 May 27 18:19 .gitignore
-rw-r--r--    1 http     root           543 May 27 18:19 .htaccess
-rw-r--r--    1 http     root          4176 May 27 18:19 ChangeLog
-rw-r--r--    1 http     root           246 May 27 18:19 Gemfile
-rw-r--r--    1 http     root          1399 May 27 18:19 Gemfile.lock
-rw-r--r--    1 http     root           122 May 27 18:19 Guardfile
-rw-r--r--    1 http     root          1214 May 27 18:19 LICENSE
-rw-r--r--    1 http     root         12855 May 27 18:19 NOTICE
-rw-r--r--    1 http     root          6351 May 27 18:19 README.md
-rwxr-xr-x    1 http     root          5395 May 27 18:19 Rakefile.rb
-rw-r--r--    1 http     root         45606 May 27 18:19 bbs-icon.png
-rw-r--r--    1 http     root           212 May 27 18:19 composer.json
-rw-r--r--    1 http     root         11761 May 27 18:19 composer.lock
drwxrwxrwx    4 http     root          4096 Oct 21 19:38 data
-rw-r--r--    1 http     root          2238 May 27 18:19 favicon.ico
drwxr-xr-x    8 http     root          4096 May 27 18:19 features
drwxr-xr-x    2 http     root          4096 May 27 18:19 img
-rw-r--r--    1 http     root         62722 May 27 18:19 index.php
-rw-r--r--    1 http     root          3468 May 27 18:19 installcheck.php
drwxr-xr-x    3 http     root          4096 May 27 18:19 js
drwxr-xr-x    3 http     root          4096 May 27 18:19 lib
-rw-r--r--    1 http     root         43704 May 27 18:19 messages.yml
drwxr-xr-x    4 http     root          4096 May 27 18:19 style
drwxr-xr-x    2 http     root          4096 May 27 18:19 templates
drwxr-xr-x    5 http     root          4096 May 27 18:19 tests
drwxr-xr-x    8 http     root          4096 May 27 18:19 vendor

Diskstation> ll
drwxrwxrwx    4 http     root          4096 Oct 21 19:38 .
drwxr-xr-x   11 http     root          4096 May 27 18:19 ..
drwxrwxrwx    2 http     http          4096 Oct 21 18:49 authors
-rwxrwxrwx    1 http     root         18432 Oct 21 19:38 data.db
-rwxrwxrwx    1 http     root             9 May 27 18:19 index.php
-rwxrwxrwx    1 http     root          1633 May 27 18:19 schema.sql
drwxrwxrwx    2 http     http          4096 Oct 21 18:49 titles

here pics :
http://www0.xup.in/exec/ximg.php?fid=21120202
http://www0.xup.in/exec/ximg.php?fid=11096168

big thx for help

**Comment by rvolz** [comment]
The easiest way is to diagnose the problem is to look into the error log of your web server. If this isn't enabled on your NAS then you could enable error logging in BicBucStriim. Change index.php (from line 38)

```php
# Init app and routes
$app = new \Slim\Slim(array(
    'view' => new \Slim\Views\Twig(),
    'mode' => 'production',
    #'mode' => 'debug',
    #'mode' => 'development',
));
```
to 
```php
    #'mode' => 'production',
    'mode' => 'debug',
```

Then the `data` directory will contain log files with error information.

**Comment by t0000** [comment]
this is now the error:

Details

Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1 no such table: books
File: /volume1/web/bbs/lib/BicBucStriim/calibre.php
Line: 79
Trace

#0 /volume1/web/bbs/lib/BicBucStriim/calibre.php(79): PDO->query('select * from b...', 8, 'Book')
#1 /volume1/web/bbs/lib/BicBucStriim/calibre.php(341): Calibre->find('Book', 'select * from b...')
#2 /volume1/web/bbs/index.php(903): Calibre->last30Books('de', 30, Object(CalibreFilter))
#3 [internal function]: main()
#4 /volume1/web/bbs/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('main', Array)
#5 /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()
#6 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /volume1/web/bbs/lib/BicBucStriim/calibre_config_middleware.php(50): Slim\Middleware\MethodOverride->call()
#9 /volume1/web/bbs/lib/BicBucStriim/login_middleware.php(33): CalibreConfigMiddleware->call()
#10 /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php(33): LoginMiddleware->call()
#11 /volume1/web/bbs/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#12 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#13 /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#14 /volume1/web/bbs/index.php(200): Slim\Slim->run()
#15 {main}

**Comment by rvolz** [comment]
That error means that something is wrong with your Calibre db, which ist stored in file `metadata.db` in the Calibre library directory. Can you open this library with Calibre?

**Comment by t0000** [comment]
i have only the BicBucStriim in my packetcentre intstalled. I need to install another package additionally ?

**Comment by rvolz** [comment]
No additional package. I was talking about your Calibre library, that you installed in `/volume1/books`, right?

**Comment by t0000** [comment]
yes is right.
Diskstation> ll /volume1/books/
drwxrwxrwx    2 root     root          4096 Oct 20 17:50 #recycle
d---------    4 root     root          4096 Oct 20 17:52 .
drwxr-xr-x   10 root     root          4096 Oct 21 20:06 ..
drwxrwxrwx    3 root     root          4096 Oct 21 20:06 @eaDir
-rwxrwx---    1 admin    users            0 Oct 20 17:52 metadata.db
Diskstation>

**Comment by rvolz** [comment]
Not right. `metadata.db` is empty (0), and where are the books? It seems you haven't copied your library. BicBucStriim can't work without a valid library.  

You have to create a Calibre library first, add your books, and copy it to that directory.

**Comment by t0000** [comment]
i have i pub uploadet over the webbrower in Filestation. and now is metadata.db still 0

drwxrwxrwx    2 root     root          4096 Oct 20 17:50 #recycle
d---------    4 root     root          4096 Oct 22 18:42 .
drwxr-xr-x   10 root     root          4096 Oct 22 18:46 ..
drwxrwxrwx    3 root     root          4096 Oct 22 18:46 @eaDir
-rwxrwx---    1 admin    users       750832 Sep 12 15:59 Robinson, Maggie - Ein Skandal in Schottland.epub
-rwxrwx---    1 admin    users            0 Oct 20 17:52 metadata.db

Do I need to do something else?
will be created the metadata.db automatically?

**Comment by rvolz** [comment]
You need a library created with (Calibre)[http://calibre-ebook.com/]. Calbre will create  a `metadata.db` fo you. Maybe this helps:


> BicBucStriim ist eine Web-Anwendung, die eine digitale Büchersammlung im Calibre-Format publiziert und für mobile Geräte bequem zugänglich macht. Calibre, die weit verbreitete Software für die Verwaltung von elektronischen Bibliotheken (für Linux, Windows und OSX verfügbar), wird mit den meisten gängigen Buchformaten fertig. Als PC-Anwendung besitzt es auch einen eingebauten HTTP-Server, der funktioniert aber eben nur, solange der PC eingeschaltet ist und Calibre läuft. BicBucStriim wurde dagegen dafür konzipiert, auf eher schwach ausgestatteten NAS-Laufwerken zu laufen und die dort gespeicherte Calibre-Bibliothek per Web-Schnittstelle verfügbar zu machen. Der PC kann also ausgeschaltet bleiben, man kommt aber trotzdem jederzeit an seine Bücher heran.

**Comment by t0000** [comment]
i have my nas new installed, and all data deletet. after install have the packed BicBucStriim installed from packages http://packages.synocommunity.com.
Do I need to install something else?
