### ISSUE TITLE
Books cant be delivered through email

### ISSUE THREAD

**Issue by derdigge** [rvolz/BicBucStriim#142]
I tried several times (SMTP with gmail) the mail returns with following error:
It wants to convert an AZW3? Its the native format afaik.
The Kindle is a paperwhite bought for Christmas this year.

Return Message:
Sehr geehrter Kunde,

Das folgende Dokument, gesendet am 11:27 Uhr, am Mittwoch, 14. Januar 2015 MEZ, konnte nicht an den angegebenen Kindle geliefert werden:
* #1 - Heimat i bin dir so nah (Kurhotel Alp - Franz Huber.azw3

Der Kindle Persönliche Dokumente Service kann folgende Arten von Dokumenten konvertieren und liefern:
Microsoft Word (.doc, .docx)
Rich Text Format (.rtf)
HTML (.htm, .html) 
Text (.txt)-Dokumente
Archivierte Dokumente (zip , x-zip) und komprimierte archivierte Dokumente
Mobi-Buch

Bilder in den Formaten JPEG (.jpg), GIF (.gif), Bitmap (.bmp) und PNG (.png).
Dokumente im Adobe PDF-Format (.pdf) werden an Kindle DX sowie Kindle der zweiten und neusten Generation ohne Umwandlung gesendet.

Dokumente im Adobe PDF-Format (.pdf) können auf experimenteller Basis in das Kindle-Format umgewandelt und geliefert werden.

Wenn die fehlgeschlagenen Dokumente eines der oben genannten Formate haben, stellen Sie sicher, dass das Dokument nicht passwortgeschützt oder verschlüsselt ist. Beachten Sie, dass die Kindle der neusten Generation passwortgeschützte PDFs unterstützen.

Hilfreiche Tipps für Dateianhänge von persönlichen Dokumenten:
Die Dateigröße jedes angehängten persönlichen Dokuments sollte kleiner als 50 MB (vor der Komprimierung zu einer ZIP-Datei)
Die übermittelte E-Mail sollte nicht mehr als 25 persönliche Dokumente im Anhang enthalten.

Weitere Informationen über das Übertragen persönlicher Dokumente zu Ihrem Kindle finden Sie in unseren Hilfe-Seite:
http://www.amazon.de/kindle-persoenliche-dokumente/

Wenn Sie sofort Unterstützung benötigen, kontaktieren Sie bitte den Kundenservice unter 0800 589 0067 (innerhalb Deutschlands) oder +49 89 22 06 10 41 (außerhalb Deutschlands).

Mit freundlichen Grüßen,
Amazon Kindle Support

Anmerkung: Diese E-Mail wurde von einer ausschließlich für Benachrichtigungen vorgesehenen E-Mail-Adresse gesendet, die keine eingehenden E-Mails empfangen kann. Antworten Sie nicht auf diese Nachricht.

Weitere Informationen über Amazon Kindle
Besuchen Sie den Kindle-Shop

Lesen Sie bei weiteren Fragen zu Kindle die Hilfeseiten für Amazon Kindle
In den Hilfeseiten finden Sie Antworten auf häufig gestellte Fragen sowie einen Link zu Amazon Kindle-Experten.
Um den Amazon Kindle-Kundenservice zu kontaktieren, klicken Sie einfach auf eine Schaltfläche im Kontakt-Feld der Hilfeseiten, um Unterstützung per Telefon oder E-Mail zu erhalten.

**Comment by derdigge** [comment]
Just digged deeper now.
I can send manually .mobi and it arived.
if i send azw manually it returns, no matter if its azw3 azw or arw2.
Ho to tell bicbucstriim to send only mobi? i have slightly php knowledge.
If You tell me in what document/function i have to dig, i can do it on my own.

**Comment by rvolz** [comment]
BicBucStriim can only send .mobi files if this format is available in the Calibre library. It does not transform book formats. 

If mailing AZW3 does not work, just open the Kindle browser and download the books via BicBucStriim. That works fine.

**Comment by derdigge** [comment]
ok i know that it cant Convert. but if you have azw3 AND mobi already in database it prefers the azw3.

**Comment by rvolz** [comment]
Ah, now I see your problem! Go to lib/calibre.php and search for the function ```kindleFormatSort```. There is an array that determins the best Kindle formats:

```php
         //global $kindleformats;
	  $kindleformats[0] = "AZW3"; 
	  $kindleformats[1] = "AZW"; 
	  $kindleformats[3] = "MOBI"; 
	  $kindleformats[4] = "HTML";
	  $kindleformats[5] = "PDF";
```

Simply put your preferred format in  $kindleformats[0].

**Comment by derdigge** [comment]
I asked arround to determine whats on here.
Since december Amazon is selling paperwhite with LIMITED azw3 support.
Two friends bought they're paper whites in January 2014, my sister June 2014 and another friend October 2014. All these can download azw3 and receive azw3 by email without issues.

My mom and i bought one in December. Both can not Download or receive azw3 by email.
But when you put azw3 on that new kindle paperwhite whith usb it works.
So Amazon is changing something here in software for sure.
Is there a reason azw3 is default in you git repo?

**Comment by rvolz** [comment]
That part was added by other authors, it was their preference. 

I don't use emailing with the Kindle. I just use the built-in browser to download the books via BicBucStriim. That way you can choose the format.

**Comment by derdigge** [comment]
You should consider to change it. Mobi can be received and used by all kindles instead azw3.
I change it for me he locally but there are lots of others........
