### ISSUE TITLE
open_basedir error while in path

### ISSUE THREAD

**Issue by bijnj01** [rvolz/BicBucStriim#143]
G'd eve,

My installcheck.php keeps blinking red, saying that the calibre dir is not within the allowed paths.
But it IS, as you can see from the apache error_log line below.
I restarted apache and I restarted php-fpm

[Sat Jan 17 22:46:59 2015] [error] [client 192.168.11.1] FastCGI: server "/php-fpm-handler" stderr: PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/volume1/homes/kugga/calibre) is not within the allowed path(s): (/etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1/homes/kugga/calibre) in /volume1/web/kxxxt/html/bbs/installcheck.php on line 68, referer: http://kxxxt.org/bbs/installcheck.php

The calibre directory itself and everything inside is owned by http:http, permissions on the dir are 755, inside the calibre dir 644. The db file is 755.
-rwxr-xr-x    1 http     http      12811264 Jan 16 21:35 metadata.db

System is Synology 5.1-5021 update 2
My question: did I overlook something installing BicBucStriim?

**Comment by rvolz** [comment]
In issues #138 and #121 several possibilities have already been discussed. Could you please check there?
