### ISSUE TITLE
error loading page

### ISSUE THREAD

**Issue by badhabits999** [rvolz/BicBucStriim#144]
Hi there,
i got bbs installed on my synology nas for a while now. been working great until last weekend. 
now when i try to use the search function i get error loading page.
anyone able to help me out on why this happens and how to fix this?

Greatly appreciated

Eric
ps: install check done all ok just yellow light at open_base dir though that was before aswell

**Comment by rvolz** [comment]
Until now errors with the search page have only been reported by people using nginx as web server, see #135  Just to check: you use the normal Synology setup, yes?

What version is your BicBucStriim installation?

**Comment by badhabits999** [comment]
using the synocommunity package now, tried the one from your website aswell but both having same issue.
version is the 1.2.4

**Comment by rvolz** [comment]
Maybe we discover the source of your problem in the log files. Please enable debug mode by editing file `index.php` at the top. It should then look like this:

```php
# Init app and routes
$app = new \Slim\Slim(array(
'view' => new \Slim\Views\Twig(),
#'mode' => 'production',
'mode' => 'debug',
#'mode' => 'development',
));
```

In debug mode the app creates log files in the data directory. If you  perform a search after enabling debug mode the error should be documented in the log file.

**Comment by badhabits999** [comment]
Hmm you are not gonna believe this, put the debug mode on and its searching
ok now. will keep it on for now to see what happens and if the error will
get back as it did before.
as soon as i get the error back will let you know and send in the log file
then aswell.

thnx for all

2015-01-22 21:39 GMT+01:00 Rainer Volz <notifications@github.com>:

**Comment by G1zm0** [comment]
I got the same issue:

Running on a Synology DS109 DSM 4.2-3252
PHP 5.3.29
Apache webserver.

I don't use the package.

I throws the error "error loading page"
But when I press "HOME" everything works and the page loads...???

my logs:
```
INFO - 2015-01-23T17:44:27+01:00 - BicBucStriim 1.2.5a: Running in debug mode.
DEBUG - 2015-01-23T17:44:27+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-23T17:44:27+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-23T17:44:27+01:00 - login resource: /login/
DEBUG - 2015-01-23T17:44:27+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-23T17:44:27+01:00 - login: login page authorized
DEBUG - 2015-01-23T17:44:27+01:00 - login: array (
  'username' => 'myusername',
  'password' => '--redacted--',
  'login' => '',
)
DEBUG - 2015-01-23T17:44:27+01:00 - login success: true
INFO - 2015-01-23T17:44:29+01:00 - BicBucStriim 1.2.5a: Running in debug mode.
DEBUG - 2015-01-23T17:44:29+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-23T17:44:29+01:00 - login resource: /
DEBUG - 2015-01-23T17:44:29+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-23T17:44:29+01:00 - getFilter: array (
  'id' => '2',
  'username' => 'myusername',
  'email' => NULL,
  'languages' => NULL,
  'tags' => NULL,
  'logged_in' => true,
)
DEBUG - 2015-01-23T17:44:29+01:00 - getFilter: Using language , tag 
INFO - 2015-01-23T17:46:09+01:00 - BicBucStriim 1.2.5a: Running in debug mode.
DEBUG - 2015-01-23T17:46:09+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-23T17:46:09+01:00 - login resource: /logout/
``

**Comment by G1zm0** [comment]
Looks like I have the same error as
https://github.com/rvolz/BicBucStriim/issues/125
Sorry duplicate

**Comment by rvolz** [comment]
There are no errors in the log. Could you check the browser's error information? With Firebug or something similar? 

 DSM 4.2-3252 is bit old for me, I have DSM 5, although I'm testing with PHP 5.3.10, which is older than yours. No problems so far.

**Comment by G1zm0** [comment]
Firefox doesn't report the error. I normally use chrome.
The login is completed, but the redirect to "Home" doesn't work.
If I press it myself all is well..

**Comment by rvolz** [comment]
If it is the same problem as in #125 you will have to use the same workaround for the moment.

**Comment by badhabits999** [comment]
New strange issue now. i can use my login and after login it wont take me to home page. i have to click the home button. if i use someone elses useraccount it wont do anything at all. stays on login page and clicking home wont work either.
log file:
INFO - 2015-01-29T10:22:09+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:22:12+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:22:13+01:00 - login resource: /
DEBUG - 2015-01-29T10:22:13+01:00 - login accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
DEBUG - 2015-01-29T10:22:13+01:00 - login: redirecting to login
INFO - 2015-01-29T10:22:19+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:22:19+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:22:19+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:22:20+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:22:20+01:00 - login accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
DEBUG - 2015-01-29T10:22:20+01:00 - login: login page authorized
INFO - 2015-01-29T10:22:50+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:22:51+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:22:51+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:22:51+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:22:51+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:22:51+01:00 - login: login page authorized
DEBUG - 2015-01-29T10:22:51+01:00 - login: array (
  'username' => '****',
  'password' => '**********',
  'login' => '',
)
DEBUG - 2015-01-29T10:22:51+01:00 - login success: true
INFO - 2015-01-29T10:22:51+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:22:51+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:22:51+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:22:51+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:22:51+01:00 - login accept: text/html, */*; q=0.01
INFO - 2015-01-29T10:22:56+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:22:56+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:22:57+01:00 - login resource: /
DEBUG - 2015-01-29T10:22:57+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:22:57+01:00 - getFilter: array (
  'id' => '9',
  'username' => '****',
  'email' => NULL,
  'languages' => NULL,
  'tags' => NULL,
  'logged_in' => true,
)
DEBUG - 2015-01-29T10:22:57+01:00 - getFilter: Using language , tag 
INFO - 2015-01-29T10:23:02+01:00 - BicBucStriim 1.2.4: Running in debug mode.
INFO - 2015-01-29T10:23:02+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:02+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:02+01:00 - login resource: /titles/37372/thumbnail
DEBUG - 2015-01-29T10:23:02+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:23:02+01:00 - thumbnail: 37372
INFO - 2015-01-29T10:23:02+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:02+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:02+01:00 - login resource: /titles/37373/thumbnail
DEBUG - 2015-01-29T10:23:02+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:23:02+01:00 - thumbnail: 37373
DEBUG - 2015-01-29T10:23:02+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:02+01:00 - login resource: /titles/37377/thumbnail
DEBUG - 2015-01-29T10:23:02+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:23:02+01:00 - thumbnail: 37377
INFO - 2015-01-29T10:23:06+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:06+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:06+01:00 - login resource: /logout/
DEBUG - 2015-01-29T10:23:06+01:00 - login accept: text/html, */*; q=0.01
INFO - 2015-01-29T10:23:22+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:22+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:23:22+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:22+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:23:22+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:23:22+01:00 - login: login page authorized
DEBUG - 2015-01-29T10:23:22+01:00 - login: array (
  'username' => '****',
  'password' => '**************',
  'login' => '',
)
DEBUG - 2015-01-29T10:23:22+01:00 - login success: false
INFO - 2015-01-29T10:23:25+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:25+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:25+01:00 - login resource: /
DEBUG - 2015-01-29T10:23:25+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:23:25+01:00 - login: redirecting to login
INFO - 2015-01-29T10:23:25+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:25+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:23:25+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:25+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:23:25+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:23:25+01:00 - login: login page authorized
INFO - 2015-01-29T10:23:42+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:42+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:23:42+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:42+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:23:42+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:23:42+01:00 - login: login page authorized
DEBUG - 2015-01-29T10:23:42+01:00 - login: array (
  'username' => '*****',
  'password' => '************',
  'login' => '',
)
DEBUG - 2015-01-29T10:23:42+01:00 - login success: false
INFO - 2015-01-29T10:23:46+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:46+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:46+01:00 - login resource: /
DEBUG - 2015-01-29T10:23:46+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:23:46+01:00 - login: redirecting to login
INFO - 2015-01-29T10:23:46+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:23:46+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:23:46+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:23:46+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:23:46+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:23:46+01:00 - login: login page authorized
INFO - 2015-01-29T10:27:15+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:15+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:27:15+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:15+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:27:15+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:27:15+01:00 - login: login page authorized
DEBUG - 2015-01-29T10:27:15+01:00 - login: array (
  'username' => '*****',
  'password' => '**********',
  'login' => '',
)
DEBUG - 2015-01-29T10:27:15+01:00 - login success: false
INFO - 2015-01-29T10:27:19+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:19+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:20+01:00 - login resource: /
DEBUG - 2015-01-29T10:27:20+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:27:20+01:00 - login: redirecting to login
INFO - 2015-01-29T10:27:20+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:20+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:27:20+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:20+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:27:20+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:27:20+01:00 - login: login page authorized
INFO - 2015-01-29T10:27:29+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:29+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:27:29+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:29+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:27:29+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:27:29+01:00 - login: login page authorized
DEBUG - 2015-01-29T10:27:29+01:00 - login: array (
  'username' => '******',
  'password' => '********',
  'login' => '',
)
DEBUG - 2015-01-29T10:27:30+01:00 - login success: true
INFO - 2015-01-29T10:27:30+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:30+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:27:30+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:30+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:27:30+01:00 - login accept: text/html, */*; q=0.01
INFO - 2015-01-29T10:27:32+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:32+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:32+01:00 - login resource: /
DEBUG - 2015-01-29T10:27:32+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:27:32+01:00 - getFilter: array (
  'id' => '9',
  'username' => '******',
  'email' => NULL,
  'languages' => NULL,
  'tags' => NULL,
  'logged_in' => true,
)
DEBUG - 2015-01-29T10:27:32+01:00 - getFilter: Using language , tag 
INFO - 2015-01-29T10:27:38+01:00 - BicBucStriim 1.2.4: Running in debug mode.
INFO - 2015-01-29T10:27:38+01:00 - BicBucStriim 1.2.4: Running in debug mode.
INFO - 2015-01-29T10:27:38+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:38+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:38+01:00 - login resource: /titles/37372/thumbnail
DEBUG - 2015-01-29T10:27:38+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:27:38+01:00 - thumbnail: 37372
DEBUG - 2015-01-29T10:27:39+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:39+01:00 - login resource: /titles/37373/thumbnail
DEBUG - 2015-01-29T10:27:39+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:27:39+01:00 - thumbnail: 37373
DEBUG - 2015-01-29T10:27:39+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:39+01:00 - login resource: /titles/37377/thumbnail
DEBUG - 2015-01-29T10:27:39+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:27:39+01:00 - thumbnail: 37377
INFO - 2015-01-29T10:27:47+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:27:47+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:27:47+01:00 - login resource: /logout/
DEBUG - 2015-01-29T10:27:47+01:00 - login accept: text/html, */*; q=0.01
INFO - 2015-01-29T10:28:06+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:06+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:28:06+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:06+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:28:06+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:28:06+01:00 - login: login page authorized
DEBUG - 2015-01-29T10:28:06+01:00 - login: array (
  'username' => '****',
  'password' => '************',
  'login' => '',
)
DEBUG - 2015-01-29T10:28:06+01:00 - login success: false
INFO - 2015-01-29T10:28:08+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:08+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:09+01:00 - login resource: /
DEBUG - 2015-01-29T10:28:09+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:28:09+01:00 - login: redirecting to login
INFO - 2015-01-29T10:28:09+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:09+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:28:09+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:09+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:28:09+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:28:09+01:00 - login: login page authorized
INFO - 2015-01-29T10:28:17+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:17+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:28:17+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:17+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:28:17+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:28:17+01:00 - login: login page authorized
DEBUG - 2015-01-29T10:28:17+01:00 - login: array (
  'username' => '*******',
  'password' => '***********',
  'login' => '',
)
DEBUG - 2015-01-29T10:28:17+01:00 - login success: true
INFO - 2015-01-29T10:28:17+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:17+01:00 - caching_middleware: caching disabled for /login/
DEBUG - 2015-01-29T10:28:17+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:17+01:00 - login resource: /login/
DEBUG - 2015-01-29T10:28:17+01:00 - login accept: text/html, */*; q=0.01
INFO - 2015-01-29T10:28:19+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:19+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:20+01:00 - login resource: /
DEBUG - 2015-01-29T10:28:20+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:28:20+01:00 - getFilter: array (
  'id' => '9',
  'username' => '****',
  'email' => NULL,
  'languages' => NULL,
  'tags' => NULL,
  'logged_in' => true,
)
DEBUG - 2015-01-29T10:28:20+01:00 - getFilter: Using language , tag 
INFO - 2015-01-29T10:28:23+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:23+01:00 - own_config_middleware: config loaded
INFO - 2015-01-29T10:28:23+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:23+01:00 - login resource: /titles/37377/thumbnail
DEBUG - 2015-01-29T10:28:23+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:28:23+01:00 - thumbnail: 37377
DEBUG - 2015-01-29T10:28:23+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:23+01:00 - login resource: /titles/37372/thumbnail
DEBUG - 2015-01-29T10:28:23+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:28:23+01:00 - thumbnail: 37372
INFO - 2015-01-29T10:28:23+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:23+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:23+01:00 - login resource: /titles/37373/thumbnail
DEBUG - 2015-01-29T10:28:23+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:28:23+01:00 - thumbnail: 37373
INFO - 2015-01-29T10:28:29+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:29+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:30+01:00 - login resource: /search/
DEBUG - 2015-01-29T10:28:30+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:28:30+01:00 - getFilter: array (
  'id' => '9',
  'username' => '******',
  'email' => NULL,
  'languages' => NULL,
  'tags' => NULL,
  'logged_in' => true,
)
DEBUG - 2015-01-29T10:28:30+01:00 - getFilter: Using language , tag 
INFO - 2015-01-29T10:28:41+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:41+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:41+01:00 - login resource: /
DEBUG - 2015-01-29T10:28:41+01:00 - login accept: text/html, */*; q=0.01
DEBUG - 2015-01-29T10:28:41+01:00 - getFilter: array (
  'id' => '9',
  'username' => '******',
  'email' => NULL,
  'languages' => NULL,
  'tags' => NULL,
  'logged_in' => true,
)
DEBUG - 2015-01-29T10:28:41+01:00 - getFilter: Using language , tag 
INFO - 2015-01-29T10:28:45+01:00 - BicBucStriim 1.2.4: Running in debug mode.
INFO - 2015-01-29T10:28:45+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:45+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:45+01:00 - login resource: /titles/37377/thumbnail
DEBUG - 2015-01-29T10:28:45+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:28:45+01:00 - thumbnail: 37377
DEBUG - 2015-01-29T10:28:45+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:45+01:00 - login resource: /titles/37373/thumbnail
DEBUG - 2015-01-29T10:28:45+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:28:45+01:00 - thumbnail: 37373
INFO - 2015-01-29T10:28:45+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:45+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:45+01:00 - login resource: /titles/37372/thumbnail
DEBUG - 2015-01-29T10:28:45+01:00 - login accept: image/png,image/*;q=0.8,*/*;q=0.5
DEBUG - 2015-01-29T10:28:45+01:00 - thumbnail: 37372
INFO - 2015-01-29T10:28:47+01:00 - BicBucStriim 1.2.4: Running in debug mode.
DEBUG - 2015-01-29T10:28:47+01:00 - own_config_middleware: config loaded
DEBUG - 2015-01-29T10:28:47+01:00 - login resource: /logout/
DEBUG - 2015-01-29T10:28:48+01:00 - login accept: text/html, */*; q=0.01

Browser changed, used pc and tablet and 2nd tablet.
bbs in is subdirectory vol1- web-bbs
