### ISSUE TITLE
[enhancement] admin options

### ISSUE THREAD

**Issue by G1zm0** [rvolz/BicBucStriim#145]
I would like to suggest some features if possible:

1) As admin show the login/logout of the userS in the http://mydomain.ext/admin/users/
2) As admin show the login/logout of the selected user in the http://mydomain.ext/admin/users/3/ and maybe track the downloaded books?

**Comment by rvolz** [comment]
Doing this in the admin interface is currently not planned. However, there are now log messages that can be used to collect these infos. All are on the INFO level:

1. Download: ``book download by <user name> for <file path> with metadata update = <status>``
2. Login: ``logged in user: <user name>``
3. Logout: ``logged out user: <user name>``
