### ISSUE TITLE
Zugriff für Rubriken vergeben

### ISSUE THREAD

**Issue by xantippe** [rvolz/BicBucStriim#148]
Hallo,

ich möchte meine Bücher endlich mal von meinem Rechner auf ein NAS bringen, damit der rest der Familie auch ohne mich sich was aussuchen & downloaden kann...

Spannende Frage wäre, ob man einen "Rubrikenschutz" einstellen kann/könnte, da meine Kids nicht alle Bücher sehen brauchen ;-)

Dank & Gruss

**Comment by rvolz** [comment]
Pro Benutzer kann man einstellen, dass Titel mit einem bestimmten Schlagwort nicht angezeigt werden sollen.
