### ISSUE TITLE
direct download button

### ISSUE THREAD

**Issue by Binog** [rvolz/BicBucStriim#150]
Hey there !
It would be nice to have a direct download button, when searching for books via smartphone.
All the tabs to download could be much faster done by a small icon next to the book.
Sometimes I need an info and do know which book it is in... such a button could bring lot of ease

Thx Jimmy

**Comment by rvolz** [comment]
You mean a download icon directly in the listing of the search results, right?

**Comment by Binog** [comment]
Yes, in just a few words ;-)
