### ISSUE TITLE
a fresh/clean git installation errors into.......

### ISSUE THREAD

**Issue by derdigge** [rvolz/BicBucStriim#151]
I often installed bbs in the past. if i clone from git this morning and do installation as usual it leads into following error.

http://s22.postimg.org/zcyvt0801/Unbenannt.png

**Comment by rvolz** [comment]
And you read this?

> Notice for Github users, v1.2.5+: In 1.2.5a #104 added the possibility to have multiple admin users. If > you have trouble to login as admin, either

>   1. use the sqlite3 cli to update user set role=1 where username='admin';
>   2. delete data/data.db

I'll add an update.php that does this, but it's not there right now.
