### ISSUE TITLE
FR: Calibre Bibliotheksverzeichnis als Netzlaufwerk 

### ISSUE THREAD

**Issue by xantippe** [rvolz/BicBucStriim#152]
Hallo,

ich arbeite mit Calibre auf einem PC aber speichere die Bücher auf einem NAS - leider kann ich BicBucStriim dort nicht installieren, so dass ich das Programm auf einem RaspPi aufgesetzt habe.

Schön wäre, wenn ich bei der Eingabe von "Calibre Bibliotheksverzeichnis" auch ein Netzlaufwerk wie "\\192.168.1.123\books\calibre\" angeben könnte - alternativ könte ich die metadata.db lokal auf dem RaspPi abspeichern, müsste aber irgendwo den Pfad angeben, um die Verlinkungen für Bilder und Downloads sicher zu stellen...

Machbar?

ansonsten ein tolles Programm!!

**Comment by rvolz** [comment]
Theoretisch schon machbar, nur würde so etwas die Anwendung ziemlich langsam machen. Die Calibre-Daten werden dauernd gebraucht. 

Warum nicht die Buchdaten per Synchronisation vom NAS auf den Rasperry Pi überspielen? (Mit Rsync zum Beispiel)

**Comment by xantippe** [comment]
etliche Comics an Bord => 45GB! :-(

**Comment by rvolz** [comment]
Wenn man eine alte USB-Platte dran hängt, geht auch das.
