### ISSUE TITLE
Searching and/or 

### ISSUE THREAD

**Issue by realShomi** [rvolz/BicBucStriim#155]
Hello, I realy like BicBucStriim. One thing I don't understand is, how to change the search-mode. I can only find exact matches. E.g. I search the book "War of the worlds" from H.G. Wells, I will only find it, when I enter "war of the" but not if I enter "war worlds" or "war wells". Can I somehow adjust this?

Thanks for any answers, Jan.

**Comment by rvolz** [comment]
The search is currently meant only for single expressions. It simply looks for occurences of the search input, regardless where they appear. Boolean operators are not supported.

**Comment by realShomi** [comment]
Ah, ok. Thank you for the answer. Then it wasn't me doing it wrong ;-). Is there any chance boolean operators will be supported in the near future? Thanks again for this helpful tool.
