### ISSUE TITLE
Adding audiobooks to OPDS catalogue

### ISSUE THREAD

**Issue by Alexv15310** [rvolz/BicBucStriim#156]
Hello. Is there any possibility to add the audiobooks to Calibre and have an access to them trought Bicbucsriim? Usually, audiobooks consist of several mp3 files. Thanks.

**Comment by rvolz** [comment]
I read that there is a plugin for MP3s, see http://www.mobileread.com/forums/showthread.php?t=143629. If you create a playlist (m3u) for the files of an audio book, you could add this playlist as one book to calibre. I haven't tried this out, though.

BicBucStriim is format agnostic, whatever Calibre delivers will be offered.
