### ISSUE TITLE
Fehler bei der Datenbankabfrage

### ISSUE THREAD

**Issue by owiegmann** [rvolz/BicBucStriim#157]
Hi,
ich habe meine ebooks in Calibre gespeichert und synchronisiere Calibre mit einem NAS (Synology) und nutze dein Programm, um die ebooks der ganzen Familie zur Verfügung zu stellen.
Ich bin auf folgendes Problem gestossen. Wenn ich nach einem Autor suche bekomme ich z.B. von einem Autor angezeigt, dass sieben Bücher existieren. Greife ich auf die Bücherliste zu werden aber nur 3 Bücher angezeigt. Anscheinend werden aber nur epub Formate angezeigt. Deshalb habe ich alle Bücher in epub konvertiert und kann per Calibre und dem Content Server auch alle Treffer sehen und darauf zugreifen. In deinem Programm werden aber nach wie vor nur die ersten drei Treffer angezeigt. Irgendeine Idee woran das liegen könnte?

**Comment by rvolz** [comment]
BicBucStriim sollte alle Formate anzeigen, die in Calibre eingetragen sind, nicht nur EPUB. Benutzer, die nicht alle Titel sehen, haben meist versehentlich einen Filter gesetzt (Sprache oder Schagwort in der Benutzer-Konfiguration). Um alle Titel angezeigt zu bekommen, einfach die Filter löschen. Dann sollte alle 7 Bücher auftauchen.
