### ISSUE TITLE
Missing Names in Author / Tag / Series page

### ISSUE THREAD

**Issue by mustela7** [rvolz/BicBucStriim#160]
Hi

Back to BicBucStriim after leaving for a while, I remark everything works, but in the Author/ Tag/ Series Pages, there are no names shown (The lists are there but no words), if I try to open one of the Links, it says "error loading page". 

I am using BicBucStriim v1.2.4 on a Qnap TS 470 pro, accessing via Safari and/or Firefox from a Mac.
No Errors testing BicBucStriim (all "green") except PHP Intl. "yellow"

**Comment by rvolz** [comment]
I guess this is a QNAP problem with SQLite see #146. Any chance to update the QNAP?

**Comment by mustela7** [comment]
It seems to be exactly the same as in post #146, so I'll go on there.
