### ISSUE TITLE
SMTP Mail senden funktioniert in 1.2.5 nicht mit 1.2.4 schon

### ISSUE THREAD

**Issue by kfr1** [rvolz/BicBucStriim#163]
Ich hab von der 1.2.4 Version auf die 1.2.5 version hier gewechselt wegen der Login abschaltung. Leider funktioniert der SMTP Mail versand seit dem nicht mehr. Hat sich da was gändert?
Ausprobiert habe ich sowohl ohne verschlüsselung als auch mit SSL und TLS server ist smtp.1und1.de mit den Ports 25, 465 und 587. 

Vielen Dank

quellen meiner verwendeten Versionen:
1.2.4 Version http://projekte.textmulch.de/bicbucstriim/downloads/BicBucStriim-1.2.4.zip
1.2.5 Version https://github.com/rvolz/BicBucStriim/archive/v1.2.5.zip

**Comment by rvolz** [comment]
Gerade getestet, SMTP funktioniert weiterhin: mit TLS und smtp.1und1 auf Port 25. Die SSL-Option bekommt anscheinend keinen Kontakt mehr (vielleicht wegen der Sicherheits-Umstellungen in letzter Zeit?).

**Comment by miktro** [comment]
I thionk BicBucStriim is agreat packaeg on Synology NAs
but
I am using version 1.2.4 andd cannot get SMTP mail to send MOBI books to my kindle account using my GMAIL SMTP account.
(I can use these accounts successfully in Calibre on my Windows PC and have set up a new Google app authentication password to use with BicBucStriim)

I have tried poerts 25,465,587 with encryption None,SSL,TLS respectively
and also SSL & TLS with port 25 but I get either an immediate error message (saying check the email address) or a long pause and then the same error message.

**Comment by rvolz** [comment]
Gmail uses different ports/protocols depending on the kind of SMTP service used. Did you already try the combinations listed here https://support.google.com/a/answer/176600?hl=en ?

**Comment by rvolz** [comment]
For example: the server smtp.gmail.com with port 465 and SSL, as described there, worked perfectly for me -- with the current Github version.
