### ISSUE TITLE
Fault: Getting around autentification

### ISSUE THREAD

**Issue by docisdn** [rvolz/BicBucStriim#165]
In the new version 2.5.1 there is an easy way of crawling around the authentification: just delete the login of the adress (***/bbc/login) and your in. 
I think this is not the way, multiple administratiors or users logins were made to. 
I re-installed v. 2.4. because i don't want anybody to get inside my libary without permision.

Thanks
docisdn

**Comment by rvolz** [comment]
Could you explain the scenario a bit more detailed?

**Comment by docisdn** [comment]
I so netter in German, so please dortige me for changing  the Language.

Nach Installation von version 2.5 habe ich die User und den Admin eingerichtet. Da meine bookmarks aber auf das Verzeichnis */bbs (und nicht */bbs/login) verweisen habe ich verwundert festgestellt, dass ich nicht auf die Login-Seite weitergeleitet werde sondern direkt ohne Login auf Startpage gelandet bin. Die Option "Logout" war nicht existent. 
Ich gehe davon aus, dass durch die Option des multiplen User und adminlogins der zwangsweise automatische Verweis von der bbs-Seite auf die Login-Seite irgendwie verlustig gegangen ist. Vermutlich eine Kleinigkeit.

Ansonsten tolles Programm (bis auf die Tatsache, dass ich zu der Gruppe der Qnap-Benutzer gehöre, bei denen die Autoren- und Reihensortierung ins Leere läuft. Habe den Thread gelesen dass es wohl ein Qnap-Problem ist)

Vielen Dank für die prompte Rückmeldung



Von meinem iPad gesendet

**Comment by rvolz** [comment]
Ich verstehe das Szenario leider immer noch nicht ganz. Probleme mit der Anmeldung traten bisher nur auf, wenn man zwischen dem Modus *mit Anmeldung* und *ohne Anmeldung* hin und her schaltete, *ohne den Webserver neu gestartet zu haben*. Auf ein solches Szenario würde auch die Tatsache hinweisen, dass die Logout-Taste nicht sichtbar ist.

War dem so? Wenn nicht bräuchte ich eine Beschreibung der Reihenfolge: welcher User hat wann was gemacht ...

Bezüglich QNAP: bisher konnte mir noch niemand die Frage beantworten, ob das an einer alten SW-Version von QNAP liegt, oder ob das der neueste Stand ist?

**Comment by docisdn** [comment]
Es kann natürlich am fehlenden Neustart des Webservers liegen, a ich tatsächlich den Modus ohne Anmeldung kurz aktiviert hatte. Tatsächlich bin ich (hoffentlich) der einzige User der Datenbank. 

Ich werde das nochmal versuchen indem ich die neue Version nochmal aufspiele. 

 

Hinsichlich QNAP muss es sich um ein Problem mit einer neueren SW Version handeln. Bei mir läuft Bicbucstriim schon immer auf dem QNAP, und anfangs konnte ich auf alle Features zugreifen. Erst im weiteren Verlauf "verschwand" der Zugriff auf Autoren. Ich kann aber nicht genau sagen wann, da ich nur selten auf diese Funktion zugreife. 

 

 

 

Von: Rainer Volz [mailto:notifications@github.com] 
Gesendet: Samstag, 20. Juni 2015 10:35
An: rvolz/BicBucStriim
Cc: docisdn
Betreff: Re: [BicBucStriim] Fault: Getting around autentification (#165)

 

Ich verstehe das Szenario leider immer noch nicht ganz. Probleme mit der Anmeldung traten bisher nur auf, wenn man zwischen dem Modus mit Anmeldung und ohne Anmeldung hin und her schaltete, ohne den Webserver neu gestartet zu haben. Auf ein solches Szenario würde auch die Tatsache hinweisen, dass die Logout-Taste nicht sichtbar ist.

War dem so? Wenn nicht bräuchte ich eine Beschreibung der Reihenfolge: welcher User hat wann was gemacht ...

Bezüglich QNAP: bisher konnte mir noch niemand die Frage beantworten, ob das an einer alten SW-Version von QNAP liegt, oder ob das der neueste Stand ist?

**Comment by docisdn** [comment]
Nachtrag: Es hat tatsächlich am fehlenden Neustart des Webservers gelegen. Wer lesen kann ist klar im Vorteil.

Vielen Dank für die rasche Rückmeldung. Wenn ich hinsichtlich des QNAP-Problems helfen kann: gerne

 

Von: Rainer Volz [mailto:notifications@github.com] 
Gesendet: Samstag, 20. Juni 2015 10:35
An: rvolz/BicBucStriim
Cc: docisdn
Betreff: Re: [BicBucStriim] Fault: Getting around autentification (#165)

 

Ich verstehe das Szenario leider immer noch nicht ganz. Probleme mit der Anmeldung traten bisher nur auf, wenn man zwischen dem Modus mit Anmeldung und ohne Anmeldung hin und her schaltete, ohne den Webserver neu gestartet zu haben. Auf ein solches Szenario würde auch die Tatsache hinweisen, dass die Logout-Taste nicht sichtbar ist.

War dem so? Wenn nicht bräuchte ich eine Beschreibung der Reihenfolge: welcher User hat wann was gemacht ...

Bezüglich QNAP: bisher konnte mir noch niemand die Frage beantworten, ob das an einer alten SW-Version von QNAP liegt, oder ob das der neueste Stand ist?
