### ISSUE TITLE
Can't install BicBucStriim

### ISSUE THREAD

**Issue by nicocans** [rvolz/BicBucStriim#166]
Hello,
I am trying to install BicBucStriim on an Ubuntu Server.
http://myserver/bbc/admin/configuration/ send me to a 404, but http://myserver/bbc/installcheck.php works (all is green). Do I have to configure a virtualhost too?

**Comment by rvolz** [comment]
If there is only one host, the default host should be sufficient.

**Comment by nicocans** [comment]
then it seems to be something wrong with .htaccess or rewrite rules.

**Comment by rvolz** [comment]
Ah, ok. Then try to enable URL Rewriting for Apache: `sudo a2enmod rewrite`

**Comment by rvolz** [comment]
and:

> Enable the usage of htaccess files (BucBucStriim incudes one):

    sudo nano /etc/apache2/sites-available/default
    In section <Directory /var/www> change 'AllowOverride NonetoAllowOverride All`.

(taken from here https://github.com/rvolz/BicBucStriim/wiki/WebServers)

**Comment by nicocans** [comment]
It works, thx!
