### ISSUE TITLE
Can't download books

### ISSUE THREAD

**Issue by coach0742** [rvolz/BicBucStriim#168]
Everything else is working, installcheck is all green, but I keep getting the same error.   
   http://pastebin.com/ZRwNrPgi

**Comment by rvolz** [comment]
This is probably a permission problem in your file system, like in #119. The HTTP server has no access to the book files. You should check their permissions.

**Comment by coach0742** [comment]
That's what I thought too, but I gave full RW access to everyone to make sure it wasn't a permissions issues. the directory is mounted from a fully accessible NFS share.

**Comment by rvolz** [comment]
BicBucStriim accesses the library via NFS? Then unfortunately the problem could be also timeout etc, like mentioned in here http://stackoverflow.com/questions/13930988/stat-failed-problems-on-nfs-sharing.

Googling for "php stat nfs share" shows different possibilities.

**Comment by coach0742** [comment]
This is definitely a problem somewhere on my end. Sorry for cluttering up the issues!
