### ISSUE TITLE
QNAP NAS v. 4.1.4 Autor ,Schlagwörter and Reihen are not accessable

### ISSUE THREAD

**Issue by Hulli** [rvolz/BicBucStriim#169]
Try to solve the problem with PHP update but without success.
The following Versions are installed on my NAS:

PHP Version. 5.25
Apache Version 2.2.29

Attached a Screenshop what happened if I go to the Autors page...

![bbs](https://cloud.githubusercontent.com/assets/13333386/8674509/a91158fc-2a3e-11e5-8105-8cfbf7b236e5.png)

**Comment by rvolz** [comment]
See #146
