### ISSUE TITLE
after upgrading to BicBucStriim  I can not access

### ISSUE THREAD

**Issue by moremoster** [rvolz/BicBucStriim#170]
After upgrading to BicBucStriim 1.2.5-4  I can not access not as a user and not as administrator. Suggestions?  Thanks

**Comment by rvolz** [comment]
That could be caused by

1. old cookies - just delete them in your browser
1. switching between login/no-login modes without restarting the web server

**Comment by moremoster** [comment]
Thank you for the quick reply, but in this case, the update has reset 
the previous configuration and are entered simply logging "admin" "admin

Thanks for all
Luigi
------ Messaggio originale ------
Da: "Rainer Volz" <notifications@github.com>
A: "rvolz/BicBucStriim" <BicBucStriim@noreply.github.com>
Cc: "moremoster" <moremoster@gmail.com>
Inviato: 17/07/2015 18:55:16
Oggetto: Re: [BicBucStriim] after upgrading to BicBucStriim  I can not 
access (#170)
