### ISSUE TITLE
large Calibre Database

### ISSUE THREAD

**Issue by locke987** [rvolz/BicBucStriim#171]
Hi,
I just installed BicBucStriim (lastVersion) on my Synology NAS.
I got it working with a small test calibre Database with only 20 books.
When I tried tu use my live calibre Database - which is about 30GB - the following issues occur:

no thumbnails are visible and downloading or send to email of a book is not working.
For most of the books I can't even see a the Content text preview of a book.
I tried installcheck.php - all green.
I checked the permissions - Looks good for me.
With the small DB the thumbnails are copied to the bbs/data Directory, when configuring to the large DB not a single thumbnail is copied here.
Is there a known issue/Limitation for large DB's?

Thanks Stefan

**Comment by rvolz** [comment]
No, there is no intentional limit and I haven't heard of size problems before. Some of the navigation features were especially introduced for people with larger libraries.

According to your description the app can't access the files below the library root, that happend before, because people forgot to apply the same permissions to the book folders and their contens. installcheck.php only checks if it can access the **metadata.db** file, not the book files below it. 

Could you please check the permissions? You could also check your Apache server logs, there should be error messages.

**Comment by locke987** [comment]
Hi,
Thanks for your fast response...today I tried a few things:

1.) First created a new Shared Dir on my NAS and copied my small test DB and Books inside, reconfigured bicbucstiim to the path, tested succesfully....all is working like a charm.
2.)Then I deleted the content of the Folder again and copied my 50MB Database and about 50GB of books inside the Folder, same permissions as in 1.), I also check the permissons of the books in the subdirs ...R/W permissions for the "admin", httpd, and several users, same as in 1.)
I can't see a difference....I reconfigured bicbucstriim, resterted httpd, same Problem as before.

here are the relevant log entries of "user-error_log" when the httpd Service is restarted:

[Sat Jul 25 20:08:42 2015] [notice] caught SIGTERM, shutting down
[Sat Jul 25 20:08:44 2015] [error] FastCGI: access for server (uid 1023, gid 1023) failed: read not allowed
[Sat Jul 25 20:08:44 2015] [notice] Digest: generating secret for digest authentication ...
[Sat Jul 25 20:08:44 2015] [notice] Digest: done
[Sat Jul 25 20:08:44 2015] [error] FastCGI: access for server (uid 1023, gid 1023) failed: read not allowed
[Sat Jul 25 20:08:44 2015] [notice] FastCGI: process manager initialized (pid 27331)
[Sat Jul 25 20:08:45 2015] [notice] Apache/2.2.29 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_ssl/2.2.29 OpenSSL/1.0.1p-fips configured -- resuming normal operations

For what should I look, any ideas?
Thanks Stefan

**Comment by rvolz** [comment]
This log shows only some FastCGI problems, but if your first try worked with this configuration, that is not problem. I was hoping for BicBucStriim errors in the log. Are there any messages from the app in this log? 

If they don't appear there you could enable the debug log in file index.php, change

```php
# Init app and routes
$app = new \Slim\Slim(array(
	'view' => new \Slim\Views\Twig(),
	'mode' => 'production',
	#'mode' => 'debug',
	#'mode' => 'development',
));
```

to 

```php
	#'mode' => 'production',
	'mode' => 'debug',
	#'mode' => 'development',
```

Then the app will log to files in the `data` directory.

**Comment by locke987** [comment]
Shame on me....my database was the Problem. After activation of the debug mode I could now see that the source files bicbucstriim tried to copy to the data direcory did not exist.  I manually corrected that for a few books and the thumnails and books appeared. So it was my fault, sorry bothering you,

Thanks Stefan

![Uploading bicbucstriim.jpg…]()
