### ISSUE TITLE
Problem with Calibre Directory

### ISSUE THREAD

**Issue by B1bl10** [rvolz/BicBucStriim#172]
Hello,
I try to install BicBucStriim but I have some problems with Calibre Directory.  I verified installcheck but all is clear. 
![bbs](https://cloud.githubusercontent.com/assets/11796852/8928757/cf9de278-3520-11e5-950f-5911fa400fdd.PNG)
The file metadata.db is writeable, the path of calibre on my web server is ok.

I've forgotten to say : I'm a noob ;-)

Thanks !

Thomas

**Comment by rvolz** [comment]
ok, and what is the problem exactly?

**Comment by B1bl10** [comment]
BBS don't find the calibre directory.

**Comment by rvolz** [comment]
Did you look at #138? Does this help?

**Comment by B1bl10** [comment]
Not really. I've read this issue but the problem still exist. I think I have a problem with the path on my web server. I search again...

**Comment by rvolz** [comment]
If the Calibre directory check fails, there should be a list of details shown below it, like in https://cloud.githubusercontent.com/assets/1092531/5717290/7ebb7a8a-9afe-11e4-830b-ac500693b9ac.png 

The results there often help to find the problem.
