### ISSUE TITLE
data/data.db should not be part of the Git repository

### ISSUE THREAD

**Issue by stucki** [rvolz/BicBucStriim#176]
I would like to run BicBucStriim using the Git directory, however that is not possible because data/data.db is changed while I use the software. My suggestion is to remove the whole data/ directory from the Git repository.

PS: The software is great but the name is insane! When you are looking for new suggestions, let me know and I'll add some... ;-)

**Comment by rvolz** [comment]
Fixed in https://github.com/rvolz/bbs-server/commit/a7982dd0db5d977105ccc885eda1de60acfe85ff
