### ISSUE TITLE
using more than one library

### ISSUE THREAD

**Issue by robsonsobral** [rvolz/BicBucStriim#181]
Hi!

Is it possible to run on more than one library? I have two of than in sibling folders.

Thank you for your app and for our attention.

**Comment by rvolz** [comment]
Yes, see https://github.com/rvolz/BicBucStriim/wiki/Multiple-instances

**Comment by robsonsobral** [comment]
Thanks! I installed from SynoCommunity. I guess I need to find another solution. I don't need another library because of BicBucStriim, but because I don't wanna mix my books and comics on Calibre.

Thank you for your attention.

---

Oh, one more thing. Shouldn't you remove the mentions of Stanza from the readme and of htaccess password from the wiki? They look like a little outdated. ;-)
