### ISSUE TITLE
autofocus search field

### ISSUE THREAD

**Issue by robsonsobral** [rvolz/BicBucStriim#183]
On click the search button, can the search field be focused?

Thank you.

**Comment by robsonsobral** [comment]
Why not on mobile devices?

**Comment by rvolz** [comment]
The last time I checked it wasn't supported by JQuery Mobile 1.4.5. I waited for an update, but that didn't come. Maybe they'll add it in 1.5.

**Comment by robsonsobral** [comment]
Really? Wow! Can't it be done on [vanilla JS](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus)?

Well... After reading some texts... It looks like the keyboard doesn't appear if the user don't tap the input.

Thanks, man!
