### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by JPreacher** [rvolz/BicBucStriim#186]
Hi,

So far I couldnt use bicbuclinks on the home page as -authors -tags and series: Error loading page.
I upgraded bicbuc to v.1.3.3 and now I can't login. The password is accepted but I stay on the same page and nothing happens, all links don't work.
I found a way to login and I use my nas address + port+ index.php. For now It is the only way to login and all my links trouble has gone away. Unfortunatly my bicbuc is now an old fashion hyperlinks page... Please anyone to help me ? Thx a lot
![bicbuc](https://cloud.githubusercontent.com/assets/10389807/10563326/8a6ea36c-7586-11e5-8111-cc404bd26cd7.jpg)

**Comment by rvolz** [comment]
See #185
