### ISSUE TITLE
remember me for an year on login form

### ISSUE THREAD

**Issue by robsonsobral** [rvolz/BicBucStriim#187]
Hi!

Is it possible to set a cookie for auto login on future visits?

Thanks!

**Comment by rvolz** [comment]
There is a session cookie already that does this. Due to recent changes its lifetime is currently determined by the web server, not by the application. With the upgrade to Slim 3.0 (next version) that should change again.

**Comment by robsonsobral** [comment]
Thanks!

I was thinking about a explicit checkbox for it.

**Comment by rvolz** [comment]
Fixed with the commit for #336
