### ISSUE TITLE
Installation issue error messages

### ISSUE THREAD

**Issue by schreima** [rvolz/BicBucStriim#189]
Dear Forum,

I installed  BicBucStriim on my Synology DS215j NAS, but still get error messages to complete configuration. Either I get an error loading page or Calibre database not existing message. Also the installationcheck tells me there is no directory.

I extended the open_basedir with: :/volume1/home/E-Books/Calibre_Datenbank

The same path I'm using for the configuration of BicBucStriim.

Read write access has User http for the BicBucStriim directory and the Calibre directory.

Did I used the correct user? Which user does BicBucStriim uses? Is the path correct or do I need to take care of something else?

Many thanks

**Comment by rvolz** [comment]
If you use the Synology web server then BicBucStriim uses the *http* user. The path seems to be ok. It may be that the ``/home`` directory has insufficient permissions, as in issue #138.

**Comment by schreima** [comment]
Thanks for the quick reply. I checked it and added the permissions for http another time even along the homes/User/E-Books/Calibre_Datenbank path including the database, but still facing the same issue. The directory is still not visible for BicBucStriim. At least it seems so.
Do you have any other idea?

**Comment by schreima** [comment]
Do I need to set any port forwarding?

**Comment by rvolz** [comment]
No, network has nothing to do with that problem. 

If the library check on the installcheck page fails, a list of test details appears below the form. What are the results in your case?

Most people store their library in a top level directry, such as ``/volume1/books``. Maybe you could try this to see if there is a difference?

**Comment by schreima** [comment]
Great, that fixed the issue. Don't know why, but now it works, thanks
