### ISSUE TITLE
Login required function not working / crashing the system (version 1.3.3)

### ISSUE THREAD

**Issue by apechman** [rvolz/BicBucStriim#190]
Good afternoon!

I've tried to disable the login required multiple times, restarting the server, restarting the full synology, etc but with no success.

After disabling and trying to login, i get the following error message on the browser:
//
Fatal error: Call to a member function getUserData() on a non-object in /volume1/web/bbs/index.php on line 2033
//

I have already re-installed the bbs from scratch, and still no luck.

Maybe a bug?
I'm running it on my Synology DS211j

thanks!
Alex

**Comment by rvolz** [comment]
That is probably the result of having old cookies on your NAS. If you delete them the problem should go away. 

Since the session handling changed in this version, the session cookies have a different structure now.

**Comment by apechman** [comment]
I'm not sure how to do so. I've tried to uninstall the web server, stop saving the php cache on synology settings but no much changes on the error.
Don't know how to erase the cookies of the Synology. Maybe u could explain how?
Thanks
Alex

**Comment by rvolz** [comment]
The directory used for storing session data on the DiskStation is normally `/var/services/tmp`. The file names look like `sess_<long hex number>`, eg `sess_8al18dk2oh5p9m80p46b8h2im6`.

**Comment by rvolz** [comment]
I added additional tests for `getUserData` in 1.3.4. I hope this fixxes your problem. If not, please lt me know.

**Comment by apechman** [comment]
I've updated it to 1.3.4 (fresh install), deleted the session cookies, configured everything, all running ok.
but when I switch off the login required, now I get a new error message:

Fatal error: Call to a member function isValid() on a non-object in /volume1/web/bbs/index.php on line 2035

I'm getting used w/ the login screen to be honest, but thought was important to leave the feedback.

By the way, I've tested the Tag feature you've made under the user menu, which did not work with me. Maybe because i have too many tags.. i have 11.000 books and they show 12.000 tags...
I've created 1 normal user and selected 1 tag to be removed, but once you login with that user name, the screen goes blank. nothing shows up at all.


Anyway, A-W-E-S-O-M-E job on this project
all the best
Alex

**Comment by rvolz** [comment]
Thanks for your testing. The easy mode will be restored with the next commit. The tag problem is already fixed.

Sorry for the mess. I guess this will be the last 1.x version, it's time to restructure the app.

**Comment by apechman** [comment]
Both issues were fixed!! :+1:   :+1: 

But I must say It did create a new one though... After disabling the login required the configuration icon stopped working.
When you click on the configuration, it takes you to the login page, and after entering the username/password of the admin, the screen goes blank, and there is no way to change any settings or go back to require logins.

Maybe this is something for version 2.x.x   :)

The tag filtering worked like a charm!

all the best
Alex

**Comment by rvolz** [comment]
Well spotted. I had to use two seperate browser instances to recreate this scenario. With only one it didn't happen. I'll add the fix to 1.3.6.
