### ISSUE TITLE
Autoren, Schlagwörter und Reihen leer

### ISSUE THREAD

**Issue by dosser** [rvolz/BicBucStriim#191]
Die im Titel angeführten Tabellen sind leer, bzw steht nur am ende der Zeile eine Ziffer.
Auch die Links sind identisch und sehr seltsam:

zB:
AUTOREN:
http://xxxx/boox/authors//0/

SCHLAGWÖRTER:
http://xxxx/boox/tags//0/

REIHEN:
http://xxxx/boox/series//0/

Hoffe es gibt dafür eine Lösung

Danke schon mal

**Comment by rvolz** [comment]
Ich nehme an das passiert auf einer QNAP-Maschine? Dann beruht das Poblem auf einer veralteten, fehlerhaften SQLite Bibliothek, die QNAP nicht austauscht, siehe #146, #160. In der aktuellen Version, siehe https://github.com/rvolz/BicBucStriim/releases, wurde das vorübergehend umgangen.

Sobald keine Fehlerberichte mehr kommen, wird diese Version auch *offiziell* gemacht.

**Comment by dosser** [comment]
Ja ist ein Qnap, sorry hab ich vergessen zu erwähnen.

Danke für den super schnellen tollen Support 👍

LG kurt


--- Original Nachricht ---
Von: Rainer Volz <notifications@github.com>
Datum: 23. November 2015 08:21:44
Betreff: Re: [BicBucStriim] Autoren, Schlagwörter und Reihen leer (#191)
An: rvolz/BicBucStriim <BicBucStriim@noreply.github.com>
CC: dosser <dosser66@gmail.com>
