### ISSUE TITLE
why no Syno package in repository with last BBS update available

### ISSUE THREAD

**Issue by tparvais** [rvolz/BicBucStriim#193]
today 2015-11-26, the last release is 1.3.5 on github.
On synocommunity, the last release is 1.2.5-4.

could you make sure to prepare the syno package for every release ?

Thank you

**Comment by rvolz** [comment]
The synocommunity packagers (the packages are not produced by me) follow the *official* releases published on the website, not the Github releases. I usually wait with making Github releases official until the *power users* following Github don't complain anymore. So most problems are solved before too many people are affected. Sometimes this procedure takes some time, sorry.
