### ISSUE TITLE
Page could not be found

### ISSUE THREAD

**Issue by martinfoerster** [rvolz/BicBucStriim#195]
Hello together, 
I own a synology NAS and did everything according to the manual but i constantly get the error message "page could not be found" or in german "Es tut uns Leid, die von Ihnen gesuchte Seite konnte nicht gefunden werden." when I try to access the path http://mynas/bbs/

Can anyone help out?

**Comment by rvolz** [comment]
Sounds like *WebStation* is not active, see [here](http://textmulch.de/blog/2012/bicbucstriim-auf-einem-nas-installieren)

**Comment by martinfoerster** [comment]
Disk Station is indeed active :/ @rvolz

**Comment by rvolz** [comment]
If the *WebStation* component and PHP (not the DiskStation) are really active, then this problem in the past was often caused by a failed unpacking of the ZIP archive. Try a different unpack method, and please check if the file `.htaccess` does really exist in the installation directory.

You could also try to call `http://.../bbs/installcheck.php` and check there for errors.

**Comment by martinfoerster** [comment]
@rvolz in installed the package trough the community package of synocommunity. So don`t really see where I have influence on how the package is unpacked in this process?

**Comment by rvolz** [comment]
Ok, I see. Normally the synocommunity package seems to work. But you could still verify if the hidden file `.htaccess` exists and has the same content as this one: https://github.com/rvolz/BicBucStriim/blob/master/.htaccess

For me it still looks like a probem with the web configuration of your NAS. If you install other synology packages into the web folder, eg DokuWiki, do they work?

**Comment by c-yco** [comment]
I have a similar issue on an ubuntu 14.04 machine with apache. The configuration test states everything ok
I used the zip from the download section, but had also the same issue with the 1.3.6 tag checked out from git directly. 
The .htaccess file has the same content as in your link. Is there any log I could check?
