### ISSUE TITLE
Additing a button to make the transition to the link

### ISSUE THREAD

**Issue by Alexv15310** [rvolz/BicBucStriim#196]
Hello. Could you add a button to make the transition to the link? 
It will be usefull for example:
1) On my media server, I placed the audiobooks. I would like to make the transition from BikBukStriёm to these audiobooks
2) Go througt the link to the site about book

Best regards, Alex

**Comment by rvolz** [comment]
Hello, I guess this relates to #156 ? Did you use a Calibre plugin for that? Which one?
