### ISSUE TITLE
PDF Books in 1.3.6

### ISSUE THREAD

**Issue by Steinbichler** [rvolz/BicBucStriim#197]
Hallo I have BicBucStriim running on a Synolgy. Everything is ok.

After a manual update to the newest version as discriped in your upgrade guide
BicBucStriim does not show my pdf books. ebooks are ok.
Goings back to synology package everything is ok again.

Can you pleas help with a tip?

Regards Roland

**Comment by rvolz** [comment]
That sounds similar to #194. Does the behaviour change if you delete the cookies as described there? 
I added code to detect and delete old cookies in 1.3.6, which could have caused similar behaviour.

**Comment by Steinbichler** [comment]
Hallo Rainer, yes same problem.
I did not see it when I was searching in the issue section. 
I changed the language of the user to Deutsch. Then the Problem comes up.
I tried now to switch it back to Keine Auswahl. No change.
After running C Cleaner (delete all cookies) the books are back.

So thanks for the tip, and thanks for fixing it in a future release.
