### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by brianbuquoi** [rvolz/BicBucStriim#198]
How can this service be configured for reverse proxy?

Some services will allow the user to put a URL base so that the service can be behind a reverse proxy.

**Comment by rvolz** [comment]
I have never tried that, but you could try to modify the `.htaccess` file that is included according to this example https://httpd.apache.org/docs/2.4/rewrite/proxy.html.

**Comment by rvolz** [comment]
See #209 for more.
