### ISSUE TITLE
ID template not working

### ISSUE THREAD

**Issue by handfest** [rvolz/BicBucStriim#200]
Currently I discovered a problem to use ID templates like described in the wiki.
If I insert the string [http://isbnsearch.org/isbn/%id%] into the URL field I will get a response "Bad parameter" and whatever text (like [ISBN] in the text field)

Using language "Deutsch" or English in Version V1.3.6
Any hints?

**Comment by rvolz** [comment]
Bad security tests where the cause for these issue. The fix will be published in 1.3.7

**Comment by handfest** [comment]
Great, thanks!
