### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by kmx236** [rvolz/BicBucStriim#202]
Hi!
I've added a new language (ru - Russian) file 'messages.yml'. How can I choose it to display?

**Comment by rvolz** [comment]
Thanks for the effort! The corresponding PHP file needs to be generated. If you have Ruby on your machine you can start the generator with the command `rake genl10n`. This will generate a new `langs.php` in `lib/BicBucStriim` and then the new translation will be used.

As an alternative you could create a pull request and then I'll include it.

**Comment by gersey** [comment]
Hi!
I would like to add a new language (hu - Hungarian). I did as rvolz wrote it, but I received an error:

> rake genl10n
> rake aborted!
> cannot load such file -- cucumber/rake/task
> /Users/zoltan/Downloads/bbs/Rakefile.rb:10:in `<top (required)>'
> (See full trace by running task with --trace)

What have I done wrong?

**Comment by rvolz** [comment]
Sorry, I assumed some Ruby knowledge. Alle dependencies are listed in the Gemfile and can be installed via Bundler. Then rake will work.

However, if you don't want to learn more Ruby: save the following lines into a file, eg `genl10n.rb`, and then run it, as in `ruby genl10n.rb`. This will generate the language files.

```ruby
require 'yaml'

msgs = YAML.load_file("messages.yml")
php = File.new('lib/BicBucStriim/langs.php', 'w')
php << "<?php\n"
php << "# Generated file. Please don\'t edit here,\n"
php << "# edit messages.yml instead. \n"
php << "#\n"
['de', 'en', 'fr', 'it', 'nl'].each do |lang|
  php << "$lang#{lang} = array(\n"
  msgs.each do |msg, locs|      
    php << "'#{msg}' => '#{locs[lang]}',\n" unless locs[lang].nil?
  end
  php << ");\n"
  php << "\n"
end
php << "?>\n"
php.close

```
