### ISSUE TITLE
Error Loading Page

### ISSUE THREAD

**Issue by night2day** [rvolz/BicBucStriim#203]
I have just installed the newest version of bbs on a synology 212+ with DSM 5.2.
I removed the old installation (version 1.1) before as suggested.
After inserting the old thumbs (as sugessted) and config the ebook folder 
bbs seems to work right. Books are shown after login with admin/admin.
But i am not able to change the admin password or create a new user. 
At saving the settings i get the "Error Loading Page" message. Also on trying loggoff/quit.
Access rights are read/write at the data folder, thumbnail folder and database file.

Do you have any further sugestions?

Greetings
n2d

**Comment by rvolz** [comment]
If there are only problems with adding/modifying the database then the database is probably still read-only. You could enable debug mode to get more information about the error, see this page for how to do that: https://github.com/rvolz/BicBucStriim/wiki/Debug-mode

**Comment by night2day** [comment]
Thank you for your fast response.

After activating the log and trying to insert a guest user it shows...

----------------------------------------------------------------------
DEBUG - 2016-03-26T12:04:31+01:00 - admin_add_user: array (
  'newuser_name' => 'Gast',
  'newuser_password' => 'gast',
)
ERROR - 2016-03-26T12:04:31+01:00 - admin_add_user: error for adding user array (
  'newuser_name' => 'Gast',
  'newuser_password' => 'gast',
)
ERROR - 2016-03-26T12:04:31+01:00 - admin_add_user: exception Undefined index: username
-------------------------------------------------------------------------

**Comment by rvolz** [comment]
Sorry, I didn't notice the version 1.1 you mentioned in the first message. The database structure of 1.1 is too old to be compatible. Just delete the database in the `data/data.db`. Then a new one should be cretad automatically and everything should work from then on.

**Comment by night2day** [comment]
Strange....your advice was successful, but i have renamed the old installation folder before i have installed the new version, so i can't imagine how the old db file comes into the new installation.
Gremlins...

Thank you for help and your great work on this project!
