### ISSUE TITLE
Issue GD version 2 not detected after upgrade to DSM 6 on Synology NAS

### ISSUE THREAD

**Issue by guill69f** [rvolz/BicBucStriim#204]
Hi, I was under DSM 5 for my Synology NAS, which automatically upgrade to DSM 6. Since that (I think), BBS is no longer working and the installcheck highlights that the cause is "GD version 2 (or higher) not installed".

Checking the PHP settings of my NAS I can see that "gd" is ticked, but maybe it's not the right version? Ican I check that and is it possible to point a way out of this situation?

thanks!

**Comment by rvolz** [comment]
The installcheck test on GD fails because the test expects to get a normal version number like _2.1.0_, but Synology now installed version _2.1.0-alpha_. I'll change that, but this is only a problem of the test, not the application.

I didn't notice any problems after the upgrade to DSM 6. Generating thumbnails with GD works over here.

**Comment by guill69f** [comment]
ok, thanks for the feedback. I will uninstall and reinstall BBS in the coming days then, and see if it changes anything.
Or else, do you have any other idea where my issue could come from? thanks

**Comment by rvolz** [comment]
What exactly is your issue?

**Comment by guill69f** [comment]
Hi, my issue is that I can no longer pass the login page.
When I type in the adress of the installcheck, all traffic lights are green except "Is GD version 2 (or higher)?", which is red.
Previously everything was working smoothly (all traffic lights green), i had some issues to start with the installation due to the fact that my ebooks / comics did not have proper permissions, but I SSH into my NAS and changed all that.
I don't recall playing with my NAS, the only reason I could think off (but you have discarded that one above) would be the upgrade from DSM 5 to DSM 6.
FYI, i also have COPS and My Readings installed, they are no longer working either. So probably it rules out any issue with BBS, the problem is probably on my NAS.
I have been googling to know how to solve the "Is GD version 2 (or higher)?" to find how to solve my issue, but did not find any answer that solved my case. Therefore I came here... Thanks

**Comment by rvolz** [comment]
Ok, then there are two possibilities you could check:

1. Check in the browser what kind of error is returned: To do that you would need something like the network analyzer in Firefox. With that you could see the error returned by the NAS when logging in to BicBucStriim, whether the origin of the error is the NAS or the app.
1. Turn on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) in BBS. There will be logs in the data folder, that could help to figure out the problem.

**Comment by guill69f** [comment]
Hi and sorry for late reply. For other reasons I am in the process of resetting and reinstalling my NAS, so i will see if I encounter the same issue once I'll reach this step in my process. thanks anyhow

**Comment by guill69f** [comment]
Hi, back after a few days .-), so i have a clean and reinstalled NAS, i have pushed again all my ebooks from the computer to the NAS, verified all permissions, modified open_dir; and still, getting the same error as before. I installed also COPS to double check things and it is failing as well.
Will try to folloz your instructions given above, struggling and bit with them though
