### ISSUE TITLE
problem to install bbs on NAS Synology DS214 with DSM6

### ISSUE THREAD

**Issue by lofirst** [rvolz/BicBucStriim#205]
Hello
I have been using bbs for years now but after upgrading my NAS to DSM 6, I had a login error I cannot handle. I decided to look if a new bbs version was there and found the 1.3.6. I tried to install it on my NAS, but I got this message and I am stacked with it :

_Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 table config already exists' in /volume1/web/bbs/lib/BicBucStriim/bicbucstriim.php:81 Stack trace: #0 /volume1/web/bbs/lib/BicBucStriim/bicbucstriim.php(81): PDO->exec('create table co...') #1 /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php(66): BicBucStriim->createDataDb() #2 /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php(22): OwnConfigMiddleware->check_config_db() #3 /volume1/web/bbs/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call() #4 /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php(1271): CachingMiddleware->call() #5 /volume1/web/bbs/index.php(205): Slim\Slim->run() #6 {main} thrown in /volume1/web/bbs/lib/BicBucStriim/bicbucstriim.php on line 81_

I do not know how to exit this issue. I deleted everything, re-installed everything but nothing changes.
Thanks in advance for your support.

**Comment by rvolz** [comment]
There is another issue regarding login problems after a DSM 6 upgrade, #204. Your error means that the app tries to create a new database, `data/data.db`, and fails at the first SQL statement. This could indicate a permission problem, that the web user has no permission to write in the `data` directory of your installation.

Coudl you check that?

**Comment by Oglarun** [comment]
Hi,
I had the same problem as discribed above and fixed it by granting write permission tothe http user for the data directory. Thanks for your hint! And thanks for that great tool!!
