### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by new-kirte** [rvolz/BicBucStriim#206]
The search in non-English languages (e.g. Russian) is case sensitive. Can it be changed to be case insensitive, please?

**Comment by rvolz** [comment]
It shouldn't be, but I see now that the function `strtolower` has its limits for cyrillic languages. I'll change that. 

Could you provide me with some test cases, e.g upper case strings and lower case equivalents?

**Comment by new-kirte** [comment]
Sure.
Search for асприн - https://diskstation.koval.id.au/bbs/search/?search=%D0%B0%D1%81%D0%BF%D1%80%D0%B8%D0%BD. No results
Search for Асприн - https://diskstation.koval.id.au/bbs/search/?search=%D0%90%D1%81%D0%BF%D1%80%D0%B8%D0%BD. Returns one author.

**Comment by rvolz** [comment]
I tested and discovered that this isn't a bug, but a restriction of current Sqlite distributions (the database that Calibre uses). By default it works with ASCII. To change that you would have to load an extension enabling Unicode. Unfortunately that extension isn't included in most installations.

I'll try to find a workaround.

**Comment by rvolz** [comment]
There is now a workaround that could help. Could you please test this version?
