### ISSUE TITLE
OPDS Search

### ISSUE THREAD

**Issue by new-kirte** [rvolz/BicBucStriim#207]
What is the URL for the OPDS search?
Thanks.

**Comment by rvolz** [comment]
Currently it is:  http:/..../bbs/opds/searchlist/0/?search=XXX

If you want to stay compatible in the future, then navigate to http://.../bbs/opds/opensearch.xml. The XML document contains the search URLs and parameters according to the OpenSearch spec.

**Comment by new-kirte** [comment]
Thanks. I'm configuring it in Freda (OPDS client).
http:/..../bbs/opds/searchlist/0/?search=XXX does not return anything (I had to change to http:/..../bbs/opds/searchlist/0/?search={0} to pass search parameters.)
http://.../bbs/opds/opensearch.xml - how do I pass search parameters to this URL?

**Comment by rvolz** [comment]
The opensearch.xml document is normally used by OPDS clients to find the search URL automatically. If Freda can't do that, you have to specify the ...bbs/opds/searchlist/... URL directly. 

If the search URL would change in a future release you would have to change it manually. Using the opensearch.xml would do it automatically.
