### ISSUE TITLE
Can't connect with version 1.36 

### ISSUE THREAD

**Issue by olamirault** [rvolz/BicBucStriim#208]
Hi,

When I install the 1.36 version of BBS, I have this message when I access to the homepage

Strict Standards: Declaration of BicBucStriim\SegmentFactory::newInstance() should be compatible with Aura\Session\SegmentFactory::newInstance(Aura\Session\Session $session, $name) in /home/olttremi/public_html/bbs2/lib/BicBucStriim/segment_factory.php on line 17

**Comment by rvolz** [comment]
Thx for reporting, I'll change the offending code. In the meantime you could, if you want to use the version, reduce PHP error reporting by following [these guidelines](http://stackoverflow.com/questions/9983286/disabling-strict-standards-in-php-5-4)
