### ISSUE TITLE
Create my very own htaccess

### ISSUE THREAD

**Issue by vowie** [rvolz/BicBucStriim#210]
Hello,

i try to access my library from the internet on my diskstation 211 and i´m facing a problem with the built-in htaccess file.
If i use the built in htaccess, my portforwarding isn´t working anymore. 
If i use BicBucStreiim without login, the portforwarding works well.

It seems that the problem is the redirection from bbs to bbs\login page. 

So i tried to create my own htaccess, but this isn´t working as well.

I´m using the latest version of BBS and DS Manager 6.0.
The installation check is without errors.
In the intern network it is working well.

What am i doing wrong? What can i do to solve the problem?

With other Applications portforwarding is working well....

Thanks in advance.

Martin

**Comment by rvolz** [comment]
Does _latest version of BBS_ mean 1.36? If so you could try the current Github version. There I just added fixes for problems with external access, see #209.

**Comment by vowie** [comment]
No, I´m using Version 1.4.0.a
BBS is installed in root folder.
i tried using a virtual host, but it isn´t working as well.
I´m not using https as mentioned in #209

**Comment by rvolz** [comment]
Ok, did you try to install it in a subdirectory, eg `.../bbs`? Problems with root folder installations come up from time to time.  
I tried to change that, but I guess they will only disappear with the refactoring in v2.0

**Comment by vowie** [comment]
yes, also tried bbs subdirectory, without success. 
Is there a older bbs version, where i can use a custom htaccess or is there another way to use a custom htaccess?

**Comment by rvolz** [comment]
I saw that the login middleware always used relative urls. Maybe that caused your problems. The commit changes that. You should verify that the configuration switch for _relative urls_ is switched off when trying this, otherwise you'll get the same behaviour as before.

**Comment by vowie** [comment]
its working! 
thank you soooo much!!

**Comment by rvolz** [comment]
Good to hear. I inadvertently changed the default setting for relative urls to OFF in the the first commit. Now they are ON again, by default. If your problems reappear, please remember to turn them OFF again.
