### ISSUE TITLE
Book/PDF Filesize indication

### ISSUE THREAD

**Issue by ramsnerm** [rvolz/BicBucStriim#212]
Hi! 
First of all thanks for this great tool. It helps a lot supplying books and PDF's. However while using it i have seen that it would be great to see the size of the book before downloading (some of my PDFs are 300MB). Therefore I would like to ask if it is possible to implement a function to show in the Download botton the Size. For example instead of PDF, PDF (220MB).

I have found some functions to utilize this but don't know how to implement it with the template system ([http://jeffreysambells.com/2012/10/25/human-readable-filesize-php]).

Can anybody help this regarding the topic? It is not must to have it in the official version, but i would like to implemented on my installation.

THANKS.

**Comment by rvolz** [comment]
The filesize is already part of the Calibre data used in the title details page, so you'll only need to transform it. This would require two changes:

1. Adding the transformation function to the Twig template library
2. Modifying the title details template

The first step would require something like this:

```
function human_filesize($bytes, $decimals = 2) {
    $size = array('B','kB','MB','GB','TB','PB','EB','ZB','YB');
    $factor = floor((strlen($bytes) - 1) / 3);
    return sprintf("%.{$decimals}f", $bytes / pow(1024, $factor)) . @$size[$factor];
}

$filter = new Twig_SimpleFilter('hfsize', function ($string) {
    return human_filesize($string);
});
$tenv = $app->view->getEnvironment();
$tenv->addFilter($filter);
```
Then adding the size to the template would be easy:
```
{{format.uncompressed_size|hfsize}}
```
The result would look like this
<img width="460" alt="bildschirmfoto 2016-05-31 um 20 27 03" src="https://cloud.githubusercontent.com/assets/1092531/15685904/31147b9e-276e-11e6-854c-f8151112e38b.png">

**Comment by ramsnerm** [comment]
Thank you very much for your quick reply. I applied the modifications today it works perfectly.

**Comment by pimpike** [comment]
Hi,
Could describe which files should be modified, please?
Thanks.

**Comment by rvolz** [comment]
The code could be placed in index.php, for example. The formatting must be inserted into templates/title_detail.html
