### ISSUE TITLE
OPDS Feed - Creation Date & Publisher

### ISSUE THREAD

**Issue by Lugasch** [rvolz/BicBucStriim#213]
Hi,

Is it possible to add publisher and publishing date r extra calibre columns to opds feed.
Some apps like bookari/ mantano use these terms.

eg.

```
<dcterms:issued>2014-09-16</dcterms:issued>
<published>2016-05-17T08:08:08Z</published> 
<dcterms:publisher>KGF-Meerbusch</dcterms:publisher>
<dcterms:extent>356 Seiten</dcterms:extent>
<dcterms:extent>0.96 MB</dcterms:extent>
<dcterms:extent>96430 Wörter</dcterms:extent>
```

Regards Lugasch

**Comment by rvolz** [comment]
_published_ is reserved for meta data about the catalog entry itself:

> OPDS Catalog Entries MAY use "atom:published" to indicate when the OPDS Catalog Entry was first accessible.

The other fields could be added together with #75.
