### ISSUE TITLE
send to kindle broken

### ISSUE THREAD

**Issue by handfest** [rvolz/BicBucStriim#214]
I've some problems to send books to kindle. The email account is working, but amazon sends an error email:
----------------------Schnipp---------------------------------
Das folgende Dokument, gesendet am 18:00 Uhr, am Samstag, 18. Juni 2016 MESZ, konnte nicht an den angegebenen Kindle geliefert werden:
xxxxxxxxx.mobi

Der Kindle Persönliche Dokumente Service kann folgende Arten von Dokumenten konvertieren und liefern:
...
Mobi-Buch
...
------------------------Schnapp-----------------

If I send the same book directly from calibre it works as asumed.
File sizes of the exportes mobi files by BBS and calibre are different.
Any hints?

Thanks Handfest

**Comment by rvolz** [comment]
I just verified the send-to-kindle and it worked from here. The difference in file sizes could be a problem. The algorithm used tries to find the most suitable kindle format, AZW3, AZW or MOBI, in this sequence. Could it be that you have multiple formats for this title in the library?

Anyway, you could turn on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) to see which file is really sent in the log.

**Comment by handfest** [comment]
>Could it be that you have multiple formats for this title in the library?

Yes, azw3 and mobi. 
I've tried another title with only mobi book. This seems to work (no error message from amazon yet), if I try to send one with more than one format _or with only azw3_  format it will fail. 

So it seems that You are on the right way  and the algorithm will do something wrong. Obviously (regarding the amazon error message) the transmitted file wil be named .mobi (also if the book ist in database only wth *azw3)

>Anyway, you could turn on debug mode to see which file is really sent in the log.

I will definitely check, but unfortunately I have currently no access to my equipement 
If You want to leave this issue open I will be back ;-)

**Comment by rvolz** [comment]
If there is a AZW3/AZW format it has priority and will be sent, instead of MOBI. The reason is probably that AZW3 files contain the more modern KF8 format for Kindle books.

**Comment by handfest** [comment]
>The reason is probably that AZW3 files contain the more modern KF8 format for Kindle books.

Exactly this might be the reason. When I use Calibre directly to send it will transmit the .mobi files instead the .azw*
BicBucStriim transmits the .azw3 if existing (checked and worked as presumed)

So this brings me to the next question: What about a parameter for choosing the transmitted format if more than one is in the DB? :-)

Currently I commented out the AZW3 in /bbs/lib/BicBucStriim/Calibre.php

Zeile 1065
/**            "SELECT * FROM data WHERE book=:id AND (format='AZW' OR format='AZW3' OR format='MOBI' OR format='HTML' OR format='PDF')",
*/

            "SELECT * FROM data WHERE book=:id AND (format='AZW' OR format='MOBI' OR format='HTML' OR format='PDF')",

**Comment by rvolz** [comment]
It's probably the easiest to let people choose what format to download or mail.

**Comment by jfisbein** [comment]
When I tried to send a PDF to my kindle I got an error from amazon the format. I think the problem is here:
https://github.com/rvolz/BicBucStriim/blob/master/index.php#L1359

the file sent is being renamed to have a ".mobi" extension which is wrong. 
If I send the pdf directly through my email it works flawlessly.

thanks!

**Comment by rvolz** [comment]
Thx for finding this. I'm changing the "sending" process to include all formats.
