### ISSUE TITLE
Fatal Error on Synology DS-207+

### ISSUE THREAD

**Issue by thinkvolt** [rvolz/BicBucStriim#216]
Hello, I tried to install BicBucStiim on my Synology DS-207+, running DSM 3.1. COPS is working, but with bbs, the following message appears at first start:

> Fatal error: Can't inherit abstract function Aura\Auth\Adapter\AdapterInterface::login() (previously declared abstract in Aura\Auth\Adapter\AbstractAdapter) in /volume1/web/bbs/vendor/aura/auth/src/Adapter/AbstractAdapter.php on line 25

**Comment by rvolz** [comment]
Can you run the script at http://.../bbs/installcheck.php? What doe it say? 
My guess is, that DSM 3.1 is too old.

**Comment by thinkvolt** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20258327/16614965/f1d1b6be-4373-11e6-810a-4a8eaa431b39.JPG)

I tested several Versions, the only one working is BicBucStriim 1.1.0

**Comment by rvolz** [comment]
Yes, that was the last version for PHP 5.2. For everything else you would have to upgrade DSM.
