### ISSUE TITLE
User config : config with empty choice

### ISSUE THREAD

**Issue by Draky50110** [rvolz/BicBucStriim#218]
Hello.

Have tried to install last ZIP from GitHub.

In user config, I have a choice of configuratin with no text and explanation.

In the following image, it is the choice with the red mark : https://lut.im/8Fi6ti5NRW/1iyz0uB1rbThjENE.png

Any idea of the problem ?

Thanks :)

**Comment by rvolz** [comment]
The list box lists the tags from the Calibre database. If there are no books or no books with tags iti is empty.

**Comment by Draky50110** [comment]
I'm a bit confused.

First dropbox = language to show
2nd is a dropdown list with tags
3rd box (red marker) is empty.

I still don't understand the 3rd dropbox, but I understand the 2nd one to exclude books with tags.

You can see it onto my test install draky.net/bbs/ (admin/admin)

**Comment by rvolz** [comment]
Sorry, the confusion was mine. The third dropbox is about user roles. 

There are two problems causing the emptiness:
1. the french translation is incomplete for this section
1. the mechanism that should use english as a default when there is no translation seems to have failed

Thanks for the heads up. I'll fix that

**Comment by Draky50110** [comment]
Ok, thanks :)
