### ISSUE TITLE
Port forwarding issue

### ISSUE THREAD

**Issue by csgnyc** [rvolz/BicBucStriim#224]
Not sure if this is an issue or whether there's a workaround.

I have set up and  can use Bicbucstriim, installed on a synology NAS, within my home network.  The problem is accessing it outside the home network.

I have set up port forwarding so that IPaddress:9091 forwards successfully to the synology DSM (192.168.1.8).  The problem is that if I then choose to open the BIcbucstriim app, it tries to open IPaddress/bbs without success (404 Not Found) and if I try to open IPaddress:9091/bbs I get an error message "Sorry, the page you are looking for is not found."

I'm comfortable with port forwarding, but I can't figure out why I can't access BIcbucstriim outside the home network.  Is this an issue or is there a workaround?

**Comment by rvolz** [comment]
Does this help? https://github.com/rvolz/BicBucStriim/wiki/Forwarding

**Comment by csgnyc** [comment]
Thanks but I had seen that page.  If I'm reading it correctly, that helps when you're in bicbucstriim and the directories are messed up.  I can't get into BicBucStriim in the first place (from outside the home network).
