### ISSUE TITLE
 open_basedir restriction in effect on Synology DSM 6

### ISSUE THREAD

**Issue by Flyingdishes** [rvolz/BicBucStriim#226]
Hi,
I am using a Synology (DS213+) NAS and just installed BBS. I am not a specialist at all.

Using the bbs//installcheck.php it shows that /Volume1/calibre is not accessible (all books and Calibre metadata.db are however there) and the " open_basedir restriction is in effect" (I guess the second triggers the first one). 

How can I troubleshoot this ?

Thanks for your help, the application looks promising.

Flying.

**Comment by rvolz** [comment]
You did add your Calibre directory to the open_basedir paths, as mentioned [here](http://projekte.textmulch.de/bicbucstriim/#install), right? 

Furthermore: ff the library check fails, it shows a list of things it did and where it failed.

**Comment by Flyingdishes** [comment]
Thanks Rainer for your quick feedback.

I am a basic windows user, so I will need to figure out how to access to usr directory from a windows client and change the open_basedir in what I undertood is a .ini file. I’ll keep you posted once I have figured out.

Denis

**Comment by rvolz** [comment]
No, the open_basedir setting is available via the Control Panel, look for Web Services/PHP Settings

**Comment by Flyingdishes** [comment]
You are perfectly right ! it works perfectly now…

I need to figure our now why I cannot access it via the Internet

Denis
