### ISSUE TITLE
bicbucstriim doesn't find the path to the Calibre directory

### ISSUE THREAD

**Issue by pikola24** [rvolz/BicBucStriim#228]
Hi,
I've been trying to make BicBucStriim work for quite a while. Unfortunately something doesn't work. When I check the path to the Calibre Library Directory. BiBucStriim doesn't find the path.

I was asking myself if the problem is the following: the root directory isn't called Volume1, but Volumes. I have tried with both names, but nothing works. I assume that the Volume cannot be renamed.

Any suggestion how could I make it work?
Thanks

<img width="1212" alt="screenshot_10" src="https://cloud.githubusercontent.com/assets/10521450/19120762/52a6511e-8b24-11e6-9b9d-cba4face1d87.png">

**Comment by rvolz** [comment]
The most common causes are:

1. The library path is not in the _open_basedir_ list
1. The libray path is not readable for the webserver user, the whole path must readable for that user
