### ISSUE TITLE
Folder pass the installation check but fails at configuration

### ISSUE THREAD

**Issue by tkamth** [rvolz/BicBucStriim#229]
Dear all,
I have the following scenario:
The folder works when checked for installation but does not pass the configuration stage, I am using a Synology server and checked all the proper permissions, any insight would be appreciated.

![screenshot from 2016-10-16 11_36_45](https://cloud.githubusercontent.com/assets/3426946/19416607/0cee0ddc-9395-11e6-9314-747d462925d8.png)
![screenshot from 2016-10-16 11_36_23](https://cloud.githubusercontent.com/assets/3426946/19416606/0ceac352-9395-11e6-92c9-64a6b87bae12.png)

**Comment by rvolz** [comment]
Synology servers normally have the open_basedir restriction applied. This doesn't seem the case for your system. Did you change the configuration? 

The installation check routine does more checks on the calibre directory than in the admin screen. It's puzzling that the installation check can access the calibre DB, but not the admin routine. Do you have an error log that shows what is going on?

**Comment by tkamth** [comment]
Thanks for the suggestion, please find below the error log.  I am logging in with admin.

INFO - 2016-10-18T20:38:32+02:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2016-10-18T20:38:32+02:00 - caching_middleware: caching disabled for /admin/configuration/
INFO - 2016-10-18T20:38:32+02:00 - multi user mode: login required
DEBUG - 2016-10-18T20:38:32+02:00 - own_config_middleware: config loaded
WARN - 2016-10-18T20:38:32+02:00 - check_config: Calibre library path not configured.
DEBUG - 2016-10-18T20:38:32+02:00 - login resource: /admin/configuration/
DEBUG - 2016-10-18T20:38:32+02:00 - after resume: VALID
INFO - 2016-10-18T20:38:44+02:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2016-10-18T20:38:44+02:00 - caching_middleware: caching disabled for /admin/configuration/
INFO - 2016-10-18T20:38:44+02:00 - multi user mode: login required
DEBUG - 2016-10-18T20:38:44+02:00 - own_config_middleware: config loaded
WARN - 2016-10-18T20:38:44+02:00 - check_config: Calibre library path not configured.
DEBUG - 2016-10-18T20:38:44+02:00 - login resource: /admin/configuration/
DEBUG - 2016-10-18T20:38:44+02:00 - after resume: VALID
DEBUG - 2016-10-18T20:38:44+02:00 - admin_change: started
DEBUG - 2016-10-18T20:38:44+02:00 - admin_change: array (
  'calibre_dir' => '/volume1/calibre',
  'must_login' => '1',
  'kindle' => '0',
  'kindle_from_email' => '',
  'mailer' => '2',
  'title_time_sort' => 'timestamp',
  'thumb_gen_clipped' => '1',
  'page_size' => '30',
  'display_app_name' => 'BicBucStriim',
  'metadata_update' => '0',
)
ERROR - 2016-10-18T20:38:44+02:00 - admin_change: ended with error array (
  0 => 1,
)

**Comment by rvolz** [comment]
Ok, this doesn't tell us more. It still claims the Calibre library doesn't exist. 

There are slight differences between the check in installcheck and the admin section. A way to tell which function is right would be to change some code:

lib/BicBucStriim/calibre.php, around line 40

```php
static function checkForCalibre($path)
    {
        $rp = realpath($path);
        $rpm = $rp . '/metadata.db';
        return is_readable($rpm);
    }
```
change line 40 

```php
        return true;
```

If installcheck.php was right this change would cause the app to open the Calibre library. Otherwise this would indicate taht there is a problem with the file permissions.

**Comment by tkamth** [comment]
Hi rvolz,
the check bypass led to the next step but now it finally led to the solution and it is working, there was, as you indicated, file permissions issue, I had to include also write permission for the folder.  

Thanks

**Comment by rvolz** [comment]
Good to hear that it works now. I'll try and add tests to installcheck.php to avoid these problems in the future.
