### ISSUE TITLE
How to: Update BicBucStriim

### ISSUE THREAD

**Issue by TheBuzzDee** [rvolz/BicBucStriim#23]
Hi,

I am looking forward to the next version (0.9.4 ?) of BicBucStriim.
Is there a HowTo or just a brief explanation how to update from a previous version?
e.g. which files changed, and have to be replaced or replace all files or, run update.php or....whatever.
I think this might be helpful...

Greetings,
BuzzDee

**Comment by MabuClou** [comment]
I am still missing a proper description on this point.

On the webpage i just found a short description for upgrading. But that just tells how to copy the thumbnails. How about the old datas like registered users and other configuration datas?

I have copied the file "data.db" from the data directory as well. Then it seemed to work properly. Was that ok? 

Please add this to your description.

Greetings,
Clouseau
