### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by Binog** [rvolz/BicBucStriim#230]
Hey if I want to login - with any account - i get a "error loading page" message, which disappears after 3 seconds.
The config.php does show no errors.
What can I do?

**Comment by rvolz** [comment]
Did you try to call the installation check routine? `http://.../bbs/installcheck.php`

**Comment by Binog** [comment]
Yes I did, and there where no errors. even the db was correctly found.

An idea?
thx

**Comment by rvolz** [comment]
ok, then the way to go forward is to switch on debug mode and look for errors in the log: https://github.com/rvolz/BicBucStriim/wiki/Debug-mode

**Comment by Binog** [comment]
Hey, did so, this is the result:

Slim Application Error
The application could not run because of the following error:

Details

Type: Aura\Auth\Exception\PasswordIncorrect
File: /volume2/web/bbs/vendor/aura/auth/src/Adapter/PdoAdapter.php
Line: 285
Trace

#0 /volume2/web/bbs/vendor/aura/auth/src/Adapter/PdoAdapter.php(150): Aura\Auth\Adapter\PdoAdapter->verify(Array, Array)
#1 /volume2/web/bbs/vendor/aura/auth/src/Service/LoginService.php(75): Aura\Auth\Adapter\PdoAdapter->login(Array)
#2 /volume2/web/bbs/index.php(243): Aura\Auth\Service\LoginService->login(Object(Aura\Auth\Auth), Array)
#3 [internal function]: perform_login()
#4 /volume2/web/bbs/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('perform_login', Array)
#5 /volume2/web/bbs/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()
#6 /volume2/web/bbs/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /volume2/web/bbs/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /volume2/web/bbs/lib/BicBucStriim/calibre_config_middleware.php(54): Slim\Middleware\MethodOverride->call()
#9 /volume2/web/bbs/lib/BicBucStriim/login_middleware.php(37): CalibreConfigMiddleware->call()
#10 /volume2/web/bbs/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware->call()
#11 /volume2/web/bbs/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#12 /volume2/web/bbs/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#13 /volume2/web/bbs/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#14 /volume2/web/bbs/index.php(205): Slim\Slim->run()
#15 {main}

----------------------------------
tried all my accounts, says all passwords are wrong. 

above that statement it says in the logs:

INFO - 2016-10-18T09:58:10+02:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2016-10-18T09:58:10+02:00 - caching_middleware: caching disabled for /login/index.php
INFO - 2016-10-18T09:58:10+02:00 - multi user mode: login required
DEBUG - 2016-10-18T09:58:10+02:00 - own_config_middleware: config loaded
WARN - 2016-10-18T09:58:10+02:00 - check_config: Calibre library path not configured.
INFO - 2016-10-18T09:58:10+02:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2016-10-18T09:58:10+02:00 - caching_middleware: caching disabled for /admin/configuration/
INFO - 2016-10-18T09:58:10+02:00 - multi user mode: login required
DEBUG - 2016-10-18T09:58:10+02:00 - own_config_middleware: config loaded
WARN - 2016-10-18T09:58:10+02:00 - check_config: Calibre library path not configured.
DEBUG - 2016-10-18T09:58:10+02:00 - login resource: /admin/configuration/
DEBUG - 2016-10-18T09:58:10+02:00 - after resume: ANON
DEBUG - 2016-10-18T09:58:10+02:00 - login auth: NULL
DEBUG - 2016-10-18T09:58:10+02:00 - login: redirecting to login
INFO - 2016-10-18T09:58:10+02:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2016-10-18T09:58:10+02:00 - caching_middleware: caching disabled for /login/
INFO - 2016-10-18T09:58:10+02:00 - multi user mode: login required
DEBUG - 2016-10-18T09:58:10+02:00 - own_config_middleware: config loaded
DEBUG - 2016-10-18T09:58:10+02:00 - login resource: /login/
DEBUG - 2016-10-18T09:58:10+02:00 - after resume: ANON
DEBUG - 2016-10-18T09:58:10+02:00 - login auth: NULL
DEBUG - 2016-10-18T09:58:10+02:00 - login: login page authorized
INFO - 2016-10-18T09:58:16+02:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2016-10-18T09:58:16+02:00 - caching_middleware: caching disabled for /login/
INFO - 2016-10-18T09:58:16+02:00 - multi user mode: login required
DEBUG - 2016-10-18T09:58:16+02:00 - own_config_middleware: config loaded
DEBUG - 2016-10-18T09:58:16+02:00 - login resource: /login/
DEBUG - 2016-10-18T09:58:16+02:00 - after resume: ANON
DEBUG - 2016-10-18T09:58:16+02:00 - login auth: NULL
DEBUG - 2016-10-18T09:58:16+02:00 - login: login page authorized
DEBUG - 2016-10-18T09:58:16+02:00 - login: array (


I checked with install check, the calibre library is accessible in place. where to config the path, again?

Thx
Jimmy

**Comment by rvolz** [comment]
Did you upgrade from a previous version, because the password is not recognized? Just to check if there is a technical problem, you could move your old data/data.db to a different location. Then you could login with the default credentials admin/admin.

If this works, then the problem is the old DB.

**Comment by Binog** [comment]
Yes, I did upgrade from an old version. So I did as You said, and indeed I could login again.

But, looks like I’m having permission problems. I can change the admin password, and it says nothing wrong, but if I logout and login again, it is still the default pass.

So maybe the old db isn’t bad?

**Comment by rvolz** [comment]
Yes, it seems that there are still permission problems with the directory or the files, like in #229. 

In general, the _user_ of the http server, normally _http_, needs read/write access to the directory and the files. Currently it can only read.
