### ISSUE TITLE
[enhancement] schlagwort

### ISSUE THREAD

**Issue by gglanzer** [rvolz/BicBucStriim#231]
zuerst ein wirklich ehrlich gemeintes LOB an den Programmierer.

(ich hoffe das ich hier auch in deutsch schreiben darf)

ich hätte da eine Frage. Wäre es denkbar und mit einfachen Mitteln realisierbar bei der Benutzerverwaltung den Punkt [Schlagwort - Optional, schließt Bücher mit diesem Schlagwort von der Anzeige aus] dahingehend zu erweitern, dass hier eine flexiblere Einschränkung möglich ist?

zB: die vorhandenen schlagworte mit Kästchen zum Ankreuzen anzeigen und in den Benutzer übernehmen. Einfacher wäre es dann nur die Bücher anzuzeigen welche der Benutzer sehen darf

**Comment by rvolz** [comment]
Diese Eigenschaft war bisher eher für Familien gedacht, wo es darum ging Kindern bestimmte Titel vorzuenthalten. Dafür wurden Inkonsistenzen bei der Anzeige in Kauf genommen, zB Autoren, die scheinbar keine Bücher haben.

Dies würde sich bei der vorgeschlagenen, positiven Filterung noch verstärken. Dahe rbin ich bisher skeptisch.

**Comment by dazze1812** [comment]
Ich finde den Vorschlag auch gut. Bisher habe ich meine Installation so gepatcht, dass der Filter als Positiv-Filter wirkt, d.h. es werden nur die Bücher mit eingestellten Schlagwort angezeigt. Damit haben meine Kinder nur Zugriff auf die Bücher mit dem Schlagwort "Kinderbuch".
Das Problem mit den Inkonsistenzen sehe ich auch, aber damit kann ich (noch) leben. Aber ich würde mich freuen wenn es da eine "offizielle" Lösung geben würde.

Ansonsten vielen Dank für das tolle Tool.

**Comment by rvolz** [comment]
dann werde ich das mal testweise einbauen.

**Comment by gglanzer** [comment]
Das freut mich zu lesen. Das es Autoren gibt welche demnach KEINE "Kinderbücher" geschrieben haben und daher "kein Buch" angezeigt wird find ich jetzt nicht schlimm. Eine positive Filterung hätte für die Kinder (um bei diesem Beispiel zu bleiben) den Vorteil das sie - entsprechend angehakt - Zugriff auf die Schlagwörter "Kinderbuch" und "Technik" hätten.

**Comment by gglanzer** [comment]
Wird es hier noch eine "offizielle" Lösung geben?

**Comment by rvolz** [comment]
In der 2.0-Fassung, die derzeit im Branch v2dev liegt. Das wird aber leider noch etwas dauern.

**Comment by gglanzer** [comment]
Gibt es Neuigkeiten zu der 2.0er Fassung oder hast du das Projekt eingestellt?
(wäre ja schade drum)

**Comment by rvolz** [comment]
Eingestellt ist es nicht, nur dauert es mal wieder länger als gedacht. Ich komme jetzt erst wieder dazu.

**Comment by ralfberger** [comment]
Hallo,
da der Vorschlag mit der "flexiblere Einschränkung" von Schlagwort noch nicht implementiert wurde 
finde ich die Lösung von gglanzer sehr interessat. 
@gglanzer 
> Bisher habe ich meine Installation so gepatcht, dass der Filter als Positiv-Filter wirkt,...

Wie hast du das gemacht?

Danke und Grüße

**Comment by gglanzer** [comment]
Der Vorschlag kam leider nicht von mir - würde mich aber auch interessieren. Eventuell gibt es ja schon eine v2 zum testen?

**Comment by ralfberger** [comment]
Stimmt, der Vorschlag kam von @dazze1812 , Entschuldigung.
v2 zum testen ist mir nicht bekannt. Aktuell ist doch V1.5?
