### ISSUE TITLE
trouble configuration

### ISSUE THREAD

**Issue by marcpalmen** [rvolz/BicBucStriim#232]
Hello

hope you can help. Installed BBS, tried to do the configuration => The configured Calibre directory cannot be used. Is it really a Calibre directory? Is it readable? Does it exist?
Did the installation check => everything ok except of course the warning on open_basedir.
Restarted twice still the same problem. 
Any would be welcome

Cheers

Marc

**Comment by rvolz** [comment]
It's probably an access rights issue. You could look at #229  for further hints.
