### ISSUE TITLE
Fehler bei der Suche nach Autor / Schlagwort

### ISSUE THREAD

**Issue by lobo0108** [rvolz/BicBucStriim#233]
ich verwende calibre und bbs mit einem Buchbestand von ca. 12.000 Büchern. Das ganze läuft auf einer QNAP ts-253 pro und ich greife mit mehreren Geräten darauf zu. Die Suche nach Strings klappt problemlos und einwandfrei. Die Suche nach Autor oder Schlagwort gelingt jedoch nicht. Hier wird die Suche zwar durchgeführt, man landet auf einer Trefferliste. Klickt man jedoch auf einen dieser Sätze (auf das Icon >) folgt eine Fehlermeldung 'error loading page'.

Klickt man jedoch auf einen der > erscheint, obige Fehlermeldung. Was kann das sein?

Gruß 
Markus

**Comment by rvolz** [comment]
Wenn der  Debug Modus einschgeschaltet ist, https://github.com/rvolz/BicBucStriim/wiki/Debug-mode, kann man im Log nachverfolgen was passiert.

**Comment by zweiundvierzig** [comment]
Hallo Markus,
hast du evebtuell bei deinem User in den Einstelungen eine Sprache festgelegt? Dann bekommst Du auch nur Bücher dieser Sprache angezeigt!

VG,
Tobias
