### ISSUE TITLE
bbs um Kindle-Funktionen 'aufgebohrt'

### ISSUE THREAD

**Issue by lobo0108** [rvolz/BicBucStriim#234]
Hallo Forum,
ich verwende bestimmt seit rund 5 Jahren Calibre und seit 2 Jahren BBS auf einer QNAP TS-253 Pro. Das klappt ganz gut - ich wünsche mir jedoch eine kleine Funktionalität: Die Speicherung der zuletzt gelesenen Seite; ähnlich wie das über den Kindle erreicht wird - das ist doch eine tolle Funktionalität: Man liest das Buch auf mehreren Geräten gleichzeitig (Morgens mit der App auf dem Handy, auf dem Nachhauseweg über die App auf dem iPad-Mini und abends auf dem Sofa/Bett auf dem Android-Tablet.

Weiß jemand hierfür eine Lösung? Gibt es ggf. ein kostenpflichtiges Addon, welches man in Calibre und BBS integrieren kann oder gibt es ggf. eine App welche die zuletzt gelesene Seite mit einer zentralen Datenbank (z.B. calibre) synchronisiert? Der Vorteil von Kindle liegt in der proprietären App von Amazon begründet. Das ist in dieser App fest verdrahtet! Die zuletzt gelesene Position wird 'einfach' mit der zentrale Datenbank synchronisiert. Das Öffnen erfolgt systemkonform - jedoch wird zu Beginn zuerst mit der Datenbank synchronisiert, damit die App mitgekommt, ob sich die aktuelle Position verändert hat und passt anschließend die Seite an.

Das funktioniert natürlich bei Kindle auch geräteübergreifend, weil Du durchaus auch mit der Kindle-App auf dem PC gelesen werden kann. Der Anfang der zuletzt gelesenen Seite wird synchronisiert. Das kann nur funktionieren, wenn es keine Unsicherheit bei der verwendeten App gibt, ergo muss es eine App geben, welche geräteübergreifend zur Verfügung steht, um das auf bbs/calibre übertragen zu können.

Gruß
Markus

**Comment by rvolz** [comment]
Ich fürchte so etwas gibt es derzeit nicht.
