### ISSUE TITLE
Anzeige von Büchern mit bestimmtem Schlagwort unterdrücken?

### ISSUE THREAD

**Issue by zweiundvierzig** [rvolz/BicBucStriim#235]
Besteht die Möglichkeit, das ein Benutzer die Bücher denen ein bestimmtes Schlagwort zugeordnet oder in eine bestimmte Reihe einsortiert sind, nicht angezeigt bekommt?

Damit könnte man benutzerabhängig filtern und müsste nicht mehrere Instanzen von BBS installieren.

Viele Grüße,
Tobias

**Comment by rvolz** [comment]
Die Benutzerkonfiguration leistet das, man kann dort Bücher nach Sprache und Schlagwort filtern.
