### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Boerenmotor** [rvolz/BicBucStriim#238]
After completing installation and configuration I get an "Http error 500" whenever I try to download an epub.

Did an installation and the board is green except for the open_basedir, this is yellow, but shows my directory containing the library.

**Comment by rvolz** [comment]
Please switch on debug mode (https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) and look into the log files. There should be error messages detailing the problem.

**Comment by Boerenmotor** [comment]
For reasons totally unclear to me it started working before I even had the chance to turn debuggin on. Now it's ignoring the updates to my calibre library...hope that wil fix itself too

**Comment by rvolz** [comment]
I see, then you should probably change the way you copy/sync the Calibre library to the NAS. Depending on the mechanism used it can take some time until the file system notices a change, in other cases not all files were copied etc. 

FWIW: I use rsync to sync my library and that works reliably.
