### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by csgnyc** [rvolz/BicBucStriim#240]
I used to have BicBucStriim working correctly on my Synology, recently (and absent-mindedly) deleted Web Station, and cannot seem to get BBS working again.

Running the install check, I get 2 issues:

**Issue 1**:  URL rewriting is not enabled.  BBS explains that "BicBucStriim contains a .htaccess file that enables URL rewriting on Apache servers automatically. If this is an Apache web server and the check failed, please change the URL rewriting (mod_rewrite) settings of your server/device."  Under Web Station settings, I can confirm that the HTTP back-end server is Apache HTTP Server 2.4.  If I open the .htaccess file within the BBS folder I get the following, which seems to indicate that mod_rewrite is on.  Any help?:

```
<IfModule mod_rewrite.c>
    Options -MultiViews

	# Tell PHP that the mod_rewrite module is ENABLED.
    SetEnv HTTP_MOD_REWRITE On

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [QSA,L]
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

# protect database
<FilesMatch data.db>
    Order allow,deny
    Deny from all
</FilesMatch>

# protect schema
<FilesMatch schema.sql>
    Order allow,deny
    Deny from all
</FilesMatch>
```
**Issue 2:**  BBS tells me that SQLite3 is not enabled.  BBS explains "The Sqlite3 database library is required to read the Calibre library data. Sqlite support for PHP is often contained in a module like php5-sqlite. Please install the Sqlite3 support if the check failed."  However, if I go to web station PHP settings, I can confirm that using PHP 5.6, I have checked off the MSSQL and sqlite3 extensions.  Any help?  Thanks

**Comment by rvolz** [comment]
I checked with Apache 2.4 and that doesn't work at all for me - I only get error pages - error code 500. I have to check why, and also for the nginx configuration, see #236.

As a workaround you could try to use Apache 2.2 instead, that one is working.

**Comment by csgnyc** [comment]
Going back to 2.2 fixed it for me.  Thanks.
