### ISSUE TITLE
Download on mobile

### ISSUE THREAD

**Issue by andymed** [rvolz/BicBucStriim#242]
Hi when i try to download books to my mobile the files don't open. Ive tried pdf, epub and mobi. It works fine on my laptop, using the same portal.

**Comment by rvolz** [comment]
So you tried to download the book files from a BicBucStriim detail page via a mobile browser, right? Are the downloads damaged or doesn't the browser know what to do with the file formats?

**Comment by rvolz** [comment]
Is this linked to #245? See there.
