### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by bitnikrbt** [rvolz/BicBucStriim#243]
Hi,

I have installed BicBucStriim 1.3.6. on a WD MybookLive. I get access to the page MYBOOKLIVE/my_test_library/installcheck.php with all green lights except for Mcrypt and Module intl that are yellow.
Calibre directory check gets green light as well.

But...

When I try to access the main configuration page on MYBOOKLIVE/my_test_library/ i get a white page on MYBOOKLIVE/my_test_library/admin/configuration/

Any suggestion ?

Thanks

Rob

**Comment by rvolz** [comment]
The first step would be to switch on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) to look for errors.

**Comment by bitnikrbt** [comment]
Hi Rainer,
the output of the log file is as follow:

INFO - 2017-02-25T08:15:29+01:00 - BicBucStriim 1.3.6: Running in debug mode.
INFO - 2017-02-25T08:15:29+01:00 - multi user mode: login required
DEBUG - 2017-02-25T08:15:29+01:00 - own_config_middleware: config loaded
WARN - 2017-02-25T08:15:29+01:00 - check_config: Calibre library path not configured.
INFO - 2017-02-25T08:15:30+01:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2017-02-25T08:15:30+01:00 - caching_middleware: caching disabled for /admin/configuration/
INFO - 2017-02-25T08:15:30+01:00 - multi user mode: login required
DEBUG - 2017-02-25T08:15:30+01:00 - own_config_middleware: config loaded
WARN - 2017-02-25T08:15:30+01:00 - check_config: Calibre library path not configured.
DEBUG - 2017-02-25T08:15:30+01:00 - login resource: /admin/configuration/
INFO - 2017-02-25T08:16:13+01:00 - BicBucStriim 1.3.6: Running in debug mode.
INFO - 2017-02-25T08:16:14+01:00 - multi user mode: login required
DEBUG - 2017-02-25T08:16:14+01:00 - own_config_middleware: config loaded
WARN - 2017-02-25T08:16:14+01:00 - check_config: Calibre library path not configured.
INFO - 2017-02-25T08:16:14+01:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2017-02-25T08:16:14+01:00 - caching_middleware: caching disabled for /admin/configuration/
INFO - 2017-02-25T08:16:14+01:00 - multi user mode: login required
DEBUG - 2017-02-25T08:16:14+01:00 - own_config_middleware: config loaded
WARN - 2017-02-25T08:16:14+01:00 - check_config: Calibre library path not configured.
DEBUG - 2017-02-25T08:16:14+01:00 - login resource: /admin/configuration/

Thanks for any suggestion.

Rob

**Comment by rvolz** [comment]
Thx for the log snippet, but there are no errors according to it. The server recognized that there is no configuration and that authorization is required. Normally you would now be presented with the login form, followed by the configuration screen.

The only thing I can recommend now is to look into your browser console, are there any errors? The app relies heavily on Javascript, is that activated?

**Comment by bitnikrbt** [comment]
Unfortunatelly no login form.
Java is working fine and updated to the latest release.

Already a long time BBS user, old BicBucStriim installation 1.1.0 works like a charm!

Any suggestion ?

Rob.

**Comment by rvolz** [comment]
Did you try version 1.4? Did your problem go away?
