### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by Aziona** [rvolz/BicBucStriim#247]
Hello, I lost my admin password. Is everything lost now?

**Comment by Aziona** [comment]
Just found out that you just need to delete the data.db file.

**Comment by Skeeve** [comment]
I'd suggets to open data.db with sqlite (or something like DbVisualizer). Then run this update statement

    update config
    set val=0
    where name='must_login'

Aftre that you can access  the configuration and change your admin password as well as changing back the "must_login" to 1.
