### ISSUE TITLE
I cant see send-to-kindle option

### ISSUE THREAD

**Issue by dhellin** [rvolz/BicBucStriim#248]
Hi all,
i have already configured smtp server, but i cant see the send to kindle option; just download.
¿can you help me?

**Comment by rvolz** [comment]
The feature is visible when

* the sent-to-kindle feature is activated in the admin section, see http://projekte.textmulch.de/images/bbs-121-sendtokindle.png
* the title has a suitable kindle format

**Comment by dhellin** [comment]
Thanks a lot.
