### ISSUE TITLE
Is there an access log? Wouldn't it be good to have one?

### ISSUE THREAD

**Issue by Skeeve** [rvolz/BicBucStriim#251]
Is there any way to see when my library was accessed by which user?

If there isn't, wouldn't it be good to add this information?

**Comment by rvolz** [comment]
Sorry for the extremely late answer! If you look at the log files you should see lines like `logged in user : xxx`. This is logged at INFO level. I hope your web server doesn't ignore that.

**Comment by Skeeve** [comment]
No issue.

Seems my QNAP is ignoring it.

**Comment by rand82** [comment]
You could modify the confprod() in the index.php to write the log directly to a logfile inside of the data-folder
`$app->getLog()->setWriter(new \Slim\Extras\Log\DateTimeFileWriter(array('path' => './data/logs', 'name_format' => 'Y-m-d')));`

You have to change the global loglevel to see the information 
`$app->getLog()->setLevel(\Slim\Log::INFO);`
or change the loglevel of the logmessage in perform_login() in index.php
from
`$app->getLog()->info('logged in user : ' . $app->auth->getUserName());`
to
`$app->getLog()->alert('logged in user : ' . $app->auth->getUserName());`
