### ISSUE TITLE
Convert XX to Mobi for sent to kindle

### ISSUE THREAD

**Issue by c-yco** [rvolz/BicBucStriim#253]
It would be great to integrate ebook-convert from calibre so BBS would convert the ebook on the fly before sending it to the kindle. 

Better then having every book stored as epub and mobi.

**Comment by rvolz** [comment]
Nice idea, but I'm trying to keep BicBucStriim as close to normal web app requirements as possible. Adding Calibre to the list of dependencies wouldn't help there. 

Maybe we can add a plugin system to V2 later, so that people could add there own modules.
