### ISSUE TITLE
Log [admin/admin] impossible 

### ISSUE THREAD

**Issue by Aurigod** [rvolz/BicBucStriim#254]
Impossible to logon with admin/admin. 
I work with only https and I got a .htaccess in my apache config yet.
I try several times :  impossible.
Is it possible to disable the function login in index.php, **I don't need it.**
I have just a Red Circle in installcheck in GD module but it is OK. I have checked witth phpinfo()
thanks...

**Comment by rvolz** [comment]
If there is already a data/data.db file you could edit it with: `insert into config values (NULL, 'must_login', '0');` 

This switches off the login requirement, and you should immediately get the configuration screen, if everything else is ok.

**Comment by Aurigod** [comment]
Thanks for your answer.
I don't manage to write the value in the database. I got an error message.
I try with W32 and db Browser for Windows.
Perhaps the same reason when the login is rejected in the browser?
Can you send me just the original database with this value inserted?
regards


2017-08-04 8:41 GMT+02:00 Rainer Volz <notifications@github.com>:

**Comment by rvolz** [comment]
As mentioned in the documentation, the database should be writeable. If it is not, the app will not work. Here is the empty db with login disabled
[data.db.zip](https://github.com/rvolz/BicBucStriim/files/1200957/data.db.zip)

**Comment by Aurigod** [comment]
Hello
I'm sorry but it's not possible yet.
I tried with the new data.db

First my conf :
[image: Images intégrées 1]
GD version is OK for me
[image: Images intégrées 2]
Now the logon
[image: Images intégrées 3]
[image: Images intégrées 4]

 only  https is allowed
*I could change and try on http local if you want*

<VirtualHost *:80>
>   ServerName cachou.net
>   Redirect / https://cachou.net
> </VirtualHost>


the logon :
[image: Images intégrées 5]
after 1 second the page is reloaded.
If I'm boring you, leave it, no problem thanks

2017-08-04 18:08 GMT+02:00 Rainer Volz <notifications@github.com>:

**Comment by rvolz** [comment]
I can't see your images on Github, please repost them here. 

BicBucStriim doesn't care about HTTPS or HTTP, however it cares about the .htaccess file included. Did you integrate it in your configuration? Your virtual host declaration doesn't show that.

**Comment by Aurigod** [comment]
[CLOSED]
the issue came from a lack of space on my partition.
100%
All seemed to work normally but...!
thanks for your help


2017-08-04 23:25 GMT+02:00 Rainer Volz <notifications@github.com>:
