### ISSUE TITLE
Show a list of series in the author detail page

### ISSUE THREAD

**Issue by rand82** [rvolz/BicBucStriim#255]
First thanks for the great BBS! :+1: 

Nice enhancement to give the user the possibility to see all series from an author on top of the detail page. 
I thought of the collapseable div from the books_detail page to show on top of the author details page.

Thanks
![example](https://user-images.githubusercontent.com/31099774/29412295-702cd17c-8358-11e7-8cf2-95a6da8f3604.png)
!

**Comment by rvolz** [comment]
I'll see if it can be added without complicating the setup.

**Comment by rand82** [comment]
I have modified the code to meet my needs. Maybe it's OK for you too. But be warned I'm no php-coder :see_no_evil:  I'm not familiar with Git until now, so I've attached the modified files.


[changes.zip](https://github.com/rvolz/BicBucStriim/files/1256899/changes.zip)
