### ISSUE TITLE
How to enable URL REWRITE on Synology

### ISSUE THREAD

**Issue by foreigncarnut** [rvolz/BicBucStriim#256]
I am getting a red light on the Installcheck for the URL Rewriting being turned on but I have no idea how to turn it on. I have a Synology NAS and am using an the Apache Webserver

**Comment by rand82** [comment]
I ran into the same issue but solved it. You have to edit the .htaccess 
Mine looks like this:

'# Options -MultiViews
# Tell PHP that the mod_rewrite module is ENABLED.
# SetEnv HTTP_MOD_REWRITE On

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

# protect database
<FilesMatch data.db>
    Order allow,deny
    Deny from all
</FilesMatch>

# protect schema
<FilesMatch schema.sql>
    Order allow,deny
    Deny from all
</FilesMatch>

'

**Comment by rvolz** [comment]
Did the above work for you? 

If the Synology setup is ok, the most likely problem is that the .htaccess file wasn't properly unzipped. It's a hidden file, so people tend to overlook it.

**Comment by foreigncarnut** [comment]
Hello Rainer –

 

No, it did not. It appeared that code was already there. To be quite honest, however, I think it is a knowledge issue on my part. My library exists on a separate computer (not on the NAS) and I was not able to have the Synology NAS point to it. Then when I tried to get the library transferred to the NAS, I could not find a way to copy folders, only files and I did not want to rebuild the structure. The best I seem to be able to do is to import a book stored on the NAS into the local library and use it that way. I wish I was smarter about this. It is really great of you to check on me. If there is a step by step process, I could probably follow that.

**Comment by rvolz** [comment]
No, BicBucStriim needs the library on the NAS. The simplest way to sync a library between a PC and a NAS is to learn about [rsync](https://www.digitalocean.com/community/tutorials/how-to-use-rsync-to-sync-local-and-remote-directories-on-a-vps), see the tutorial. It works very reliably and transfers only the new/modified files.

**Comment by rvolz** [comment]
If the URL rewriting is still a problem, please verify that you are using Apache 2.2 on Synology, the other one didn't work.

**Comment by foreigncarnut** [comment]
Hello Reiner

 

Yes, I had to drop down to version 2.2

 

But I am running Apache 2.2

 

It still does not show green though
