### ISSUE TITLE
[SECURITY] Images can be retrieved without login

### ISSUE THREAD

**Issue by josefglatz** [rvolz/BicBucStriim#258]
This should be prevented. What do you think?

**Comment by rvolz** [comment]
In an earlier version this was the case. However, some clients (like Aldiko or Tolino iirc) didn't send authorization headers for images, and so that had to be changed.

**Comment by josefglatz** [comment]
Hi,

I'm running the latest stable which is installable via synocommunity. The update check  says that there is no update.

I've tested it with default Chrome browser in private session. 

Should I switch to master?

Thx


Von meinem iPhone gesendet

**Comment by rvolz** [comment]
Sorry, I shouldn't have answered questions so early. What I meant was, that the download prevention for images was active in an earlier version. 

It had been deleted then because some clients didn't send the necessary authorization data (after login) for images -- for books yes, but not for images.

**Comment by josefglatz** [comment]
Ah, ok,

Is it possible to add a setting to enable/disable that?

**Comment by josefglatz** [comment]
I mean, it would be nice that nothing of the library can be fetched if you're not authenticated

**Comment by josefglatz** [comment]
A new setting would be nice to de-/activate such a limitation

**Comment by Magneticdud** [comment]
another security problem is that, if someone configures it on lighttpd/nginx/IIS according to the wiki, it's possible to download /data/data.db. It contains the password and so anyone can login

probably with shodan it's easy to find BBS installations running on anything except apache and hack them

**Comment by rvolz** [comment]
Thanks for the heads up @Magneticdud, I added some info regarding security to the wiki.

**Comment by rvolz** [comment]
In V2 all requests go through the API, so pictures can't be downloaded without login anymore

**Comment by rvolz** [comment]
Just for the record: I removed that solution. Loading the images via AJAX is too slow.
