### ISSUE TITLE
Retrieve username and password

### ISSUE THREAD

**Issue by zeppelie** [rvolz/BicBucStriim#259]
How can I retrieve my username and password that I lost???

**Comment by rvolz** [comment]
If there is still an admin user that on could look up all existing user names and issue a new password.

**Comment by zeppelie** [comment]
it's lost too... :'(

**Comment by rvolz** [comment]
If you know some basic SQL you could follow the procedure below. If not, you could delete `data.db` and start fresh with admin/admin, the rest of the data would be lost then, of course.

Get new password `php -r 'print_r(password_hash("new password", PASSWORD_BCRYPT));'`
That will print something like "$2y$10$etGuvM9MfxpWrpcbUu3A4eD/QpZVz49nuAz.gTeZvVJIGhYg227ja%". The password is everything except the final "%".

Get the existing usernames from data.db: `select username from user;`

Update password: `update user set password="..." where username="...";

After that you should be able to log in again.

**Comment by zeppelie** [comment]
thank you very much!
