### ISSUE TITLE
BBS on Asustor ADM 3.x - Error 500 [an error occurred while processing this directive] 

### ISSUE THREAD

**Issue by padanfain2000** [rvolz/BicBucStriim#261]
Hi rvolz,
First off, I really, really love bbs and had it running ever since I got my first NAS. Great Job!

Usually I had no issues running bbs at all. It was running on my Asustor and is now running on my Synology. Having said that, I updated my Asustor to: ADM 3.0.1.R9J2 which now features
Apache/2.4.25 (Unix) PHP/5.6.30. Unfortunately this cannot be configured. BBS stopped working alltogether showing only: 

Serverfehler!

[an error occurred while processing this directive] Die Anfrage kann nicht beantwortet werden, da im Server ein interner Fehler aufgetreten ist.

Fehlermeldung: 
(none)

Error 500

I have now reinstalled it on my Synolgy and it works like a charm.
Any chance to get this running with above Apache/PHP combo at all? I tried your dev build but same Error.

Cheers,
pf2k

**Comment by rvolz** [comment]
You could switch on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) and see what causes the error.

**Comment by padanfain2000** [comment]
Hi rvolz,
I just tried and it doesn't even produce a log :( It seems like not even the index.php is being interpreted.

**Comment by rvolz** [comment]
Then you should check that the .htaccess file is there and is interpreted by the web server. Sometimes this is disabled by default, for security reasons. Then you must enable it in the Apache config.

**Comment by padanfain2000** [comment]
- Checked the file presence and it was there
- checked apache2.conf and .htaccess was allowed (I explicitly added it for my bbs folder to make sure)

- renamed .htaccess and the page showed halfway... strange.
- edited the .htaccess file by leaving out the lower half like so:
<IfModule mod_rewrite.c>
    Options -MultiViews

	# Tell PHP that the mod_rewrite module is ENABLED.
    SetEnv HTTP_MOD_REWRITE On

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [QSA,L]
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

# protect database
#<FilesMatch data.db>
#    Order allow,deny
#    Deny from all
#</FilesMatch>

# protect schema
#<FilesMatch schema.sql>
#    Order allow,deny
#    Deny from all
#</FilesMatch>

and it's working now...!
installcheck shows me, that everything (apart from GD Module) is working as required.

I still don't quite get it, but am happy to have it running again. From what I could google it seems like something is amiss with the apache SSI which apparently tries to interpret something wihtin the .htaccess file but spectacularly fails.

cheers,

pf2k

**Comment by rvolz** [comment]
The FilesMatch directive? Strange, that is an old directive. Maybe they made the same changes as Synology for Apache 2.4. The last time I checked, 2.4 had problems there.
