### ISSUE TITLE
ID Templates

### ISSUE THREAD

**Issue by janstanka** [rvolz/BicBucStriim#262]
Impossible to submit ID template settings values (name, URL). 
example->
name: "Databaze knih"
URL: "https://www.databazeknih.cz/knihy/%id%"

BBS ver. 1.3.6 (Synology DSM package)
browser Firefox 56.0.1 (64bit)

**Comment by rvolz** [comment]
Could you please explain the problem? I just checked and the templates seem to work ...

**Comment by janstanka** [comment]
I'm sending images of configuring template in steps.
1. step
![1 step](https://user-images.githubusercontent.com/33105491/32174557-8072bb78-bd82-11e7-9d21-1cccab12db0c.png)
2. step
![2 step](https://user-images.githubusercontent.com/33105491/32174559-8090df4a-bd82-11e7-94e4-029a2bbf5e9e.png)
3. step
![3 step](https://user-images.githubusercontent.com/33105491/32174560-80b7fbf2-bd82-11e7-98ac-d70271518e62.png)
4. step
![4 step](https://user-images.githubusercontent.com/33105491/32174562-80e42b50-bd82-11e7-9334-0e14c42cbe54.png)
result
![5 step - result](https://user-images.githubusercontent.com/33105491/32174556-804c0a46-bd82-11e7-969f-d72dd3562e3b.png)

I've tried on Firefox, MSIE 11, Chrome on Android and Dolphin on Android with same behaviour.

**Comment by rvolz** [comment]
Ok, thanks. I tried to replicate your problem. I entered the same URL, see pic, and everything worked (green), as it should:
<img width="293" alt="bildschirmfoto 2017-10-30 um 15 48 38" src="https://user-images.githubusercontent.com/1092531/32177380-7a9522b0-bd8a-11e7-9f24-360ba7610d0b.png">

The generated links worked to:

<img width="464" alt="bildschirmfoto 2017-10-30 um 15 55 15" src="https://user-images.githubusercontent.com/1092531/32177522-d04b2254-bd8a-11e7-84fb-f3bf045c5b76.png">

Maybe the error message indicates the problem. If you could switch on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) then you could look at the log files in the `data` folder. There should be warning or error messages explaining the "bad parameter" error shownin your pictures.

**Comment by janstanka** [comment]
I switched BBS to debug mode and here is the part of log:

INFO - 2017-10-31T08:12:09+01:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2017-10-31T08:12:09+01:00 - caching_middleware: caching disabled for /admin/idtemplates/databazeknih
INFO - 2017-10-31T08:12:09+01:00 - multi user mode: login required
DEBUG - 2017-10-31T08:12:09+01:00 - own_config_middleware: config loaded
DEBUG - 2017-10-31T08:12:09+01:00 - login resource: /admin/idtemplates/databazeknih
DEBUG - 2017-10-31T08:12:09+01:00 - after resume: VALID
WARN - 2017-10-31T08:12:09+01:00 - admin_modify_idtemplate: invalid template id databazeknih

**Comment by rvolz** [comment]
It seems there is a problem with the id _databazeknih_, which produces the error. As far as I can see from your pics and logs the ID looks like an ASCII string. The ASCII string  _databazeknih_ would of course work as an ID. However, the warning in the log says: it isn't an ASCII string. 

Could you please check for non-ASCII characters in this ID? See _Identifiers_ in Calibre.

**Comment by janstanka** [comment]
I did not found any non-ASCII chars in string. But I tryed the same procedure with ISBN identifier with values:
Display text: "isbn"
URL: "https://isbnsearch.org/isbn/%id%"
and the result was the same - Bad parametr (same as on 5-th. picture).  I remember that in some previous version of BBS was it functional (maybe 1 year ago).

**Comment by rvolz** [comment]
It still is functional, at least over here. There must be some encoding issue. 

There is a change that could help with this issue. Could you please try that out? if it works for you I'll add it to the new version:

In index.php change the line 394

```php
   // parameter checking
    if (!preg_match('/^\w+$/',$id)) { // <-- this one
        $app->getLog()->warn('admin_modify_idtemplate: invalid template id ' . $id);
        $app->halt(400, "Bad parameter");
    }
```
to 
```php
    if (!preg_match('/^\w+$/u',$id)) { 
```
The "u" adds unicode support and should solve the problem. Repeat the same for line 433.

**Comment by janstanka** [comment]
My index.php is looking different. Look at lines 394 and 433.
[index.zip](https://github.com/rvolz/BicBucStriim/files/1434328/index.zip)

**Comment by rvolz** [comment]
Glad to hear that. I'll add it to the code and will release 1.3.7 soon
