### ISSUE TITLE
Different results when accessing via /bbs and /bbs/index.php

### ISSUE THREAD

**Issue by feuermandel** [rvolz/BicBucStriim#263]
Dear supporter,

I try to use this tool with native ubuntu and debian (raspberry) and I am getting the same error on both systems:

- When accessing the web-page using <IP-address>/bbs everything looks stylish, but I can not download any file.

- When accessig the web-page using <IP-address>/bbs/index.php no fancy style get applied, but I can download my ebooks.

When testing with /bbs/installcheck.php every button is green (except for GD2), but I am sure, I have installed GD2 and previed pictures get generated..

Sorry, but I am to stupid to find my error. Any suggestions?

Thanx a lot

**Comment by rvolz** [comment]
If everything else is ok, then you could turn on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode). Maybe the log files show some errors.
