### ISSUE TITLE
sqlite and GD on DSM6.x not working

### ISSUE THREAD

**Issue by marc0janssen** [rvolz/BicBucStriim#264]
I can't get BicBucStriim te work on a synology DSM6.x.
It keeps requesting for GD en Sqlite3.

I tried all the info I got from the web not nothing seems to help.

Can someone help out a little?

**Comment by rvolz** [comment]
Maybe they are not enabled? Then you would have to enable them in the Synology Settings/Web Station. There is a list with extensions, that can be checked.

**Comment by marc0janssen** [comment]
Hi RAiner,

I searched in the web station (as this was my first thought) but I can not find any checkboxes to enabled modules…

DO you have a tip where to find it?

Best regards
Marco

**Comment by marc0janssen** [comment]
oh, I found some screenshots on the web.
But for me the extensions are not shown on that page...

That is very weird.

**Comment by rvolz** [comment]
I'm using DSM 6.1.3, and if you logged in as **admin**  you should be able to see the extensions on the page called php settings in web station. If not, then you could look if the packages for PHP, Apache etc are installed

**Comment by marc0janssen** [comment]
Yes all of those are installed. So that is not the problem.
I found another problem thought.
Which I will test some more and the write out here.

It involves a downgraded of the webstation to a version in 2016 and then a upgrade again.
Further more , safari shows the extensions In a compressed view, while Firefox displays it correctly.

Will test so more.

**Comment by marc0janssen** [comment]
OK ... This is the case.
I run a DS214play. The current version of the webstaton seems not to display the extensions. Sometimes the pages just was greyed out.

I did the following:
1. downloaded the following packages from Synology at the address: http://usdl.synology.com/download/Package/spk/

WebStation-i686-1.0-0051.spk
Apache2.2-i686-2.2.31-0011.spk
PHP5.6-i686-5.6.30-0052.spk

warning: CHECK if the architecture is correct for your NAS (ie. i686)

2. Uninstalll the current packages: webstation, php 5.6 and apache.
3. reboot.
4 install WebStation-i686-1.0-0051.spk
5.reboot
6. install PHP5.6-i686-5.6.30-0052.spk
7. reboot
8. install Apache2.2-i686-2.2.31-0011.spk (this might fail, which is not a problem, install it later after the upgrade of webstation)
9. reboot
10. check if you have the extension available in the php-setting in webstation. (note: safari will display them in a small/single line in the bottom and it is only visible if you enlarge the complete webstation window. ADVISE: use FIREFOX!)
11. install BIcBUcSTriim and check the installation check page, is the module are still missing , endble them in the page discribes in step 10.
12. if all works, upgrade, the apache, webstation, and PHP 5.6 the the latest build.
13. reboot.
14. check again the installation checkpage.
15. Drink a beer. Be happy!

**Comment by marc0janssen** [comment]
And to finish it up:

 Bicbucstriim works like a charm now!!

**Comment by rvolz** [comment]
good to hear that!
