### ISSUE TITLE
More a missing feature: how to look for a book or an author starting with  string?

### ISSUE THREAD

**Issue by Fabien68** [rvolz/BicBucStriim#265]
Hello,

I tried B% but the search looks like '%B%'

Is there a possibility to search for an author or book title with starting letter ?

Thanks for that !

Regards
Fabien

**Comment by rvolz** [comment]
The app currently assumes lazy users and surrounds the search term automatically with `%...%`, which finds every occurrence of the term.

I guess we could relax that in the future and do this only when there is no `%`in the search term. So you could then search for `B%`or `%B`.

**Comment by Fabien68** [comment]
Dear Rainer,


Thanks a lot for your quick response. I have another question:


In my calibre library, I have my books available in 2 formats, EPUB and AZW3.


Using my Kindle voyage's integrated browser, when I try to download AZW3 file, I got an error indicating

"File type invalid

The experimental web browser cannot download this type of file.


Only files with extension .AZW, .PRC, .MOBI or .TXT can be downloaded on your Kindle"


If I upload the AZW3 using usb cable, there's no issue.


As I am not a web programmer, I could not figure out what is the reason for that.... Do you have an idea?


Regards

Fabien





________________________________
De : Rainer Volz <notifications@github.com>
Envoyé : mardi 21 novembre 2017 10:16
À : rvolz/BicBucStriim
Cc : Fabien68; Author
Objet : Re: [rvolz/BicBucStriim] More a missing feature: how to look for a book or an author starting with string? (#265)


The app currently assumes lazy users and surrounds the search term automatically with %...%, which finds every occurrence of the term.

I guess we could relax that in the future and do this only when there is no %in the search term. So you could then search for B%or %B.

**Comment by rvolz** [comment]
Hello Fabien, that seems to be a restriction imposed by Amazon, see #142. If you search for it you'll find lots of posts by people trying to email or download AZW3s with the same result. 

Using MOBI or transfer via USB seem to be the alternatives.

**Comment by Fabien68** [comment]
Hello Rainer,


Thanks for your quick response.


I was talking yesterday about this with a colleague of mine who told me that it is possible to download azw3 using the program *COPS* [which also uses Calibre library to publish books ].

I did not believe him and I tried yesterday night from his home: I can confirm that it works.


In case you're interested to see how it's achieved, the program is a PHP freeware located  at  http://blog.slucas.fr/en/debian/start .

My knowledge in PHP / Web is too poor for me to investigate...

Regards
Fabien


________________________________
De : Rainer Volz <notifications@github.com>
Envoyé : lundi 27 novembre 2017 10:22
À : rvolz/BicBucStriim
Cc : Fabien68; Author
Objet : Re: [rvolz/BicBucStriim] More a missing feature: how to look for a book or an author starting with string? (#265)


Hello Fabien, that seems to be a restriction imposed by Amazon, see #142<https://github.com/rvolz/BicBucStriim/issues/142>. If you search for it you'll find lots of posts by people trying to email or download AZW3s with the same result.

Using MOBI or transfer via USB seem to be the alternatives.

**Comment by rvolz** [comment]
Thx for sharing, Fabien. You were right, Calibre and COPS use a different MIME type for downloading books. Although that one is officially [deprecated](https://www.iana.org/assignments/media-types/application/vnd.amazon.mobi8-ebook), it is the only one that works currently. 

I'll update the app.

**Comment by rvolz** [comment]
Could you please check if this version works for you?

**Comment by Fabien68** [comment]
Hello Rainer,


FANTASTIC !


I will be able to give you a response only this evening when I am at home.

Can I only replace some files or should I re-install all ?  if I can only replace some files, can you tell me which one ?

I am asking because the application is running on an Asustor NAS and I only downloaded the App from the asustor store - the new version would not be available immediately, for me it is much easier to replace the changed files.


Regards

Fabien


________________________________
De : Rainer Volz <notifications@github.com>
Envoyé : mardi 28 novembre 2017 12:00
À : rvolz/BicBucStriim
Cc : Fabien68; Author
Objet : Re: [rvolz/BicBucStriim] More a missing feature: how to look for a book or an author starting with string? (#265)


Could you please check if this version works for you?

**Comment by rvolz** [comment]
It is sufficient to replace `lib/BicBucStriim/utilities.php` with the current one in Github. If it works for you I'll release a new version.

**Comment by Fabien68** [comment]
Ok, thanks ! I let you know as soon as I am at home this evening.


May I ask where you are living? I am next to Basel.


Regards

Fabien


________________________________
De : Rainer Volz <notifications@github.com>
Envoyé : mardi 28 novembre 2017 12:35
À : rvolz/BicBucStriim
Cc : Fabien68; Author
Objet : Re: [rvolz/BicBucStriim] More a missing feature: how to look for a book or an author starting with string? (#265)


It is sufficient to replace lib/BicBucStriim/utilities.php with the current one in Github. If it works for you I'll release a new version.

**Comment by rvolz** [comment]
I'm currently in Berlin.

**Comment by Fabien68** [comment]
Hello Rainer,


A bit too far to drink something together. Let me know if you're come next to here.


I'd like also to confirm that IT WORKS

Regards
Fabien

________________________________
De : Rainer Volz <notifications@github.com>
Envoyé : mardi 28 novembre 2017 18:57
À : rvolz/BicBucStriim
Cc : Fabien68; Author
Objet : Re: [rvolz/BicBucStriim] More a missing feature: how to look for a book or an author starting with string? (#265)


I'm currently in Berlin.

**Comment by rvolz** [comment]
The commit https://github.com/rvolz/BicBucStriim/commit/2d408d0f43c8d6097646ba2442992b69a6999929 changed the search syntax (the usual "*?" instead of SQLs "%_") and removed the automatic addition of wildcards around search terms.
