### ISSUE TITLE
data.db upgrade instead of new start after each upgrade/update

### ISSUE THREAD

**Issue by royvanmanen** [rvolz/BicBucStriim#267]
After installing new version I always have to copy the users from the old one in the new one using a sqlite tool. Would be better if db could be upgraded.

**Comment by rvolz** [comment]
Sorry for the late reply. Normally you can just reuse the existing data.db, copy it. The last time a database change was required, was with version 1.25.

I agree, that an update-script would be nicer. It's on the list.

**Comment by rvolz** [comment]
See #83
