### ISSUE TITLE
Sending to Kindle don´t work with gmx or gmail

### ISSUE THREAD

**Issue by KSchwaier** [rvolz/BicBucStriim#269]
When I try to send to Kindle there will be an error "check email"
Sending via calibre direct to Kindle it works fine.
Sending with bicBucStriim to Kindle an error occurs.
(the mail is registered at amazon!!)

**My configuration:**
Version:      1.4.1 on Synology NAS (6....)
Mail:            xxxxxx@gmx.de
Password:   xxxxxyyyxx
SMTP:         smtp.gmx.com
Port:            587
Security:     TLS

What is wrong???

**Comment by rvolz** [comment]
I guess the "check email" error means that there is some problem with your email configuration. You could verify that by enabling [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode). If there is a connection problem with the SMTP server, the output will look similar to these lines:

```
++ Starting Swift_SmtpTransport
!! Connection could not be established with host smtp.1und1.de [ #0]
kindle: Mail dump
```

I just tried to send mail via

SMTP: smtp.1und1.de
Port: 587
Security: TLS

and that worked as before, with other SMTPs too.

**Comment by KSchwaier** [comment]
Hallo Rainer,
in Deutsch.

Habe den Fehler gefunden.
Ich habe das senden an Kindle immer nur mit einem Buch getestet.
Beim Aufruf des Browsers im Kindle erschien aber auch ein Error „temporally not available“

Nun habe ich im Books-Verzeichnis auf Synology gesehen, dass das Buch gar nicht im MOBI-Format vorliegt.

Bei einem anderen Buch, das im MOBI-Format vorliegt, klappt das Senden einwandfrei.

Warum in der Datenbank das Mobilfunknetz erscheint ,obwohl es im Verzeichnis nicht da ist, kann ich nicht sagen.

Bin gerade in Teneriffa, und wenn ich wieder zuhause bin werde ich erneut das Books-Verzeichnis synchronisieren.

Danke für Deine Hilfe



Mit freundlichen Grüßen

Konrad Schwaier
Klosterstr. 33
13581 Berlin
Tel:       030 - 35 10 22 93
Fax:      030 - 35 10 22 95
Mobil:   0172 - 304 84 99
e-Mail:  Konrad@Schwaier.net

**Comment by rvolz** [comment]
Ah ok. Der vorhandene Algorithmus geht einige Formate durch, die wohl früher einmal kompatibel mit "send to kindle" waren, es heute aber nicht mehr sind. Dieses Verhalten soll geändert werden, siehe #214.

**Comment by KSchwaier** [comment]
Hallo Rainer,
Danke für Deine Hilfe von 2018. Es lief bis jetzt einwandfrei.
Nun habe ich mir ein neues NAS (DS220+) zugelegt.
Leider konnte ich von meinem alten (DS116) nicht auf die DS220+ migrieren.
Bei Synology kann man leider nicht von 1-bay auf 2-bay mit dem Migrationsassistenten migrieren, sondern muss manuell alles neu aufsetzen.

Nun habe ich Bicbucstriim 1.5.0 neu installiert und kann nun leider keine emails mehr an Kindle senden.
Der Debug sieht folgendermaßen aus:

INFO - 2021-02-05T00:00:04+01:00 - BicBucStriim 1.5.0: Running in debug mode.
.......
DEBUG - 2021-02-05T00:00:15+01:00 - kindle mail config: array (
  'username' => 'xxxx@yyyy.zzz',
  'password' => 'xyxyxyxy1234',
  'smtp-server' => 'mail.gmx.net',
  'smtp-port' => '587',
  'smtp-encryption' => 'tls',
)
WARN - 2021-02-05T00:00:15+01:00 - kindle: Email exception stream_socket_enable_crypto(): this stream does not support SSL/crypto
WARN - 2021-02-05T00:00:15+01:00 - kindle: Mail dump 

Was ist denn da nun falsch???
System ist DSM7 auf der Synology (funktionierte abr schon auf der DS116)

**Comment by rvolz** [comment]
Das Web sagt,  dass der Fehler auftritt, wenn OpenSSL nicht aktiviert ist. Möglicherweise also die Extension in den PHP-Einstellungen aktivieren.

Funktioniert das Mailen von Büchern an Kindles noch? Ich fragte mich, ob die Funktion noch benutzt wird, weiter nötig ist ...

**Comment by KSchwaier** [comment]
DANKE...
das wars das senden via mail geht mit: openssl-> aktiviert

Ich hatte da noch einen anderen Fehler drin.
"DEBUG:
WARN - 2021-02-05T22:51:16+01:00 - kindle: Email exception Connection could not be established with host  mail.gmx.net [php_network_getaddresses: gethostbyname failed. errno=0 #0]
Log data:
++ Starting Swift_SmtpTransport
!! Connection could not be established with host  mail.gmx.net [php_network_getaddresses: gethostbyname failed. errno=0 #0]
WARN - 2021-02-05T22:51:16+01:00 - kindle: Mail dump "

Ich hatte den SMTP-Server mit copy und paste eingefügt und dann war da leider noch am Anfang ein Leerzeichen drin.
Nun geht alles.
DANKE nochmals.

Die Mailfunktion finde ich ganz schick, da wir eine "Familienbibliothek" haben und so jeder ganz simpel die neuen eingepflegten Bücher beliebig aufs Kindle laden kann. Ich finde die Funktion ganz hervorragend.

Wenn man alleine ist, braucht man die Mailfunktion wahrscheinlich nicht. Da kann mit einem 128-er USB-Stick, die ja nun nichts mehr kosten alles lösen.
Also Danke nochmals für Deine Hilfe.
