### ISSUE TITLE
Sqlite / intl

### ISSUE THREAD

**Issue by joko63739** [rvolz/BicBucStriim#271]
Hi,
just installed Bicbucstriim and did the installcheck. Everything is green except Sqlite3 and intl although these two are checked in the php 5 settings.
When I call <mynas>/bbs I get the following error:
Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in /volume1/web/bbs/lib/BicBucStriim/bicbucstriim.php:57 Stack trace: #0 /volume1/web/bbs/lib/BicBucStriim/bicbucstriim.php(57): PDO->__construct('sqlite:/volume1...', NULL, NULL, Array) #1 /volume1/web/bbs/index.php(140): BicBucStriim->__construct('data/data.db', true) #2 {main} thrown in /volume1/web/bbs/lib/BicBucStriim/bicbucstriim.php on line 57
What can I do?

**Comment by rvolz** [comment]
There are two extensions required from WebStation: sqlite3 and pdo_sqlite.  Are both enabled?

**Comment by joko63739** [comment]
Yes, both are enabled.

**Comment by rvolz** [comment]
You could verify that the sqlite3 packages are used by the PHP version you are using with BicBucStriim. Some users had problems with multiple PHP versions on Synology in the past.

1.  in your bbs installation directory create a file called `phpinfo.php`
1. add the line `<?php phpinfo(); ?>`to that file
1. call `phpinfo.php` with your browser

You'll get a list with PHP configuration items back. Look for something like this:

<img width="887" alt="pdo_sqlite" src="https://user-images.githubusercontent.com/1092531/35356816-d80806e6-0151-11e8-9766-a08dc58eb2fb.png">
<img width="984" alt="sqlite3" src="https://user-images.githubusercontent.com/1092531/35356819-dd027d5c-0151-11e8-9f5e-24d0ff11856b.png">

If these entries don't exist -- and your error message says so -- the SQLite packages are active for the wrong PHP version. In that case you should make sure that in WebStation the extensions are loaded for the right PHP version.

**Comment by joko63739** [comment]
Hi Rainer,
phpinfo doesn’t show any entries with sqlite. When I look at the PHP settings in web station nothing is checked there.
How can I change the settings that sqlite is active for PHP 5.6 and not 7?

Von: Rainer Volz [mailto:notifications@github.com]
Gesendet: Mittwoch, 24. Januar 2018 22:06
An: rvolz/BicBucStriim <BicBucStriim@noreply.github.com>
Cc: joko63739 <joko63739@live.de>; Author <author@noreply.github.com>
Betreff: Re: [rvolz/BicBucStriim] Sqlite / intl (#271)


You could verify that the sqlite3 packages are used by the PHP version you are using with BicBucStriim. Some users had problems with multiple PHP versions on Synology in the past.

  1.  in your bbs installation directory create a file called phpinfo.php
  2.  add the line <?php phpinfo(); ?>to that file
  3.  call phpinfo.php with your browser

You'll get a list with PHP configuration items back. Look for something like this:

[pdo_sqlite]<https://user-images.githubusercontent.com/1092531/35356816-d80806e6-0151-11e8-9766-a08dc58eb2fb.png>

[sqlite3]<https://user-images.githubusercontent.com/1092531/35356819-dd027d5c-0151-11e8-9f5e-24d0ff11856b.png>

If these entries don't exist -- and your error message says so -- the SQLite packages are active for the wrong PHP version. In that case you should make sure that in WebStation the extensions are loaded for the right PHP version.

**Comment by rvolz** [comment]
In WebStation, in the tab "php settings" use the select box at the top ("php version") to switch to PHP 5.6. When you switch between version you should see that some options etc change their selection state. Then check the PHP modules you need for PHP 5.6 and save.
