### ISSUE TITLE
500 Error with .epub files, but not .mobi

### ISSUE THREAD

**Issue by SilentArtifact** [rvolz/BicBucStriim#272]
Heyo!

Love your project here, it's everything I've wanted from an ebook library and more! I've run into a snag, though; when attempting to download .epub files directly, it get a 500 error; this doesn't happen with .mobi, which is strange. Any ideas why that might be happening?

**Comment by rvolz** [comment]
I would guess that you have enabled "update metadata" in the configuration? If yes, then turning it off will probably help.

You could also turn on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) to look for the source of the problem in the log files.

**Comment by SilentArtifact** [comment]
You are a prince among men, nay, a king, etc. 

Thanks a ton!

**Comment by rvolz** [comment]
Glad to hear that it worked. To get "update metadata" working you would need to figure out, why the application can't write into the system's TEMP folder, which should be possible.
