### ISSUE TITLE
No access to BicBucStrimm

### ISSUE THREAD

**Issue by alias0102** [rvolz/BicBucStriim#275]
From Belgium.
I had to renew my synology.  Before I had BicbucStriim and Calibre running like a charm on my nas.
I had made a full backup of all my files in the directory 'web'.
After the factory reset of the NAS, installed everything new.  
My two websites are running very well.  Except the one where I have my libraries from calibre.
When I go to the internet and go to my website, everything looks like it should. 
When I click on the link to my library, I get a prompt to enter my username and password... so far so good.
But then,... after entering my userename and password... I only get a white screen in my browser.
I have tried several things in the settings (who can access, firewall, ...)  But still I get a white screen.  On every computer or tablet  I use, after username and password... White as snow.
What am I missing?

**Comment by alias0102** [comment]
![afbeelding](https://user-images.githubusercontent.com/36133737/35779619-8d69edfc-09d0-11e8-8fec-929ee8cb0092.png)
 
At last I get this checkup.  What does it mean??

**Comment by rvolz** [comment]
It means what it says: PHP support for Sqlite 3 and GD is required and missing currently. Apparently ou had them earlier but they are now disabled. 

You have to enable these modules in WebStation, tab PHP. If you enable them, you should make sure that you do this for the right PHP version. See #271
