### ISSUE TITLE
How to show download button just for PDF format

### ISSUE THREAD

**Issue by pxnji** [rvolz/BicBucStriim#276]
Halo,
I really love Bicbucstriim, Thank you for making this. Then, I tried to add pdf reader from PDF.js and it works but there is one problem, if ebook format is not PDF it will also remain open with PDF reader. So, how to show download button just for PDF format?

**Comment by rvolz** [comment]
By default BicBucStriim sends everything as a binary attachement to the browser, for download. What the browser does with that attachment depends on its configuration - that has nothing to do with BicBucStriim. 

I too have PDF.js installed, but whenever I click on download for PDF, EPUB the file is downloaded, regardless of the browser. So your best course of action would be to look into your browser's configuration and restrict your PDF viewer to files with MIME type `application/pdf`.

If you absolutely must change BicBucStriim to do that, you could adapt function `titleMimeType` in https://github.com/rvolz/BicBucStriim/blob/master/lib/BicBucStriim/utilities.php to your needs. That function tries to find the right MIME type for each book file. If it can't find the right one it uses `application/force-download`. That should force your browser to download the file.
