### ISSUE TITLE
Change the title of book detail page

### ISSUE THREAD

**Issue by bukusite** [rvolz/BicBucStriim#277]
Hello,
I tried to replace the existing part in the screenshot into the title of the book that is underneath,
[![booktitles](https://image.ibb.co/inS1bH/booktitles.png)](https://imgbb.com/)
I changed part of this index.php:
` array('page' => mkPage(getMessageString('book_details'), 2, 2),
            'book' => $details['book'],
            'authors' => $details['authors'],
            'series' => $details['series'],
            'tags' => $details['tags'],
            'formats' => $details['formats'],
            'comment' => $details['comment'],
            'language' => $details['language'],
            'ccs' => (count($details['custom']) > 0 ? $details['custom'] : null),
            'show_idlinks' => $show_idlinks,
            'ids' => $details['ids'],
            'id_templates' => $id_tmpls,
            'kindle_format' => $kindle_format,
            'kindle_from_email' => $globalSettings[KINDLE_FROM_EMAIL],
            'protect_dl' => false)
    );`
become:
` array('page' => $details['book'],
            'book' => $details['book'],
            'authors' => $details['authors'],
            'series' => $details['series'],
            'tags' => $details['tags'],
            'formats' => $details['formats'],
            'comment' => $details['comment'],
            'language' => $details['language'],
            'ccs' => (count($details['custom']) > 0 ? $details['custom'] : null),
            'show_idlinks' => $show_idlinks,
            'ids' => $details['ids'],
            'id_templates' => $id_tmpls,
            'kindle_format' => $kindle_format,
            'kindle_from_email' => $globalSettings[KINDLE_FROM_EMAIL],
            'protect_dl' => false)
    );`
but the page views of the book become messy. How do I replace that part? I use BiBucStriim to share school books but when viewed from google search then all that appears duplicate title is BicBucStriim :: Book Details not the title of the book. Thank you very much.

**Comment by rvolz** [comment]
Nearly, in this case you would need to replace the `getMessageString` call
 
```php
array('page' => mkPage(getMessageString('book_details'), 2, 2),
            'book' => $details['book'],...
```

with

```php
array('page' => mkPage($details['book']->title, 2, 2),
            'book' => $details['book'],...
```

That would give you "BicBucStriim :: book title", and if you configured also the setting "page title" then you could replace the "BicBucStriim" part too.

**Comment by bukusite** [comment]
Thanks a lot, it works!

**Comment by bukusite** [comment]
How about change it to author name?
![authir](https://user-images.githubusercontent.com/31478427/35945666-8bbc17f8-0c93-11e8-8d4c-0cba85fa1b52.PNG)

**Comment by rvolz** [comment]
You can adapt the recipe, just with the author data structure and field `...->name`. The same applies to series and tags ...

**Comment by bukusite** [comment]
Awesome! You should make this change for the next update.

**Comment by rvolz** [comment]
as mentioned above you'll need the `->name` field, not `->author` etc

**Comment by rvolz** [comment]
instead of `mkPage($details['author']->author` you should use `mkPage($details['author']->name`. title and name belong to the data structures of Calibre

**Comment by pxnji** [comment]
I did like what u said , changing it `mkPage($details['author']->name` but it doesnt change it. And im still confused about the data structures of Calibre of series and tags.
