### ISSUE TITLE
Multiple Calibre Libraries on one Server

### ISSUE THREAD

**Issue by dichter** [rvolz/BicBucStriim#278]
It would be really nice to be able to add more then one Calibre Libraries - I have for example 
a Library for Non Fiction, for English fiction, for German Fiction and also one Adult-only library. 
Libraries could be handled as a top level selector. And It would be nice if one could exclude certain users from seeing certain libraries (i.e. to exclude the kids from seeing the adult-only library). 

Currently I am using Ubooquity, but it does not know anything at all about Calibre libraries and just handles them as subdirectories (it kinda works, if one embed the metadata into the book files, but it shows the calibre internal folder numbers...)

**Comment by DoctorDri** [comment]
Hi. I have two different Calibre libraries, one for books in Spanish and another one for books in English. Therefore, I have two BicBucStriim installations on my server. Both work fine, independently, which means that different users can be created for each one.

**Comment by rvolz** [comment]
I would also recommend to use multiple installations. To deal with multiple libraries would add a lot of complexity to the app. 

There is also the tags filter to exclude certain users from seeing certain books.
