### ISSUE TITLE
Calibre Bibliotheksverzeichnis

### ISSUE THREAD

**Issue by oulifspeedy** [rvolz/BicBucStriim#279]
Hallo,

ich teste gerade bbs und habe folgenden Aufbau:
- WD My Book World mit dem Verzeichnis ebooks in dem die Dateien un die db liegen
- Windows Server 2016 mit IIS

Wenn ich auf der Admin-Seite jetzt \\IP_des_NAS\ebooks eingebe, kommt die Meldung, dass auf das Verzeichnis nicht zugegriffen werden kann. Berechtigungen sind vorhanden. Kennwörter sind auch gleich.
Jetzt ist meine Frage, wie muss ich den String eintragen? Langt es als UNC-Pfad?

Gruß
Anja

**Comment by rvolz** [comment]
Hallo, bisher ging ich davon aus, dass Anwendung und Bibliothek auf dem gleichen Rechner laufen, sich es um lokale Pfade handelt. Die Anwendung versucht an dieser Stelle den kompletten Pfad zur `metadata.db` zu ermitteln, um dann fesetzstellen, ob diese Datei lesbar ist.

Mit IP-Adressen kommt man daher an dieser Stelle nicht weiter.

**Comment by oulifspeedy** [comment]
Danke für deine Antwort. Dann weiß ich jetzt auf jeden Fall, warum es nicht geht. 
Denke, dass ich dann eine Kopie auf den Server lege und dann die Synchronisation immer wieder durchführe.
