### ISSUE TITLE
Error loading page on every search

### ISSUE THREAD

**Issue by talentedmrripley** [rvolz/BicBucStriim#280]
The search function is not working for me.  No matter what I search for I always get a small box in the center of the screen that says "Error Loading Page".  In the apache error log is this:

`[Mon Mar 12 22:53:20.360653 2018] [:error] [pid 8371] [client 172.16.0.153:8377] PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_case() in /var/www/html/bbs/lib/BicBucStriim/calibre.php:161\nStack trace:\n#0 /var/www/html/bbs/lib/BicBucStriim/calibre.php(217): Calibre->mkCountParams(NULL, Object(CalibreFilter), 'Friedman')\n#1 /var/www/html/bbs/lib/BicBucStriim/calibre.php(784): Calibre->findSliceFiltered(3, 0, 30, Object(CalibreFilter), 'Friedman')\n#2 /var/www/html/bbs/index.php(1051): Calibre->titlesSlice('en', 0, 30, Object(CalibreFilter), 'Friedman')\n#3 [internal function]: globalSearch()\n#4 /var/www/html/bbs/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('globalSearch', Array)\n#5 /var/www/html/bbs/vendor/slim/slim/Slim/Slim.php(1326): Slim\\Route->dispatch()\n#6 /var/www/html/bbs/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()\n#7 /var/www/html/bbs/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#8 /var/www/html/bbs/lib/BicBucStriim/calibre_config_middleware.php(50): Slim\\Middleware\\MethodOverride->call()\n#9 /var/ww in /var/www/html/bbs/lib/BicBucStriim/calibre.php on line 161, referer: http://books.msquared.local/bbs/`

**Comment by rvolz** [comment]
The function `mb_convert_case` is missing. It belongs to a PHP module that is normally included by default, `php...-mbstring`. You should try to enable that module in your installation.

The function was included to help with searching for non-ascii strings.

**Comment by talentedmrripley** [comment]
Thanks, that was exactly it.  It might be a good idea to update the install instructions for people not using a Synology.  I also had to install the PHP DOM package to get main page to load at all and add the <Directory /var/www> section to the sites-enabled Apache config file.
