### ISSUE TITLE
[ENHANCEMENT] Mark book as favorite

### ISSUE THREAD

**Issue by rand82** [rvolz/BicBucStriim#281]
It would be nice if I could see which books an other user has marked - because of the same flavor.

- Make a possibility to mark a book as favorite (a yellow star in book details and book list)
- Show all marked favorites as list
- Maybe the user can see which other users have marked the book as their favorite (reduce this list to e.g. 5 users) on book detail page
- Search for books an other user has marked as favorite

**Comment by rvolz** [comment]
The features make sense, but are beyond the scope of a simple personal/family library app. So I am a bit wary of feature creep. I'll look into it.
