### ISSUE TITLE
BicBucstriim redirect to NAS homepage

### ISSUE THREAD

**Issue by Sphinkie** [rvolz/BicBucStriim#282]
Hello
I have installed the _BicBucstriim_ packet on my Synology DS118, but when I enter the url 
http://<NAS address>/bbs/
or
http://<NAS address>/bbs/installcheck.php 
I am always redirected to  <NAS address>:5000 which is the login page of the synology.

I use the DSM version 6.1.5.

(note: I have not installed extra 'web packages' (as Apache or php), as I supposed that Synology comes with build-in equiped AMP web server... but maybe not ?)

Thanks for your help
David

**Comment by rvolz** [comment]
What kind of package did you install, the community package from the package manager or the zip file from the website?

**Comment by Sphinkie** [comment]
Hello
I installed the package from SynoCommunity, via the 'packet Manager'

**Comment by rvolz** [comment]
If both installations fail, then something is missing, probably a php dependency. 

First you should make sure that WebStation actually uses Apache 2.2/PHP 5.6: "Web Station > General Settings" shows what is actually being used.

If that setting is correct go to "PHP settings" and verify -- for PHP 5.6 --  that your Calibre library is in the _open_basedir_ list and that the required extensions are checked (gd, iconv, intl, pdo_sqlite, sqlite3).

**Comment by Sphinkie** [comment]
"iconv" was missing.
It works now.
Thanks for your help.
