### ISSUE TITLE
problem synology after update sqlite3

### ISSUE THREAD

**Issue by belidi** [rvolz/BicBucStriim#284]
Problem after doing the update of webstation (2.1.3.0140) on synology 211+.
can not find sqlite3 while synology indicates that it is running.

**Comment by rvolz** [comment]
Synology WebStation now can manage multiple HTTP servers/PHP versions, and each version has its own extensions. You should verify that the PHP profile BicBucStriim uses, has the extensions pdo_sqlite and sqlite3 activated.

**Comment by belidi** [comment]
missing the activation of the pdo-sqlite extension in php profile
thank you for the speed of your help

Provenance : Courrier pour Windows 10

De : Rainer Volz
Envoyé le :vendredi 23 mars 2018 18:17
À : rvolz/BicBucStriim
Cc : belidi; Author
Objet :Re: [rvolz/BicBucStriim] problem synology after update sqlite3 (#284)

Synology WebStation now can manage multiple HTTP servers/PHP versions, and each version has its own extensions. You should verify that the PHP profile BicBucStriim uses, has the extensions pdo_sqlite and sqlite3 activated.
