### ISSUE TITLE
Can't connect from Aldiko anymore

### ISSUE THREAD

**Issue by ThomasDaheim** [rvolz/BicBucStriim#286]
Hi,

when trying to access my library from Aldiko under Android I get an error message "Can't connect to server" even before being asked for a PWD.

I enabled debug mode and found the following in the log:
```
INFO - 2018-04-14T18:19:12+02:00 - BicBucStriim 1.3.6: Running in debug mode.
INFO - 2018-04-14T18:19:12+02:00 - multi user mode: login required
DEBUG - 2018-04-14T18:19:12+02:00 - own_config_middleware: config loaded
DEBUG - 2018-04-14T18:19:12+02:00 - login resource: /opds
DEBUG - 2018-04-14T18:19:12+02:00 - after resume: VALID
```
So it seems like Aldiko has reached my bbs Server but somehow they no longer talk to each other :-(

Any ideas how this could be resolved and where else to look for?

Thanks,
Thomas

**Comment by rvolz** [comment]
I just tried Aldiko with version 1.4.1 and that worked, still no pictures though. Maybe you shoud try to upgrade.

**Comment by ThomasDaheim** [comment]
OK, will try that. Need to switch to manual installation, since there is no newer packages for my NAS that 1.3.6. Anything special to keep in mind when upgrading? Or can I just overwrite the existing installation with the new download?

**Comment by rvolz** [comment]
Maybe you should put the manual one in a different directory. So you could switch back to the SynoCommunity package when they follow up.

**Comment by ThomasDaheim** [comment]
Good tip. SO now I can log in from Aldiko. But whenever I hit "Download" on a new book it doesn't work and I get "Internal Server Error" message on my phone. ^

installcheck.php show eveything as OK. Any other place I could look for more info?

**Comment by rvolz** [comment]
With debug mode enabled, there should be more detailed error messages. But first you could check, if switching off "update metadata" in the admin section helps.

**Comment by ThomasDaheim** [comment]
I can see "ErrorException: filesize(): stat failed for /volume1/Multimedia/Books/xxx" after "book download by Thomas for /volume1/Multimedia/Books/xxx".

The file in question looks OK to me when using file browser. But must be something with rights or properties - since download of other books seems to work.

Thanks!

**Comment by rvolz** [comment]
Yes, "stat errors" mean, that the HTTP user can't access the directory or book.

**Comment by ThomasDaheim** [comment]
Unfortunately, I can't see anything special with that book. rwx for all users... Is a special owner required?

**Comment by rvolz** [comment]
No, the same owner as for the other books? It could also be that one of the directories above the book is the problem. Are cover and thumbnail shown correctly? If yes, then the directories are ok. 

The most common source for download errors of EPUB files is the _metadata update_ feature. To avoid that, you could turn that feature off. If the download still fails after that, I would propose to replace the book file with a new copy. Sometimes problems like this were caused by copy errors.

**Comment by ThomasDaheim** [comment]
I have deleted & copied the folder once again and now it seems to work :-) Thanks!
