### ISSUE TITLE
Kindle 4th Generation (Model:D01100) and AZW3 Format

### ISSUE THREAD

**Issue by MacAndreas** [rvolz/BicBucStriim#287]
Hello,

I have a Synology DS with three BicBucStriim 1.4.1 installations configured to listen on different ports. I use Apache 2.4 and PHP 7.

If I try to download a *.azw3 eBook I see the notice

> The experimental web browser cannot download this type of file. Only files with extension .AZW, .PRC, .MOBI or .TXT can be downloaded on your Kindle.

In the code (utilities.php) I found the right (?) MIME-TYPE application/x-mobi8-ebook... I tried different MIME-TYPES without success, but text/plain whitch shows me the eBook as plain text (as expected :-)

I read on the Notes to 1.4.1 this issue shouldn't appear... did I do anything wrong?

Edit: the download as .MOBI works...

Andreas

**Comment by rvolz** [comment]
Maybe old firmware? I just tried it with a Kindle Voyager, Firmware 5.9.4 and AZW3 download still worked. The same with a Kindle Fire 8.

**Comment by MacAndreas** [comment]
So it is the 4th Generation the latest firmware is 4.1.3 and this is the installed version.

**Comment by rvolz** [comment]
Did you try the MIME type ``application/vnd.amazon.mobi8-ebook``? That is supposed to be the right type for Kindle books, but sometimes didn't work. So it was changed to ``application/x-mobi8-ebook``.   Maybe it works  in your case ...

**Comment by MacAndreas** [comment]
Hm, I tried vnd.amazon.mobi8-ebook without success... But, the error message is 

> Only files with extension .AZW

and not AZW3... is it possible that the Kindle 4th generation is not able to show KF8 at all?

I changed the extension from an azw3 to mobi and downloaded it with success, but got an error while opening it:

> can't open, wrong format, if it bought from Amazon, download it again... aso...

so, I think, it can't...

**Comment by rvolz** [comment]
Yes, it looks like there are restrictions. However, most Kindle books contain both versions - KF8 and MOBI - exactly for this reason. Apparently that book doesn't.
