### ISSUE TITLE
error password when I change the language 

### ISSUE THREAD

**Issue by jfcapdet** [rvolz/BicBucStriim#288]
hello,
In my NAS Qnap , when I change the password AND the language : ( I put "fra" = FRENCH) in user: admin, (only admin user) 
then I can't login with the new password , 

But if I leave " no selection" in language , the new login work fine.  (just for admin  )

**Comment by rvolz** [comment]
The app uses two-letter ids for languages, so the code for French would be "fr". Could you try that?

**Comment by jfcapdet** [comment]
I just have the 4 choices possible:
fra 
eng 
ron
ita
with 3 letters from the pulldown menu

**Comment by jfcapdet** [comment]
it is the option language : (it's just for exlude other languages on the list)

**Comment by rvolz** [comment]
You were right, I was referring to the user language. However, when I change the language and the password of a user at the same time in my test environment, everything works as exepected for me. 

To see what really causes your error you should enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode).

**Comment by jfcapdet** [comment]
For me that don't work only for the admin, the other users (not admin) work welll.
I think is my configuration or my system (on NAS Qnap).
It is not very important, if I find the problem, I shall write here the result.
thank for all
jf
