### ISSUE TITLE
Impossible to install Sqlite3 on ubuntu server

### ISSUE THREAD

**Issue by pandoux** [rvolz/BicBucStriim#289]
Hi guys,

I will deploy this project on a touchscreen in the documentation center of the school where I work.

I set up an ubuntu server.
I installed :
Ubuntu server 18.04
Apache 2.4.29
Php 7.2.5
GD 2.2.5
Sqlite 3.22.0

But Sqlite would not be installed in installcheck.php

In addition, when I go on the index.php site, I have a blank page.

An idea?

**Comment by rvolz** [comment]
You need not only to install sqlite and gd, but also the PHP adapters for them, e.g. the packages php-sqlite etc
