### ISSUE TITLE
Synology BicBucStriim No Longer Working - Database not found

### ISSUE THREAD

**Issue by caracturus** [rvolz/BicBucStriim#290]
I have been running BicBucStriim for months successfully (great program!). However, I have suddenly found that it no longer finds the metadata.db file in my books directory. The Installcheck.php page shows all green, except for the expected yellow for open_basedir restriction which still correctly shows that the books directory has been added. The Calibre director check is red. The director does exist, it contains the metadata.db file and the directory has been added to the open_basedir. 

Calibre is version 1.3.6
php is 5.6.34
Appache is 2.2.34
DSM is 6.1.7

Any ideas what has changed to cause the failure? Thanks.

**Comment by rvolz** [comment]
It could be that a recent update changed access rights or removed dependencies.

If you execute the Calibre directory check and it ends with failure, it reports some details below the red light (directory exists, is readable etc). What are the details in your case?

**Comment by caracturus** [comment]
Thanks.

Currently I get the following:

Check Directory: /volume1/Media/Books

Directory exists? No
Directory is readable? No
Directory is executable? No
Real path of database is:
Database opened? No

**Comment by rvolz** [comment]
So the app has no permissions at all to acces your library. Did you change something? Sometimes DSM upgrades also seem to change file permissions, probably in the name of security. 

You should make sure that the directory/files are readable bei the http server. You could try to make them readable ( and executable) for the group ```http```, or simply by all. That should help.

**Comment by rvolz** [comment]
Glad to hear that it works now. Sometimes it helps, when the library folder is inside a network share. User folders are shareable by default, so it might be that.
