### ISSUE TITLE
Can you translate it into other languages?

### ISSUE THREAD

**Issue by watermoonchandra** [rvolz/BicBucStriim#292]
I like this project very much. Can you translate it into other languages? such as Chinese.Just like COPS，It has many language versions.

**Comment by rvolz** [comment]
There are already some translations, added by other users, see here https://github.com/rvolz/BicBucStriim/blob/master/messages.yml. If you would like to add one, the procedure is:

* fork this project
* add your translated texts to messages.yml
* test that your translations work
* create a pull request

**Comment by xro** [comment]
OK. Added all translations in pl to messages.yml. Also added 'pl' to list of allowed langs in index.php but it is not picking it up. I found out I need my language in lib\BicBucStriim\langs.php  but I have no idea how to generate that file. Can you tell me?

**Comment by rvolz** [comment]
Sorry, I did forget to say that you had to add the language to Rakefile.rb. But now everything is merged.
