### ISSUE TITLE
Use my own domain for BBS

### ISSUE THREAD

**Issue by DoctorDri** [rvolz/BicBucStriim#295]
Not an issue but a question. Can I use my domain "domain.com" for BBS somehow?

I do this for other Synology apps, like my VideoStation is on "video.domain.com", and it's quite simple cause I just have to add a CNAME pointing to my NAS and add this domain for the app on DSM.

I can redirect my domain "books.domain.com" to BBS, but then the address change to my "example.synology.me/bbs" address, and I would like it to show just my domain as I share my books with family and friends.

Is it possible somehow?

**Comment by rvolz** [comment]
BBS tries to be agnostic as possible about the hostname. By default it generates relative URLs without hostname and port, unless you disabled the generation of relative URLs in the admin menu?

I'm no expert in this area, but AFAIK you have to give the app it's own port in the app center, like for the synology apps.

**Comment by DoctorDri** [comment]
Tweaking the DSM settings for this seemed too complicated, so I ended up frame-redirecting my domain to "example.synology.me/bbs" using a mask instead of just plain redirecting, so my domain shows on the browser and not the Synology's. It's not ideal, but it works for now.

Thanks!

**Comment by xro** [comment]
use this in your web dir on your NAS
`RewriteEngine On
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://<<your domain goes here>>/$1 [R,L]
`

**Comment by MabuClou** [comment]
I have also a synology and for me it works. I have done this:

Login to your synology and start WebStation. Go to "Virtual Host" and add a new one. 
Make it "namebased" and use the name of your subdomain as Hostname.
Use the correct ports like you have already setup in your router. That's it.

Maybe you have also to manipulate the DNS settings for your subdomain. In my case i have set the A-Record to my static IP-Address and i had to delete the AAAA-Record. My Domain is hosted at 1&1. My be it is different at your provider.

Hope  these explanations can help.
