### ISSUE TITLE
Username/Password invalid for /opds

### ISSUE THREAD

**Issue by tfeiner** [rvolz/BicBucStriim#296]
If I login to https://serverName:8081/bbs (via form) everything works as expected. If I am already logged in there, I can also call https://serverName:8081/bbs/opds

When I am logged out and call https://serverName:8081/bbs/opds a basic auth form is opened, but my valid credentials do not work there.

Enviroment: QNAP TS253A

**Comment by rvolz** [comment]
How do you call .../opds? With which app? It is supposed to work with OPDS-capable ebook apps ...

**Comment by rvolz** [comment]
Anayway, if you are calling it from  a browser and don't get the OPDS XML back after you authenticated, then the app probably doesn't get the authorization headers. Take a look at the .htaccess file included.

**Comment by tfeiner** [comment]
I am calling it from a browser. If I login to /bbs before, /bbs/opds works well.
But if I call /bbs/opds, then my authentication fails.

Btw, I really like BBC, great work :)

**Comment by tfeiner** [comment]
I try to use OPDS from "Marvin", there I cannot load the catalogue

**Comment by rvolz** [comment]
The log confirms my suspicion. The app isn't getting authentication info. The way authentication is handled differs between normal login and OPDS access. An OPDS app has to sent the authentication headers with each access. Assuming you entered your login credentials in Marvin, Marvin does that too, I just tried.

If the credentials in Marvin are correct, then the only other possibilty I see currently, is the web server setup. The crucial line in .htaccess is this one

`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

You could try to delete or change it. I don't have experience with QNAP setups, sorry.

**Comment by tfeiner** [comment]
Now I installed a docker container with BicBucStriim and it works perfectly. Therefore it was the exotic Apache setup of QNAP. Thank you very much!
