### ISSUE TITLE
Download protection not available

### ISSUE THREAD

**Issue by xro** [rvolz/BicBucStriim#298]
I see on few screenshots that there is Download protection. Funny enough that option doesn't display in my Admin/Configuration section at all. How to enable it?

**Comment by rvolz** [comment]
The screenshot might be old, sorry for that. The download restrictions are now part of the user configuration, where you can filter the books by language/tag. It was meant for for families with kids primarily.

**Comment by xro** [comment]
What if you disable "Login required". How can you restrict downloads then?
I want my library to be publicly viewable and books be downloadable only for special password holders.
