### ISSUE TITLE
additional button for searching authors by letter

### ISSUE THREAD

**Issue by Habak1** [rvolz/BicBucStriim#302]
Hello,

if you click the button „authors“ you will see first the site with some authors starting with „a“. If you are looking for an authors with „m“ you have to push the „forward“-button serveral times.
By many authors it is exhausting. So an additional button between „backs and „forward“ shows all initial letters of all authors where you can choose for e.g. the „m“. 
Thanks 
Habak

**Comment by rvolz** [comment]
Yes, you are right, that is currently in implementation for version 2.0. It was already requested, a long time ago in #16 . Please follow that one for updates.
