### ISSUE TITLE
HTTP Error 500 on Synology NAS

### ISSUE THREAD

**Issue by glawesh42** [rvolz/BicBucStriim#303]
Hi,

I've downloaded the 1.2.0 version from GitHub and installed by dragged the unzipped folder to my www folder on a Synology.

I get an http error 500 when trying to access via myip/~user/bbs/index.php or myip/~user/bbs/installcheck.php

My NAS is on Apache 2.2 and PHP 5.6

Do you have an idea what I can do to fix the problem(s)?

Best regards,
Damien

**Comment by Floskelkoenig** [comment]
Hello, 
I just went through the same steps as you did but I got through without too much hazzle.
Here are some questions I stumbled upon while trying to make it work properly

- are personal websites enabled on your Synology?
- did you configure the PHP-profile? (activated the extensions gd / intl / mcrypt / pdo_sqlite / sqlite3)
- did you activate customize open_basedir and add the path to your ebook-folder to the open_basedir? (check if you have the colon : as separator - I didn't and it cost me dearly :D )
- have you tried to install it under the standard web-folder (volume1/web)

Cheers,
jan

**Comment by mycanaletto** [comment]
Hi,
DSM 6 + Apache 2.4 + PHP 5.7 and all extentions catived = same 500 et=error
Same result on IIS ...

**Comment by arejaytee** [comment]
I copied the php file into the phpMyAdmin folder and then it worked.

**Comment by D3laz** [comment]
which file?

**Comment by DorRobs** [comment]
the index.php-file in the web/phpmyadmin directory.

Note: Save the original file if it doesnt works.

**Comment by DorRobs** [comment]
I write it because at my fault it works.
