### ISSUE TITLE
Seesion Errror?

### ISSUE THREAD

**Issue by hollyofnone2** [rvolz/BicBucStriim#304]
hy
i use calibre 3.36.0 and BicBucStriim on my synology nas.
now and that was new i become following error:
Warning: Declaration of BicBucStriim\SegmentFactory::newInstance(BicBucStriim\Session $session, $name) should be compatible with Aura\Session\SegmentFactory::newInstance(Aura\Session\Session $session, $name) in /volume1/web/bbs/lib/BicBucStriim/segment_factory.php on line 16 Call Stack: 0.0002 364560 1. {main}() /volume1/web/bbs/index.php:0 0.0048 756464 2. require_once('/volume1/web/bbs/lib/BicBucStriim/login_middleware.php') /volume1/web/bbs/index.php:22 0.0061 757656 3. require_once('/volume1/web/bbs/lib/BicBucStriim/segment_factory.php') /volume1/web/bbs/lib/BicBucStriim/login_middleware.php:13 

andy ideas and tips?
regards 
holger

**Comment by rvolz** [comment]
That message means that your PHP installation was updated/is new and so you'll need to update the BicBucStriim version too.
