### ISSUE TITLE
Unnecessary number information

### ISSUE THREAD

**Issue by StephanKurz** [rvolz/BicBucStriim#305]
on the initial „newsest books list“ pick a book and then follow the link to the author you‘ll get a list of books of the autor. Whysoever every title starts with a leading number 1.0 and so on, even if it‘s not part of a series. To me this makes no sense. 
Choosing the author directly you‘ll get the same list, this time with no numbers. Why two diffrent views?

**Comment by rvolz** [comment]
I cannot reproduce this, sorry. I get a list without numbers ... Looking at the template: it shows the volume number only if there is something in the series field. You could try to clear the series field in Calibre. Maybe there are some invisible characters in there.
