### ISSUE TITLE
Can't filter languages for users on synology

### ISSUE THREAD

**Issue by pctv007** [rvolz/BicBucStriim#308]
Hi,
I created 2 users (fr/fr and en/en) and set the language accordingly to each of them.
Saved and logged in as each... No filtering occured: fr can see all books and en too.
Could there be a check case to chose to show or exclude languages, please ?
And do you have an idea why the filter by user doesn't work properly ?
I just updated to 1.5.0 and it's the same (was using 1.4.0)
Thanks

**Comment by rvolz** [comment]
I just checked (with 1.4.2) and the feature still worked for me, sorry. 

The language filter in the user configuration relies on Calibre's language info for the titles. Many older books didn't have language info and you had to set that explicitely during import. If there is no language id for a title the filter can't work. Could that be the problem?

**Comment by pctv007** [comment]
Hi, and thanks for your FAST answer.
Unfortunately, I don't think it's that, because I explicitely set the
language on all my books...
To tell you the truth, I was never able to filter languages with
BicBucStriim even after setting a language on ALL my books...
That's why it would be nice to have checkboxes to exclude or include
languages :-)
I'll try to implement it, but I don't know when I'll have the time to do it
:-)
Thanks anyway
Regards

Patrice


Le jeu. 21 févr. 2019 à 07:43, Rainer Volz <notifications@github.com> a
écrit :
