### ISSUE TITLE
files cbr and cbz

### ISSUE THREAD

**Issue by cricribibi** [rvolz/BicBucStriim#309]
Hello,
When I transfer a CBR or CBZ file in "Calibre". It is well integrated like the other books in the library. Then i transfer from my library to my nas. When I connect to my website bbs the book in CBR or CBZ is not displayed. The name of the author is well found but not related to the book.
Another test. I transfer my comic in EPUB in "calibre". I transfer everything on my nas. I will then go to my website bbs. The book appears well but in epub format and not in CBR or CBZ. "Calibre" does not convert from EPUB to CBR or CBZ.
How to have my comics on BicBucStriim?
thank you in advance,
Good night,
Christophe (France)

**Comment by rvolz** [comment]
BicBucStriim has no book format restrictions, it just displays what Calibre has to offer. I have a few CBZs in my library and I'll check if they are still offered for download, as they should.

In the meantime you could check if the comic files were copied correctly to the NAS, and if the Calibre author name is really the same as for the EPUB. Sometimes there are differences in spelling or sequence, especially for comics with their multiple "authors".

**Comment by cricribibi** [comment]
Hello,
Thank you for your answer, I bring some additional information.
The CBR or CBZ files are displayed in the "Caliber" library. The files are also in the corresponding folder on the hard disk.
By going to the BBS website, bbs does not offer cover in JPG while "caliber" the created, nor the sheet corresponding to the book and therefore no download.
While if I put the book in Epub no problem, BBS offers me the sheet of the book and download.
Caliber does its job well but I guess BBS does not consider the CBR or CBZ file as an EPUB.

**Comment by rvolz** [comment]
<img width="440" alt="CleanShot 2019-03-28 at 20 35 19@2x" src="https://user-images.githubusercontent.com/1092531/55187404-40c4db80-5199-11e9-80fd-ad88057e664e.png">

That picture is from my library, so the CBZ format is still recognized, not only EPUB. CBRs should appear there too. The problems you describe, including the missing pictures, seem to indicate, that the transfer to your NAS is incomplete. Could you try to use a different method to copy the Calibre library? Perhaps rsync?

You could also check if BBS has problems with the library, read [this page](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) if you want to do that.

**Comment by cricribibi** [comment]
After reinstalling with the user 'admin' I found my books in CBR and my library has grown a few pounds. I finally found the why !!
When I registered a user, I indicated the language in French. Except some books did not have the language concept of which my comics in CBR.
