### ISSUE TITLE
Earlier (long time ago) bbs libraries installed ok, recently copied bbs for additional library fails...

### ISSUE THREAD

**Issue by buis42** [rvolz/BicBucStriim#310]
Warning: require_once(lib/BicBucStriim/bbs_pdo.php): failed to open stream: No such file or directory in /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php on line 5 Fatal error: require_once(): Failed opening required 'lib/BicBucStriim/bbs_pdo.php' (include_path='.:./lib/BicBucStriim:./vendor') in /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php on line 5

**Comment by buis42** [comment]
appreciate advise.

**Comment by rvolz** [comment]
The message is pretty clear, it can't find (or load) the file bbs_pdo.php. Did you really copy everything?

Another possibility is that you are using an ancient BBS version on a system with a recent PHP version. That must be an ancient version, you are using, 1.2.x? If your system is recent updating to a newer version might help. The file bbs_pdo.php relied on PHPs PDO support and another third-party library. These parts changed with the PHP versions, and are probably not compatible anymore.

**Comment by buis42** [comment]
Thank you for prompt feedback!!

I do have BBS version 1.3.6-5, which is the latest release??
However i do have a mix of a few not updated packages.
The reason for this is that after i have done an update on the packages mentioned below - about 9 months ago however- i could not anymore login to the the installed bbs libraries....
After i deleted the new updated web station, php and apache server packages and re-installed the older versions , i could access the bbs libraries again...
I kept a copy of the original BBS library version and used this again, but i do not know if the installed libraries have been updated and the copy i have used now is perhaps an older version.
Could you let me know how to check the BBS version used please.

Hence i have now following packages with version numbers shown from  the package center:
Apache 2.2
PHP 5.6
Maria DB10
Maria DB5
Web Station (no version number is given)

What i could do is try to update all these package to the latest versions and check if this will solve the issue.
Appreciate your advise.

**Comment by rvolz** [comment]
The most recent version is 1.5.0, you can download it from [here](http://projekte.textmulch.de/bicbucstriim/downloads/). With that you should be able to update your Synology packages. You could update to PHP 7 for example, but should keep Apache 2.2 for BBS.

**Comment by buis42** [comment]
Thank you for sound advise, will do so and let you know the results.

Due to lack of background, appreciate advise on updating:
Can  the Web Station package from Synology be updated to the latest version (before or after PHP update?).
Do i have to delete PHP 5.6  (and other PHP versions) or can PHP versions co-exist? 
Do i have to delete the presently existing (older still working) BBS libraries and replace these also with copies op the new to be installed version?

Thanks in advance.

**Comment by buis42** [comment]
Meanwhile have seen that i could select PHP7 as default (for bbs) and actually leave PHP 5.6 installed aswell.
Got all green at install check (after selecting the required options for PHP 7 similar to 5.6) and successfully have the new additional library running.

Again many thanks to get me on the right track!
