### ISSUE TITLE
Calibre Library Check - failing for director with correct permissions and in open_basedir

### ISSUE THREAD

**Issue by jiversen** [rvolz/BicBucStriim#315]
Hi,
I am a brand new BBS user, and installed it today on a Synology NAS with latest OS, Apache 2.2, PHP 5.6, and BBS version 1.5.0 and 1.3.6 (from synology package). All of the Environment checks pass, but I am also having some trouble with the calibre library path. Perhaps I am overlooking something basic, though I did try to follow the install instructions carefully, and also tried your solutions from the related issues to a failed Calibre Library Check.

Similar to many others, my library is in /volume1/books/cl

Here are the relevant permissions and ownerships--it is very permissive (I tried also using user and/or group as http).
```
drwxrwxrwx+  1 root  root    16 Oct  6 20:04 books
drwxrwxrwx  1 root root 2086 Oct  6 15:48 cl
-rwxr-xr-x  1 root root 455680 Oct  6 15:48 metadata.db
```
And PHP setting `open_basedir`
```
/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1/books/cl
```
But this results in, despite the fact that the directory does exist, clearly:

![image](https://user-images.githubusercontent.com/160093/66284489-e6f64a00-e87c-11e9-9cc0-c191da4edd53.png)

_Yet_  if I try, e.g. for fun `/var/services/web/bbs` (which resolves to `/volume1/web/bbs`), just to check directory readability (of course it does not have a metadata.db) it works as it should. Indeed this works for any directory under `/var/services/web`

![image](https://user-images.githubusercontent.com/160093/66284826-ae577000-e87e-11e9-8a3b-c94138f8c537.png)

The relevant directory permissions are, to my eye, not meaningfully different to those for `books` and `cl`, above (if anything, they are more restrictive)

```
drwxrwxrwx+  1 root  root    72 Oct  6 20:46 web
drwxr-xr-x  1 http root  440 Dec 21  2015 bbs
```

To make things exactly parallel, though it should not matter, tried adding a symlink to my library within `/var/services`, analogous to `/var/services/web`, which is a symlink to` /volume1/web`:

```
lrwxrwxrwx   1 root root   17 Oct  6 21:21 cl -> /volume1/books/cl
lrwxrwxrwx+  1 root root   12 Oct  5 13:16 web -> /volume1/web
```
and, adding that also to the `open_basedir`:
 ```
/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/var/services/cl
```
This also failed.

Finally, all of the other 'lights' in the check are green, except for 
![image](https://user-images.githubusercontent.com/160093/66284987-77358e80-e87f-11e9-97b3-3ac459869cf2.png)

From all of this, I suppose I could move my library under the `web` directory, but I'd rather not do that if possible. There was another solution where someone had a previously working directory stop working and moving it to somewhere else helped, but that's not a satisfying answer to something that should work.

Thanks for any insight!

**Comment by rvolz** [comment]
The difference between `web` and `books` is probably that `web` is a shared folder (by default) and your `books` folder is not, or is it? My `books` folder is a shared folder (for syncing) and PHP has no problems accessing it. 

IIRC other discussions about directory issues, the problem started usually at the top of the hierarchy, and that  is `/volume1` not `/volume1/books`. And `/volume1` usually has restricted access, for good reasons. Creating a shared folder apparently changes the access rights.
