### ISSUE TITLE
calibre library migrated to volume 2 unrecognised?

### ISSUE THREAD

**Issue by anniemossity** [rvolz/BicBucStriim#317]
In the configuration page, "Calibre library path" is set to "/volume2/books/Calibre Library". The page is unable is unable to save resulting the the message "Error Loading Page". 

Due to the need for a restore, my entire system is now on volume 2 and the library on: "/volume2/books/Calibre Library". This is indeed the correct address for the Library and I do not get the message "The configured Calibre directory cannot be used. Is it really a Calibre directory? Is it readable? Does it exist?" 

Apologies for the dumb question, but am I missing something?

**Comment by rvolz** [comment]
Did you change the _open_basedir_ path when migrating? Without that, PHP can't touch the new directory. Besides that you could enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode), to see what causes the problem.
