### ISSUE TITLE
Unexpected surface

### ISSUE THREAD

**Issue by huber72** [rvolz/BicBucStriim#322]
Hi,

I'm Peter from Germany - please excuse my English, I'll do my very best...

Yesterday I installed BicBucStriim following the instructions I found on the web, installation has been made on a server (IONOS 1&1) where my website is hosted. Folder has been renamed to bbs, as suggested.
I then copied my ebooks (books are in single folders, alphabetically including the book cover = cover.jpg) incl the metadatadb to a folder called calibre, subfolder files, picked up the correct path to this folder from 1&1 and made the installation check - everything ist ok (green), just "Is Mcrypt enabled" is yellow (cause "No")

I then followed the instructions to enter my admin page followed by my page https://.....//bbs/index.php/

Now I see the surface as shown on the picture attached, no covers on main page and no horizontal lines/tabs as on the second pic - what's going wrong with this?

Thank you for any assistance (I,m not a technician, really)

Peter 
![bbs-121-recent](https://user-images.githubusercontent.com/60315804/73135096-e1e12480-403e-11ea-993b-d52d0d479c92.jpg)
![surface](https://user-images.githubusercontent.com/60315804/73135097-e1e12480-403e-11ea-8054-6f0eaa65bb7f.JPG)

**Comment by rvolz** [comment]
Hello Peter,

do the links work, can you navigate to different pages? You should verify that the **.htaccess** file does exist in your bbs folder (it is a hidden file, sometimes they are not transferred properly). And then your IONOS installation must allow  .htaccess files for your bbs folder. See here for further explanations https://www.ionos.de/digitalguide/hosting/hosting-technik/htaccess-tricks/

If the problems don't go away you could enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) to get detailed error information.

**Comment by huber72** [comment]
Hi - thanks for prompt answer...

Yes, all links work and I am able to navigate to different pages (only sometimes, cover appear)
Yes, .htaccess file exists within the bbs folder and
Yes: I switched the .htaccess file on the IONOS webspace/server to Code "705" (read, write, execute = rwx---r-x)

In fact, nothing changes

Than I followed your instructions to go to debug mode and changed the 2 lines within the index.php as follows:

# Init app and routes
$app = new \Slim\Slim(array(
    'view' => new \Slim\Views\Twig(),
    'mode' => 'production',
    #'mode' => 'debug',
    #'mode' => 'development',
));

- nothing happens, even log files do not appear

For the time being I'm running BicBucStriim 1.3.6 but started with 1.5.0

regards Peter

**Comment by rvolz** [comment]
Then you probably have access rights problems. Some folders must be readable publicly. The browser wants to read 

- CSS stylesheets from ...bbs/style
- CSS images from .../bbs/img
- Javascript from .../bbs/js

But apparently it cannot. You could check this for example with your browser by navigating to https://.../bbs/style/style.css. Something like that should appear:

```
body{padding-top:60px;padding-bottom:40px}#passwordform #pw_dlg_status{text-align:center;background-color:orange...
```

For debug-mode to work you'll need to change the code to

```php
#'mode' => 'production',
'mode' => 'debug',
```

**Comment by huber72** [comment]
Just checked the files mentioned above at IONOS Server and sitched them all to Code "705"

Using the browser navigation "https://.../bbs/style/style.css" the according message appears - so far: ok

Changed the 2 lines according to your instruction now received a large logfile

At least, nothing changed at the Website https://.....//bbs/index.php/.....

PS Are you German? Dann bitte auf Deutsch :-), danke

**Comment by huber72** [comment]
Hi,

just not to prove all single steps I decided to start with a fresh installation:

Downloaded BicBucStriim Vs 1.5.0 and put the content into the web root - renamed to bbs

On IONOS Hosting Server switched all folders and files to access code 777 - highest level

Compared the .../calibre/files folder on the host with the folder on my PC - all folders alphabetically sorted are on the host, all folders contain one *.epub file each and corresponding cover.jpg

Entered the website https://www.XXX/bbs/index.php/ login page with admin/admin (see pic) and entered calibre library path /kunden/homepages/.../calibre/files
anf got the following result - see pic02

Start page shows cover (sometimes) after a while not anymore - surface looks like pic03; hence, nothing changed from other installation


Question: The folder bbs/data/titles contain - after one hour - 171 jpg files instead of some thousends - does it take such a long time?

For debug mode I changed the lines
# Init app and routes
$app = new \Slim\Slim(array(
    'view' => new \Slim\Views\Twig(),
    #'mode' => 'production',
     'mode' => 'debug',
    #'mode' => 'development',

and got the result you mentioned above: body{padding-top:60px;padding-bottom:40px}#passwordform #pw_dlg_status{text-a........ No log files!

If there is really no solution, I need to cancel the whole installation as I have no ideas anymor

regards Peter
![bbs01](https://user-images.githubusercontent.com/60315804/73269440-20144a80-41dd-11ea-8e72-91adfec7e864.JPG)
![bbs02](https://user-images.githubusercontent.com/60315804/73269441-20144a80-41dd-11ea-9c2d-072bdfcd194a.JPG)
![bbs03](https://user-images.githubusercontent.com/60315804/73269443-20144a80-41dd-11ea-9f82-5af324fefb39.JPG)

**Comment by rvolz** [comment]
> Question: The folder bbs/data/titles contain - after one hour - 171 jpg files instead of some thousends - does it take such a long time?

Die thumbnails .../data/titles werden erst generiert, wenn sie wirklich benötigt/angezeigt werden, sonst nicht. Solange sie also keine neuen Seiten aufrufen, werden es nicht mehr.

> Start page shows cover (sometimes) after a while not anymore

Das ist Teil ihres Zugriffsrechte-Problems: Beim allerersten Zugriff wird das Bild erst erstellt und daher wohl angezeigt, bei den nächsten Zugriffen versucht das Programm die schon bestehende Datei aus .../data/titles zu laden, kann das aber wohl nicht. (Den Unterschied sehen sie an der URL des Bildes.)

> Entered the website https://www.XXX/bbs/index.php/

Die Webseite müsste bei der URL https://www.XXX/bbs/ erscheinen. Wenn nicht, haben sie Probleme mit der Auswertung von .htaccess.

Es tut mir leid, dass sie diese Probleme haben, aber ich kann nicht alle Umgebungen voraussehen. Da die Installationsprüfung durchläuft und die Anwendung im Prinzip funktioniert, ist es mir ein Rätsel, warum Bilder/CSS/Javascript nicht geladen werden. Ggf. fragen sie mal den IONOS Support.

**Comment by huber72** [comment]
Schade - ich sehe im Netz auch keine Lösungsansätze da eigentliche alle User BicBucStriim auf einer NAS installiert haben

Dann muss ich nach einer anderen Lösung suchen

Danke jedenfalls für die Unterstützung

Gruß Peter

**Comment by huber72** [comment]
Just for fun:

rufe ich die Seite https://www.XXX/bbs/templates/main.html auf, erscheint folgendes:

{% block headerlinks %}{% endblock %}
{% block leftpanel %}{% endblock %}

{{ page.title }}
{% if page.level == 1 and page.menu == 1 %} {{ page.glob.l10n.pagination_search }} {% endif %} {% if page.level == 1 and page.menu == 2 %} {{ page.glob.l10n.pagination_search }} {% endif %} {% if page.level == 1 and page.menu == 3 %} {{ page.glob.l10n.pagination_search }} {% endif %} {% if page.level == 1 and page.menu == 4 %} {{ page.glob.l10n.pagination_search }} {% endif %} {% if page.level == 1 and page.menu == 5 %} {{ page.glob.l10n.pagination_search }} {% endif %} {% if page.admin %} {{ page.glob.l10n.admin_short }} {% endif %} {% if page.auth %} {{page.glob.l10n.logout}} {% endif %}
{% if page.dialog==false %} {% include "navbar.html" %} {% endif %}
{% block content %}{% endblock %}
{% include "footer.html" %}
{% block rightpanel %}{% endblock %}

**Comment by huber72** [comment]
Moin,

ich lass ja noch nicht locker: Nochmals Version 1.5 installiert und mit 777 Rechten ausgestattet, Ordner umbenannt
Rufe ich jetzt meine Seite auf https://www.haselau.eu/bbs/admin/configuration/
erscheint - wie leider vorher auch - folgendes Bild
![Unbenannt](https://user-images.githubusercontent.com/60315804/73626739-52450280-464a-11ea-9e12-dd9b85330151.JPG)

Das nur zur Kenntnis und evtl Kommentar, bevor ich mal bei IONOS anrufe

Danke, Peter

**Comment by rvolz** [comment]
Das Bild bedeutet, dass die **.htaccess** Datei im bbs-Ordner nicht ausgewertet wurde. Das muss eingeschaltet werden, nach wie vor.

**Comment by huber72** [comment]
Moin,

zur letzten Sicherheit hier der Code:

<IfModule mod_rewrite.c>
    Options -MultiViews

	# Tell PHP that the mod_rewrite module is ENABLED.
    SetEnv HTTP_MOD_REWRITE On

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [QSA,L]
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

# protect database
<FilesMatch data.db>
    # Apache < 2.3
    <IfModule !mod_authz_core.c>
        Order allow,deny
        Deny from all
        Satisfy All
    </IfModule>

    # Apache ≥ 2.3
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
</FilesMatch>

# protect schema
<FilesMatch schema.sql>
    # Apache < 2.3
    <IfModule !mod_authz_core.c>
        Order allow,deny
        Deny from all
        Satisfy All
    </IfModule>

    # Apache ≥ 2.3
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
</FilesMatch>

Die Datei hat vollständige Berechtigung 777

**Comment by huber72** [comment]
Moin,

ich habe gerade ca 40 Minuten mit einem Mitarbeiter von IONOS 1&1 telefoniert, das Problem aber letztendlich nicht lösen können:

der erste Punkt war die .htaccess Datei, die im Root Verzeichnis des Webservers liegt und die .htaccess Datei im bbs-Ordner "unterwirft" - um das zu Testzwecken mal abzuschalten, wurde die .htaccess umbenannt - kein Erfolg

Der Mitarbeiter ist irritiert, dass in der installierten Version 1.5 (wie auch in den Versionen 1.3 und 1.4) ständig ein ...bbs/admin/configuration/ - also ein Ordner/Datei "admin" angesprochen wird, den es nicht gibt und daher auch nichts ausführen kann...
Nachdem ich feststellte, dass es in der Version 1.3 einen Order "admin" unter "Features" gibt, haben wir die Version 1.5 durch die Version 1.3 ersetzt - das ändert auch nichts: IONOS sagt mir dass in z.B. in Zeile 7 der Datei admin_configuration.html immer noch

<form action="{{page.rot}}/admin/configuration/" method="post" id="adminform">

steht - im Ordner "features/admin" aber keine configuration enthalten ist.

Die derzeitige und letzte Fehlermeldung der noch installierten 1.3 Version sagt "Error 404 - Not found", alle Berechigungen wurden wieder auf 777 gesetzt

**Comment by rvolz** [comment]
Es ist schon traurig, dass ein IONOS-Mitarbeiter nicht weiß, wie die Web-Anwendungen funktionieren, die seine Firma en masse anbietet. BicBucStriim funktioniert genau wie WordPress und andere PHP-Software.

Diese Zeile in der .htaccess 

```
 RewriteRule ^(.*)$ index.php [QSA,L]
```

teilt dem Webserver mit, dass er die Datei index.php, die im gleichen Ordner zu finden ist, aufrufen soll. index.php bekommt daraufhin als Argument die Aufruf-URL, also zB /admin/configuration, und liefert dann die entsprechende Seite zurück. Damit kommt die Anwendung ohne Unterordner aus, das war früher einmal.

Das heißt aber auch, dass die Anwendung ohne  .htacess nicht funktionieren kann. Allerdings kann die genaue Ausgestaltung der .htacess-Datei je nach Umgebung variieren. Bei manchen Nutzern funktionierte zum Beispiel

```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
```
statt
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]
```

Aber das muss man leider ausprobieren.

**Comment by huber72** [comment]
Änderung erbringt:

Multiple Choices
The document name you requested (/index.php) could not be found on this server. However, we found documents with names similar to the one you requested.

Available documents:

    /index.html (common basename)
