### ISSUE TITLE
Error Loading Page at login attemp; 500 error on POST

### ISSUE THREAD

**Issue by apiontek** [rvolz/BicBucStriim#323]
I moved a working instance of BBS from an intel amd64 / Ubuntu 18.04 container on one machine to an aarch64 / Ubuntu 19.10 container on another machine.

Now when I try to login at /login, on hitting the Login button I just get "Error Loading Page" and nothing else happens. I've archived my data & started fresh with a clean unzip of BBS, still getting the error just trying to do first time login.

In server logs, resources are loading fine, but when it hits `"POST /bbs/login/ HTTP/2.0"` the result is 500 error.

installcheck.php shows no errors, just yellow for Apache & URL rewriting, but I'm not using Apache, I'm on nginx.

**Comment by rvolz** [comment]
You could enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) to get a) detailed error messages in the browser and b) log files. If your nginx configuration worked with the previous instance it is probably something in the environment that changed.

**Comment by apiontek** [comment]
Thanks. Log file suggested a redis problem, because my php session handler is set to use redis, via a unix socket.

Turns out, when migrating, I forgot to do `adduser www-data redis` -- php session handling was broken altogether and I didn't know because I'd not thought to test it after migrating...

After adding www-data to the redis group and restarting, session handling, and BBS, started working again.

Thanks for the pointer to debug mode!
