### ISSUE TITLE
bbs relies on mcrypt that isn't supported anymore by PHP since 7.2

### ISSUE THREAD

**Issue by leolivier** [rvolz/BicBucStriim#326]
Hi, everything is in the title:
Could you replace mcrypt by libsodium which is officially supported in place since PHP7.2?

**Comment by rvolz** [comment]
Thanks for the hint, I did miss that. mcrypt was required by some libraries, I'll have to check them.

**Comment by rvolz** [comment]
The new version 2.0. (currently in alpha testing) requires PHP 7.4+ and uses libsodium. Thanks for the hint, again.
