### ISSUE TITLE
Change Calibre folder name

### ISSUE THREAD

**Issue by Thomas1005** [rvolz/BicBucStriim#328]
Hi,
does anybody know, how i can change the "Calibre" folder name. E.g. from Calibre to calibre ?
Can do it at the NAS (PHP and so on), but how i can change it at the configuration of BicBucStriim ?
Thanks
T.

**Comment by rvolz** [comment]
You mean the configured path to the Calibre library? BicBucStriim doesn't insist on a certain folder name for that.  Mine is "/volume1/books", for example.
