### ISSUE TITLE
Synology size drive limit

### ISSUE THREAD

**Issue by DoctorDri** [rvolz/BicBucStriim#329]
Long time ago I installed BBS in the root folder of my Synology 918+. It worked very well until now.

Unfortunately, BBS is eating all my root drive space (Synology limits it to 1GB). The directory /var/services/web/bbs/data/titles is 902M big.

As a consecuence, I can't update the NAS DSM system nor install new packages. I contacted Synology support and they recommended moving the folder somewhere else:

> thank you for your we can't make the space bigger it's partition that set to be like this.
if you don't wan to remove it  you have to move the files to other folder . or see with the settings of the packet if you can change the location of the database 
in order to access to the root file you have to connect in command line to your nas after you have to move to the folder /var/sevices/web and move this file 

I have two questions about this:

- To move BBS folder is possible? If I move it out of the /root/ drive space, would it work in, say, Volume2 where I have many TBs free?

- If not the directory itself, can BBS database be moved outside the root drive?

- What is causing such a big volume? Is it temporary or log files that I can delete? I have around 120.000 books in epub and MOBI format, which means around 250.000 files; maybe this is the issue, having a big library?

**Comment by rvolz** [comment]
The directory `.../data/title` contains thumbnail images for the books. In my library the file size of the thumbnails is between 7 and 50 KB. For 120.000 books this directory could get quite large, yes.

Ad-hoc you could simply delete all thumbnails. They will be regenerated automatically when needed. 

The BBS directory needs to be in the Synology `web` folder to work. I have no Volume2, so I don't know if that could be moved. The BBS database should be small, so moving it would make no sense.  However, you could move your library easily.

**Comment by DoctorDri** [comment]
Perfect, this worked. I deleted half of the thumbnails inside .../data/title and therefore DSM had drive space for updates again.

I guess there's no way to keep BBS in the Synology web folder but this specific thumbnails directory outside of it, right? Cover thumbnails are cool and I would like to be able to have them in BBS, but if this is not possible then I'll just delete the .../data/title folder contents periodically.

**Comment by rvolz** [comment]
Maybe you should look into creating a virtual host via WebStation. I just noticed that it is possible to specify a different document root there, maybe you could move BBS using that.

I haven't tried that myself though, just an idea ...

**Comment by DoctorDri** [comment]
Thanks for the idea. I looked into this but it seems that it's beyond my DSM knowledge. I may give it another try in the future and if so, report back with the results.
