### ISSUE TITLE
Revert to previous metadata.db

### ISSUE THREAD

**Issue by ebuddelm** [rvolz/BicBucStriim#330]
Hi, 
I have installed BicBucStriim on Synology and can get to my Calibre library fine. I maintain my calibre library on my pc and have created a synchronisation scheme with Cloudsync to my Synology server. If I modify the Calibre library by adding books with calibre on my PC the metadata database is synchronised along with the new books to the synology server. I checked the modification date and size on the Synology, I even checked the contents of the metadata.db on the synology using sqllite and can see the new books in there. 

However I do not see the new books in BicBucStriim. 
I tried reinstalling BicBucStriim and then I can see the new books for a short time but after a while (within an hour) I see the 'old' content again in BicBucStriim. It seems to me like there is some caching going on but I cannot find any place to check that. I did uncheck the PHP caching in Synology Web station but that has no effect. 

Is there some way to debug so I can see where BBS is getting it's information and hopefully where it is taking a turn to the 'wrong' directory or file?

I do know a lot about programming but are not very fluent in PHP.

**Comment by rvolz** [comment]
BicBucStriim uses the metadata db directly, as soon as that changes the new information/books should be visible. It uses the path entered in the configuration section to find the db. That path is stored in its own _data/data.db_. 

As long as that path doesn't change during synchronization everything should be ok. You could check that db to verify that the path is still the one you want. 

```sql
select * from config;
```
will produce something like 

```txt
1|db_version|3
2|calibre_dir|/volume1/books
...
```
You could also try to clear your browser cache before testing. The JavaScript code is old and sometimes the pages don't get refreshed properly.

**Comment by ebuddelm** [comment]
Thanks for the prompt answer. I see a perfect match of the data in the data/data.db file with the configuration I see in BBS. In my case /volume1/Calibre/CalibreNederlands. 
I cleared the cache, I even installed a different browser (both Edge and DuckDuckGo) to make sure that was not the problem. I still only see the new data only temporary. I even restarted the Synology to make sure there was no cache left. Nothing seems to bring the new data to the front permanently.
Any ideas where I can look next for strange things? Some debug log file?

**Comment by rvolz** [comment]
You could certainly activate [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) to see if strange error messages appear. However, I doubt that, titles appearing and disappearing again sounds very strange.

To check if that is a backend problem you could run a SQL query in metadata.db

1. when the new titles appear
2. when they disappeared

The query is the equivalent to the main screen "30 most recent books". I assume that the phenomenon is visible there too. 

```sql
select title from books order by timestamp desc limit 30;
```

Ideally the results of both queries should be identical, if they differ you are dealing with different versions of the database.

The only mechanism for _hiding_ titles from view -- although they are in the database -- is to define a _filter_ for a user. You could check that too. However, they should always work, not only sometimes.

**Comment by ebuddelm** [comment]
Thanks for the clue about filters. 
It turned out that when you set a language for a user an implicit filter is applied to display only the books that have that language attached in the metadata. I had not set the language for all books, including new ones, but had set the language for the user (admin also). It took me a while to associate the setting of a language in a user definition with a filter being applied. It only dawned on me after looking carefully through the log file that was created in debug mode, I saw then that the filter was being applied. I had not thought of setting a language for a user as being a filter.
Works like a charm now.
