### ISSUE TITLE
search select end then error

### ISSUE THREAD

**Issue by hollyofnone** [rvolz/BicBucStriim#331]
Ich suche na einem author, child... wähle ihne aus dannn kommt der fehler
Fatal error: Call to undefined method Calibre::authorSeries() in /volume1/web/bbs/index.php on line 1504 Call Stack: 0.0002 245304 1. {main}() /volume1/web/bbs/index.php:0 0.0343 1284640 2. Slim\Slim->run() /volume1/web/bbs/index.php:206 0.0352 1290264 3. Slim\Middleware\PrettyExceptions->call() /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php:1271 0.0352 1290432 4. CachingMiddleware->call() /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php:67 0.0375 1299464 5. OwnConfigMiddleware->call() /volume1/web/bbs/lib/BicBucStriim/caching_middleware.php:41 0.0437 1311896 6. LoginMiddleware->call() /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php:31 0.0438 1314304 7. CalibreConfigMiddleware->call() /volume1/web/bbs/lib/BicBucStriim/login_middleware.php:37 0.0452 1316008 8. Slim\Middleware\MethodOverride->call() /volume1/web/bbs/lib/BicBucStriim/calibre_config_middleware.php:50 0.0453 1316416 9. Slim\Middleware\Flash->call() /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/MethodOverride.php:92 0.0454 1316920 10. Slim\Slim->call() /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/Flash.php:85 0.0497 1348536 11. Slim\Route->dispatch() /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php:1326 0.0498 1349040 12. call_user_func_array:{/volume1/web/bbs/vendor/slim/slim/Slim/Route.php:462}() /volume1/web/bbs/vendor/slim/slim/Slim/Route.php:462 0.0498 1349592 13. authorDetailsSlice() /volume1/web/bbs/vendor/slim/slim/Slim/Route.php:462 

nee idee?
sind ca 200.000 Bücher drin!
vg
holger

**Comment by rvolz** [comment]
Nein, ```authorSeries``` ist schon Version 1.4.0 enthalten und hat bisher nie Probleme gemacht. Sind vielleicht Dateien kaputtgegangen oder Versionen vermischt worden?
