### ISSUE TITLE
Not only send to Kindle, but to other adresses too

### ISSUE THREAD

**Issue by smedest** [rvolz/BicBucStriim#335]
At the moment you can only send to a Kindle mail adres. It would be nice if it could allso be send to e.g. name@pbsync.com
In short: make it possible to send it to a variable domain.

**Comment by rvolz** [comment]
It's a long time since this was implemented, but it should be already possible to send to arbitrary mail addresses. The only Kindle-specific part is that Kindle-formats are preferred.

**Comment by rvolz** [comment]
Is sending books via mail still a feature? IIRC Amazon discourages sending books to Kindles. I wonder if it should be kept in V2.
