### ISSUE TITLE
bbs login working time

### ISSUE THREAD

**Issue by huber72** [rvolz/BicBucStriim#336]
Moin,

after the login to bbs as a user/guest the bbs website closes after several time, new login is necessary.

Is there any chance to enlarge the time to eg 2 hours or so?

Thanks Peter

**Comment by davkastheranger19** [comment]
The current index.php in version 1.5.0 has the lifetime of the login cookie set to 1 day in Production mode, 5 minutes in Development mode, and 1 Day if in Debug mode. Check your index.php and check which modes it's in. If it's in Production, then check your browser settings and see if it set to delete cookies on close. This would log you out.

**Comment by huber72** [comment]
Thanks for reply - times in all three modes - see above - are set in respective times 1day, 5 minutes, 1 day), but which version is running?

**Comment by davkastheranger19** [comment]
> Thanks for reply - times in all three modes - see above - are set in respective times 1day, 5 minutes, 1 day), but which version is running?
> 
> Browser is not closed during the day and - for the time being - runs 24/7

Then it's probably in production mode if you haven't changed it manually. I've started looking into this as the timer is not working for the 1-day cookie. I'll let you know if I was able to figure out why it's terminating the connection prior to the cookie expiration. I'm not a dev, but just a fellow user, so no promises.

**Comment by huber72** [comment]
thanks in advance

**Comment by rvolz** [comment]
@huber72 It could be that your problem is also affected by the PHP session timers as explained [here](https://github.com/rvolz/BicBucStriim/blob/master/docs/configuration.md#user-session). You could try to change them with a local [php.ini](https://github.com/rvolz/BicBucStriim/blob/master/public/php.ini) and play with  the values.
