### ISSUE TITLE
Authors: Fails to expand in search results

### ISSUE THREAD

**Issue by davkastheranger19** [rvolz/BicBucStriim#337]
Click the Magnafying glass in the top right corner and in the search window, Search for Lastname, firstname and hit enter.
The results will show X number of authors and when you click the plus to expand the author field, nothing shows up. 
Books, Tags, and Series all show correctly. 

When I search for just the first name or last name of the author, it appears and shows correctly.
This is happening on desktop Chrome and Android Chrome. The sample test of other browsers yields same results.
My install is showing green across the board when I run the config checker.
I'm running the 1.5.0 build
![Author](https://user-images.githubusercontent.com/56652223/87236431-a69d9c80-c3b7-11ea-856a-a200e17688dc.PNG)
![Title](https://user-images.githubusercontent.com/56652223/87236432-a69d9c80-c3b7-11ea-8fa3-fe0ea3578f40.PNG)
![Author2](https://user-images.githubusercontent.com/56652223/87255271-43fbdd80-c457-11ea-8c9b-dbf426d9d7ae.PNG)

**Comment by davkastheranger19** [comment]
I'm guessing that the search function isn't escaping the comma in the search query.

**Comment by rvolz** [comment]
Sorry for the late reply, but yes, the search is currently quite dumb. It just tries to find something that matches the search string.

**Comment by davkastheranger19** [comment]
> Sorry for the late reply, but yes, the search is currently quite dumb. It just tries to find something that matches the search string.

No problem. 
Any idea when the next major update/release is going to be for this software?

**Comment by rvolz** [comment]
A beta of v2 will probably appear end of September.
