### ISSUE TITLE
BicBucStriim - covers issues

### ISSUE THREAD

**Issue by xBot55** [rvolz/BicBucStriim#341]
BicBucStriim works fine but some book covers do not display even though they are ok in Calibre.
How to check that everything is correct ?
![BBS cover issues](https://user-images.githubusercontent.com/69253733/89429728-34ae3e00-d73e-11ea-9c04-940f98d5045f.jpg)

**Comment by rvolz** [comment]
Normally, that is a temporary problem. The generation of the thumbnail image took too long, for whatever reason. Most of the time, reloading the page a couple of times (the browser caches...) causes the image to appear.

To check if the thumbnail file exists:

1. Click on the title, add `/thumbnail` to the browser URL, which should then look like `http://<server>/bbs/titles/<number>/thumbnail`. The browser should then show the image. (This also triggers the generation of the thumbnail if it doesn't exist.)
2. Search the folder `data/thumbnails/titles`. The thumbnails files are named like `thumb_<number>.png`. The _number_ is the book number from the browser URL. If the file looks strange, delete it. It will be regenerated automatically when needed.

If all that fails, you could enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) and look for image generation errors.

**Comment by xBot55** [comment]
Hello,

 

Sorry I did not find the real problem before my ticket was closed (# 341).

My problem is that if Caliber generated a recording with an author name in uppercase, this book

will not appear in bbs.

 

For example :

bbs is looking for "JUSTIN CRONIN" while in Caliber registered under "Justin Cronin" ...

 

Trace from debug mode:

../..

Details

Type: ErrorException

Code: 2

Message: filesize(): stat failed for /volume1/Docs/Livres/Calibre Biblio/JUSTIN CRONIN/LA CITE DES MIROIRS (2596)/La Cite des Miroirs - Cronin, Justin.mobi

File: /volume1/web/bbs/index.php

Line: 1315

../..

 

if I change "JUSTIN CRONIN" to "Justin Cronin", it works but the others become inaccessible.

 

Do you have a solution? or what can I change?

 



 

De : Rainer Volz [mailto:notifications@github.com] 
Envoyé : jeudi 17 septembre 2020 08:41
À : rvolz/BicBucStriim
Cc : xBot55; Author
Objet : Re: [rvolz/BicBucStriim] BicBucStriim - covers issues (#341)

 

Closed #341 <https://github.com/rvolz/BicBucStriim/issues/341> .
