### ISSUE TITLE
Another cover issue

### ISSUE THREAD

**Issue by jobbanobba** [rvolz/BicBucStriim#342]
The cover thumbnails on the start page are not correctly displayed for the corresponding ebook. No problem, I assumed, and deleted the thumbnail images in the data/title folder to let bbs have them re-generated. That worked okay but if I refresh/reload the start page the images are not correct again! This happens on my Synology NAS DS218+ using apache 2.2 and 2.4 and PHP 5.6, Edge browser on Win 10 Pro. Latest bbs 1.4.1. 

Installcheck reports everything's okay. Checked my library in calibre: everything's okay, too.

Please help!

Werner

**Comment by jobbanobba** [comment]
upgraded to 1.5.0 but problem persists

**Comment by jobbanobba** [comment]
Example, see first row: "Alfie kehrt heim", wrong image:

![image](https://user-images.githubusercontent.com/71380881/93330336-edc46580-f81e-11ea-998b-e4d91302cb72.png)

book display, correct cover:

![image](https://user-images.githubusercontent.com/71380881/93330402-059be980-f81f-11ea-94ac-e4680896ddbd.png)

**Comment by jobbanobba** [comment]
Well, I tried now another browser (Chrome) and... voilà... bbs works just fine. So, the new Microsoft Edge browser can be blamed. Another buggy Microsoft piece of junk.

**Comment by rvolz** [comment]
The reason for the problem in Edge could also have been, that the _old_ image was still in the browser cache. Once it is in there it takes a while until it is deleted because BBS doesn't set aggressive timeouts -- book covers seldom change. Hitting the refresh button once or twice often solves the problem.
