### ISSUE TITLE
BBS not working with Calibre 5.x

### ISSUE THREAD

**Issue by docisdn** [rvolz/BicBucStriim#343]
Found out, that BicBucStriim dosen't work with the new Calibre Version higher than 4.3. I think it's because of the new python 3 in calibre version 5.x and higher.
Description of the error:  If you try to login, there's an error like you used a wrong password. In fact, it's the new version. I downgraded to calibre 4.3 and everythingworked fine again.

**Comment by rvolz** [comment]
The login information is independent of the Calibre data. So, the problem must be the result of something else. I haven't noticed problems with V5, I'm running 5.2 now.

If you want to find out more, enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode). That should give you detailed error messages.

**Comment by jandanielosc** [comment]
I have trouble with DB from Calibre 5.2. I cant log in. I have tried reinstall BBS, clean BBS database but troubles still continue. Calibre DB checked, no errors. I am using BBS on QNAP TS-228.
There is debug info from BBS:

Slim Application Error

The application could not run because of the following error:
Details
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 11 malformed database schema - near "WITHOUT": syntax error
File: /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre.php
Line: 123
Trace

#0 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre.php(123): PDO->prepare('SELECT * FROM b...')
#1 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre.php(440): Calibre->findPrepared('Book', 'SELECT * FROM b...', Array)
#2 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/index.php(1031): Calibre->last30Books('en', 30, Object(CalibreFilter))
#3 [internal function]: main()
#4 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('main', Array)
#5 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()
#6 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre_config_middleware.php(50): Slim\Middleware\MethodOverride->call()
#9 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/login_middleware.php(36): CalibreConfigMiddleware->call()
#10 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware->call()
#11 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#12 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#13 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#14 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/index.php(206): Slim\Slim->run()
#15 {main}

**Comment by rvolz** [comment]
According to the error your Calibre database seems to be damaged. The login was actually ok, but the app tried to load the Calibre data for the first page and failed. 

There are two points you could check:

1. The Calibre library is really damaged: use the menu "Library management/Check library" in Calibre to verify that
1. The Calibre DB was damaged when you copied it to your server/NAS/drive. You could verify that the sizes are equal.

**Comment by jandanielosc** [comment]
I have tried size and MD5 of database and the DB are equal. I have made new small DB without any user columns in Calibre  with a few ebooks. Still the same error. I am using version of BBS 1.4.1 installed through qpkg package from https://www.qnapclub.eu.  PHP on QNAP TS-228 is:
PHP 5.6.40 (cli) (built: Aug 25 2020 05:51:40)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
After a clean install of BBS, I can login into BBS as a admin with admin/admin logon credentials. After that, I can add DB and save config with green strip of DB functioning.

**Comment by rvolz** [comment]
I am glad to hear that it works now. I don't know the QNAP package, so I can't say anything about it.

There is no direct link between the BBS DB (data.db) with the user data and the Calibre DB. Once BBS can find and open the Calibre DB, everything should work. I tried my DB with Calibre 5.2 and different users, but there were no errors.

**Comment by jandanielosc** [comment]
unfortunately it doesn work. i cannot login again. Last thing, what i've done, was seting of path fo calibre DB, then click of save. Next login to BBS is impossible, I have getting message "error loading page".
Here is log file of BBS:
INFO - 2020-10-16T20:28:20+08:00 - BicBucStriim 1.4.1: Running in debug mode.
INFO - 2020-10-16T20:28:20+08:00 - multi user mode: login required
DEBUG - 2020-10-16T20:28:20+08:00 - own_config_middleware: config loaded
DEBUG - 2020-10-16T20:28:20+08:00 - login resource: /
DEBUG - 2020-10-16T20:28:20+08:00 - after resume: ANON
DEBUG - 2020-10-16T20:28:20+08:00 - login auth: NULL
DEBUG - 2020-10-16T20:28:20+08:00 - login: redirecting to login
DEBUG - 2020-10-16T20:28:20+08:00 - mkRootUrl: Using root url /bicbucstriim
INFO - 2020-10-16T20:28:20+08:00 - BicBucStriim 1.4.1: Running in debug mode.
DEBUG - 2020-10-16T20:28:20+08:00 - caching_middleware: caching disabled for /login/
INFO - 2020-10-16T20:28:20+08:00 - multi user mode: login required
DEBUG - 2020-10-16T20:28:20+08:00 - own_config_middleware: config loaded
DEBUG - 2020-10-16T20:28:20+08:00 - login resource: /login/
DEBUG - 2020-10-16T20:28:20+08:00 - after resume: ANON
DEBUG - 2020-10-16T20:28:20+08:00 - login auth: NULL
DEBUG - 2020-10-16T20:28:20+08:00 - login: login page authorized
DEBUG - 2020-10-16T20:28:20+08:00 - mkRootUrl: Using root url /bicbucstriim
INFO - 2020-10-16T20:28:28+08:00 - BicBucStriim 1.4.1: Running in debug mode.
DEBUG - 2020-10-16T20:28:28+08:00 - caching_middleware: caching disabled for /login/
INFO - 2020-10-16T20:28:28+08:00 - multi user mode: login required
DEBUG - 2020-10-16T20:28:28+08:00 - own_config_middleware: config loaded
DEBUG - 2020-10-16T20:28:28+08:00 - login resource: /login/
DEBUG - 2020-10-16T20:28:28+08:00 - after resume: ANON
DEBUG - 2020-10-16T20:28:28+08:00 - login auth: NULL
DEBUG - 2020-10-16T20:28:28+08:00 - login: login page authorized
DEBUG - 2020-10-16T20:28:28+08:00 - login: array (
  'username' => 'admin',
  'password' => 'admin',
  'login' => '',
)
DEBUG - 2020-10-16T20:28:28+08:00 - login success: VALID
INFO - 2020-10-16T20:28:28+08:00 - logged in user : admin
INFO - 2020-10-16T20:28:28+08:00 - BicBucStriim 1.4.1: Running in debug mode.
INFO - 2020-10-16T20:28:28+08:00 - multi user mode: login required
DEBUG - 2020-10-16T20:28:28+08:00 - own_config_middleware: config loaded
DEBUG - 2020-10-16T20:28:28+08:00 - login resource: /
DEBUG - 2020-10-16T20:28:28+08:00 - after resume: VALID
DEBUG - 2020-10-16T20:28:28+08:00 - getFilter: array (
  'id' => '1',
  'email' => NULL,
  'role' => '1',
  'languages' => NULL,
  'tags' => NULL,
)
DEBUG - 2020-10-16T20:28:28+08:00 - getFilter: Using language , tag 
ERROR - 2020-10-16T20:28:28+08:00 - exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 11 malformed database schema - near "WITHOUT": syntax error' in /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre.php:123
Stack trace:
#0 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre.php(123): PDO->prepare('SELECT * FROM b...')
#1 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre.php(440): Calibre->findPrepared('Book', 'SELECT * FROM b...', Array)
#2 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/index.php(1031): Calibre->last30Books('en', 30, Object(CalibreFilter))
#3 [internal function]: main()
#4 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('main', Array)
#5 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()
#6 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/calibre_config_middleware.php(50): Slim\Middleware\MethodOverride->call()
#9 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/login_middleware.php(36): CalibreConfigMiddleware->call()
#10 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware->call()
#11 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#12 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#13 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#14 /share/CACHEDEV1_DATA/.qpkg/BicBucStriim/www/index.php(206): Slim\Slim->run()
#15 {main}

**Comment by rvolz** [comment]
Sorry for that. But the log you provided states clearly:

* the login in the BBS data.db succeeded
* the selection of books in the calibre db failed

To verify that, you could open the Calibre's `metadata.db` on your NAS with sqlite3 and try the SELECT manually to check:
```SQL
SELECT * from books ORDER BY timestamp DESC LIMIT 30;
```
That is what BBS is trying to do. Does the same error appear?

**Comment by jandanielosc** [comment]
it works :-) i've got sqlite3 output from Calibre DB to terminal. But what is wrong with BBS? 
Calibre DB is stored in PUBLIC share on QNAP, where users/process can do R/W

**Comment by jandanielosc** [comment]
results of http://gandalf.danielci.local/bicbucstriim/installcheck.php 
All seems to be good
![Screenshot_1](https://user-images.githubusercontent.com/65282801/96264517-90aa0400-0fc4-11eb-97c4-396bf932b245.png)
![Screenshot_2](https://user-images.githubusercontent.com/65282801/96264520-91429a80-0fc4-11eb-9fd5-339c299a08bb.png)
![Screenshot_3](https://user-images.githubusercontent.com/65282801/96264525-9273c780-0fc4-11eb-8d6e-9afac48cbccf.png)

**Comment by rvolz** [comment]
The library check only tries to open the database, to see if it exists and can be accessed. Normally that is sufficient.

I searched for the error message in your log. The results seem to suggest, that either the database must be corrupt or the SQLite version is too old. There were issues with outdated SQLite versions on QNAP before (e.g. #146). Is that the same system that worked before?

I'll try to replicate this during the weekend.

**Comment by jandanielosc** [comment]
The Calibre DB is createdby Calibre 5.2 for testing purposes with BBS today. New created DB is created without any users columns and modifications as I have made in my main calibre DB, which worked till now. But I don't exactly know when is stopped works. There where one or two sytem updates for QNAP TS-228 in past months. I am thinking, that I didn't use BBS in summer. But now isn't working as you know. Calibre database is surelly uncorrupted (verified by size and checksums).
Version of sqlite on my system is:
sqlite3 --version
3.33.0 2020-08-14 13:23:32 fca8dc8b578f215a969cd899336378966156154710873e68b3d9ac5881b0ff3f
Downgrade of QNAP system is not good idea, If it is necessary, I have to miss the BBS has working.
Many thx. Good luck.

**Comment by jandanielosc** [comment]
There is version of sqlite3 module in apache/php
[/usr/local/apache/modules] # /usr/local/apache/bin/php --ri sqlite3
sqlite3
SQLite3 support => enabled
SQLite3 module version => 0.7-dev
SQLite Library => 3.8.10.2
Directive => Local Value => Master Value
sqlite3.extension_dir => no value => no value

**Comment by kaemelle** [comment]
Hello, 
got the same error when I replaced my library few days ago. The error message talked about the annotations_fts_stemmed_config :Message: SQLSTATE[HY000]: General error: 11 malformed database schema (annotations_fts_stemmed_config) - near "WITHOUT": syntax error
After many searches, I decided to edit my metadata.db file with DB Browser and delete all tables beginning by "annotation". I replaced it il my distant ebook folder. I little bit rough but surprisingly it worked...
Not the best solution but if it can help to find where the problem come from I will be glad

**Comment by jandanielosc** [comment]
Bingo. This is it!!!! After deleting the tables beginning with the annotation, the BBS working. What the hell are those tables doing?

**Comment by rvolz** [comment]
If you use the _Calibre Viewer_ to read ebooks, you can make notes and highlight sections. These tables store your notes. They are mostly empty in my case. The one that you mentioned contains only a version number:

<img width="488" alt="grafik" src="https://user-images.githubusercontent.com/1092531/96294775-31acb500-0fed-11eb-9713-19f65fb2169f.png">

**Comment by rvolz** [comment]
@kaemelle thx for the report. The annotation tables are not used by BicBucStriim, so it's strange that this problem appears in this context.

**Comment by rvolz** [comment]
I looked at the Calibre source code and discovered that its [most recent database upgrade](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/db/schema_upgrades.py) uses an SQLite extension, [FTS5](https://sqlite.org/fts5.html). That extension is used with the annotation tables that caused your troubles.

So, it could be that the SQLite libraries on your systems are outdated and don't contain this extension.
