### ISSUE TITLE
Reopen #341 ticket

### ISSUE THREAD

**Issue by xBot55** [rvolz/BicBucStriim#344]
Sorry I did not find the real problem before my ticket was closed (# 341).
My problem is that if Caliber generated a recording with an author name in uppercase, this book
will not appear in bbs. (the reverse is also true)

For example :
bbs is looking for "JUSTIN CRONIN" while in Caliber registered under "Justin Cronin" ...

Trace from debug mode:
../..
Details
Type: ErrorException
Code: 2
Message: filesize(): stat failed for /volume1/Docs/Livres/Calibre Biblio/JUSTIN CRONIN/LA CITE DES MIROIRS (2596)/La Cite des Miroirs - Cronin, Justin.mobi
File: /volume1/web/bbs/index.php
Line: 1315
../..

if I change "JUSTIN CRONIN" to "Justin Cronin", it works but the others become inaccessible.

Do you have a solution? or what can I change?
(see also my email)

**Comment by rvolz** [comment]
Are your sure your Calibre Database is properly synchronized? BBS reads all info from Calibre Database and then tries to construct the path to the book from that information. So, if BBS tries to access "JUSTIN CRONIN", then this uppercase name comes from the Calibre DB!

Specifically, this information comes from the table `books`, column `path` in Calibre's `metadata.db`:

<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/1092531/98082772-91261400-1e79-11eb-99de-e93e51b78df9.png">

Calibre constructs this `path` from the author name and book title. If the paths in your DB and the directories/files differ you should reorganize your Calibre library and re-synchronize it with your NAS.

One source of the problem could be that your Calibre installation is probably on a Windows system. Windows didn't care about uppercase/lowercase names, but your NAS does! So maybe a library reorganization helps to correct the paths.

**Comment by xBot55** [comment]
Hello,

 

Yes indeed, I agree with you, I think the problem is with Calibre and the way he creates directories.

My "Bbs" database is on a Synology NAS and BicBucStriim accesses it on this same NAS.

A priori it works very well except for this problem.

 

As I cannot modify the Calibre database by hand, I thought that "Bbs" could access the same

directory whether lowercase or uppercase.

If it doesn't and it comes from my NAS, never mind.

 

Thank you to make the effort to answer me.

 

If you know of an article or tutorial for accessing - and modifying - a Calibre database, maybe you can

send me the link.

 

Thank you

 

De : Rainer Volz [mailto:notifications@github.com] 
Envoyé : mercredi 4 novembre 2020 08:49
À : rvolz/BicBucStriim
Cc : xBot55; Author
Objet : Re: [rvolz/BicBucStriim] Reopen #341 ticket (#344)

 

Are your sure your Calibre Database is properly synchronized? BBS reads all info from Calibre Database and then tries to construct the path to the book from that information. So, if BBS tries to access "JUSTIN CRONIN", then this uppercase name comes from the Calibre DB!

Specifically, this information comes from the table books, column path in Calibre's metadata.db:

 <https://user-images.githubusercontent.com/1092531/98082772-91261400-1e79-11eb-99de-e93e51b78df9.png> 

Calibre constructs this path from the author name and book title. If the paths in your DB and the directories/files differ you should reorganize your Calibre library and re-synchronize it with your NAS.

One source of the problem could be that your Calibre installation is probably on a Windows system. Windows didn't care about uppercase/lowercase names, but your NAS does! So maybe a library reorganization helps to correct the paths.

**Comment by rvolz** [comment]
> As I cannot modify the Calibre database by hand, 

You could, if you installed SQLite in some form. But a simpler solution could be:

1. save the book files of that title somewhere
2. delete the title in Calibre
3. Add the title  again -- and be sure to enter the name/title information in the proper form

Another alternative could be to use the menu "Library maintenance > Check library" in Calibre. Perhaps that would repair the directory names.
