### ISSUE TITLE
Dependencies with nginx and php7.3

### ISSUE THREAD

**Issue by arman68** [rvolz/BicBucStriim#345]
The wiki seems to be a bite out of date, and I could not find an accurate and up to date list of dependencies needed to install bbs on nginx with php 7.3. After a bit of trial and errors, I think the following should be sufficient:

```
# install nginx and sqlite3
sudo apt install nginx sqlite3

# install php 7.3 with all dependencies required for BicBucStriim
sudo apt install php7.3 php7.3-common php7.3-fpm php7.3-sqlite3 php7.3-gd php7.3-intl php7.3-xml php7.3-mbstring php7.3-json
```
Notes:
php.3-xml is not listed in the old instructions for php5, but it is needed.
php7.3-mbstring is needed for the search
php7.3-fpm should be used for nginx instead of php7.3-cgi which is meant for apache

This works well installed on a raspberry pi, with rapbian buster, and using the latest version of Calibre 5.

Please confirm this is correct, and if so, it could be added to the installation wiki.

**Comment by rvolz** [comment]
If these packages work for you, I'm happy to change the wiki accordingly. Thank you for working this out.

I haven't checked the alternative installations in a while,  they were meant as examples.

**Comment by rvolz** [comment]
Due to #350 I'll create Dockerfiles with all dependencies for Apache and Nginx. Check branch  [BicBucStriim-350](https://github.com/rvolz/BicBucStriim/tree/BicBucStriim-350) for updates.

**Comment by rvolz** [comment]
I checked now with PHP 7.2 and 7.4. I had to add the PHP modules `php...-pdo` and `php...-zip` and `php...-iconv` to your selection (based on Alpine and Synology). But I guess that list depends on the defaults each distribution provides for PHP.
