### ISSUE TITLE
cant log in with calibre 5.x on qnap nas

### ISSUE THREAD

**Issue by docisdn** [rvolz/BicBucStriim#356]
as said,bicbucstriim doesnent work with calibre version 5.x on my qnap nas
any suggestions?

Thanks for your help

**Comment by rvolz** [comment]
What kind of suggestions are you looking for? 

If you need a workaround: you could write a small sql script that deletes the offending tables from your metadata.db each time you sync your library to your NAS. As @kaemelle mentioned in https://github.com/rvolz/BicBucStriim/issues/343#issuecomment-710213568 the app worked after that.

As far as I can see from the issues in this repo QNAP seems to be slow in updating SQLite, so it may take a while to get a version that works out of the box. I don't know if there are any QNAP repos with community or pre-release sw, maybe asking in their user forums could help there, https://forum.qnap.com

**Comment by docisdn** [comment]
Vielen Dank für die schnelle Rückmeldung
Ich werde einfach auf das SQL Update von Qnap warten
Frohe Weihnachten wünsche ich

By the way: bicbucstriim ist großartig 
Vielen Dank für die Arbeit, die da drin steckt

Mit freundlichen Grüßen
A. Alpen

Von meinem iPhone gesendet

**Comment by rvolz** [comment]
:-)
