### ISSUE TITLE
Update Calibre tags or set status=Read

### ISSUE THREAD

**Issue by ReneOverkleeft** [rvolz/BicBucStriim#357]
Hi,
Feature request. 
I would like to update my book tags from BBS. 
This way I can set my book to status Read without opening the Calibre program. 

Thanks

**Comment by rvolz** [comment]
Technically that would be possible, but the principle of this app is to leave Calibre's data alone -- only read it, never modify it. Everything else would add even more dependencies. Sorry.

**Comment by rvolz** [comment]
However, if you or someone would like to implement external services to modify Calibre's data, we could add a possibility to call these services and pass them the book id etc.
