### ISSUE TITLE
BBS on new Synology NAS - Autoload.php error

### ISSUE THREAD

**Issue by DoctorDri** [rvolz/BicBucStriim#359]
Hi,

I had BBS working perfectly on a DS918+, but I recently purchased a new DS920+ for a different location, and I encountered an error while trying to make BBS work:

> Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /volume1/web/bbs/index.php on line 10 Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/pear') in /volume1/web/bbs/index.php on line 10

On Synology's DSM I installed:

- Web Station
- PHP 5.6, 7.0 and 7.4
- Apache 2.2 and 2.4
- BBS Master in volume1/BBS

Not sure what's missing or why the error come up.

**Comment by rvolz** [comment]
Does _bbs master_ mean, you simply cloned the Github repository? Then the solution would be simple: that is no longer possible. The *vendor* packages are no longer included in the repo, that is why there is no `autoload.php` file.

For the moment you should download one of the installation archives.

**Comment by DoctorDri** [comment]
Thank you, this solved it. Very easy fix indeed.
