### ISSUE TITLE
Another "Error loading page"

### ISSUE THREAD

**Issue by ulpedi** [rvolz/BicBucStriim#360]
Installation on QNAP Nas TS219P

After installation and first login as admin, I have successfully saved the calibre-path.

After logout, a new login is no longer possible (Error loading page).

Calling installckeck.php showed no errors (everything green except for "PHP module intl" = yellow).
Also the calibre path check

The debug mode brought the following result:
"
Slim application error

The application could not run because of the following error:
Details
Type: PDOException
Code: HY000
Message: SQLSTATE [HY000]: General error: 11 malformed database schema - near "WITHOUT": syntax error
File: /share/MD0_DATA/Qweb/hugo/lib/BicBucStriim/calibre.php
Line: 123
"
Is there any help?

**Comment by rvolz** [comment]
That is probably the same issue as in #343: you are using Calibre 5.x and your QNAP has an old  SQLite version that cannot handle the new Calibre tables. BicBucStriim works because it itself doesn't use these, but as soon as it tries to access the Calibre database it gets errors.

**Comment by ulpedi** [comment]
Thanks for your answer!
OK, here is no real solution.
Now i got 2 metadata.db: One original and one without "annotations".
Depending on the use (Calibre or bbs) I put one as "in use"

Schade...
