### ISSUE TITLE
BBS on Asustor 3.5.3.RBH1 not starting

### ISSUE THREAD

**Issue by Ivanuskask** [rvolz/BicBucStriim#361]
Hi, I installed via Appcentral on AS-304T BBS 1.3.7. When i click on it, web browser opens but there is a note: web is not reachable. How to solve this? Thanks. Ivan

**Comment by rvolz** [comment]
Hm, a version 1.3.7 was never published between 1.3.6 and 1.4.0, so your version be something custom. Maybe you could ask the packager about it? 1.3 is also old (2015). You should look for version 1.5.

The error message doesn't tell me anything, it probably doesn't come from the app. Additionally, you could try to enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode).

**Comment by Ivanuskask** [comment]
Hi, thanks for info. I had to enable secured web server in Asustor ADM - Services - Web Server.
