### ISSUE TITLE
Can non-english character files be downloaded?

### ISSUE THREAD

**Issue by babonya** [rvolz/BicBucStriim#363]
Hi!

Thanks for making and updating BicBucStriim. This is one most reason to run NAS for me. :)

I am Korean, and it's definitely not a English character language.

Most of my book titles are written in Korean, but BicBucStriim allows them to be download as English-converted titles.

"Convert non-English characters to English equivalents" is uncheckable option for Saving books to disk preference.
If it is unchecked, I can save book files with Korean title.

I tried to find same option on BicBucStriim 1.5.0 but failed.

If it is not so difficult to download files in non-English character, could you add the option for next version, please?

**Comment by rvolz** [comment]
I have never used the "Convert non-English characters to English equivalents" option, in fact, I didn't know about it until now. Thanks for the hint.

If I understand correctly you would like the download file name to be in the non-ascii form?

**Comment by babonya** [comment]
Yes, exactly!

**Comment by rvolz** [comment]
Ok, I'll check if that original file name is preserved somewhere.
