### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by pascal-louis** [rvolz/BicBucStriim#366]
Bonjour,
Pour optimiser le fonctionnement de mes sites WordPress, je dois passer le PHP 7.3 en 7.4.
Or, BBS (version 1.5 installée il y a plus d'un an) est également présente sur ce même serveur avec la version 7.3.
Si je modifie PHP en 7.4, impossible de se connecter en administrateur ou en membre du site...
Les dernières modifications apportées à cette version 1.5 peuvent t'elles permettre de résoudre de problème si je retélécharge et réinstalle la dernière mouture de BBS 1.5?
Cordialement
Pascal

Hello,
To optimize the functioning of my WordPress sites, I have to upgrade the PHP 7.3 to 7.4.
However, BBS (version 1.5 installed more than one year ago) is also present on this same server with version 7.3.
If I modify PHP in 7.4, it is impossible to connect as administrator or as member of the site...
Can the last modifications made to this version 1.5 allow to solve this problem if I download and reinstall the last version of BBS 1.5?
Sincerely
Pascal

Translated with www.DeepL.com/Translator (free version)

**Comment by rvolz** [comment]
Yes, you are right: I forgot to publish the workaround for PHP 7.4. I now created a new version with some modifications for PHP 7.4. You can download it from https://projekte.textmulch.de/bicbucstriim/downloads/BicBucStriim-1.5.1.zip
Hope this helps.

**Comment by pascal-louis** [comment]
Bonsoir,

Merci beaucoup.
Juste une question pour la mise à jour, comment ne pas perdre les utilisateurs enregistrés ?
Cordialement
Pascal
..................................
Good evening,

Thanks a lot.
Just a question for the update, how not to lose the registered users?
Sincerely
Pascal

**Comment by rvolz** [comment]
Simply save the existing `data` directory and overwrite the `data` directory included in the installation archive with it. Then you will keep all users and the existing thumbnails.

If you only want the users, save and overwrite only the file `data/data.db`.

**Comment by pascal-louis** [comment]
Bonjour,

J'ai bien mis à jour vers la version 1.5.1, mais lors du passage en PHP 7.4, toujours ce message : "error page loading".
Au contrôle "installcheck" ; tout est en vert à l'exception de mcrypt.
Malheureusement, cette option n'est pas présente dans les options de la version 7.4 de mon Cpanel...

Hello,

I updated to version 1.5.1, but when I switch to PHP 7.4, I still get this message : "error page loading".
At the "installcheck" control, everything is in green except mcrypt.
Unfortunately, this option is not present in the options of version 7.4 of my Cpanel...

**Comment by rvolz** [comment]
_mcrypt_ isn't required in 7.4, instead you probably need sodium/libsodium.

If that doesn't help, please turn on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode), and look for the underlying error message in the log file.

**Comment by pascal-louis** [comment]
Bonjour,

Suite à vos conseils et le lien "debug mode", je suis allé voir les lignes à modifier, j'ai constaté que le mode était mis par défaut en "development".
J'ai donc remis le mode en "production" et activé sur PHP 7.4 "sodium"
Et pour le moment, pas de souci de connexion en admin ou pour les membres inscrits...

Merci pour vos suggestion et la qualité de votre application

PS : En français tags se dit "étiquettes" ou dans le cas d'ouvrages littéraires : "Genres", est-il possible de pouvoir modifier dans la barre de navigation (en haut de l'accueil) Tags en Genres par exemple

Cordialement

Pascal

Hello,

Following your advice and the link "debug mode", I went to see the lines to modify, I found that the mode was set by default in "development".
So I put the mode in "production" and activated on PHP 7.4 "sodium".
And for the moment, no problem of connection in admin or for the registered members...

Thank you for your suggestions and the quality of your application

PS: In French tags is said "étiquettes" or in the case of literary works: "Genres", is it possible to change in the navigation bar (top of the home page) Tags in Genres for example

Sincerely

Pascal

Translated with www.DeepL.com/Translator (free version)

**Comment by rvolz** [comment]
Oops, I did forget to change the mode back to production, sorry for that. 

As for the translations, the general process is:

- forking the project in Github
- updating the translations in file `assets/l10n/messages.yml`
- creating a pull request so that I can check and merge the changes

**Comment by rvolz** [comment]
PS: if you need the translation change urgently, just edit the file `lib/BicBucStriim/langs.php`. The French translations are in the section starting with `$langfr = {`

**Comment by pascal-louis** [comment]
Je vais voir en ce qui concerne le "forking", mais évidemment mes propositions devraient être validées par d'autres francophones...
J'ai tout de même modifié à titre expérimental la section évoquée les Tag, Tags et taggués de la langue française par "genre, genres et dont le genre est".
J'ai bien sûr sauvegardé le fichier php original.

Autre sujet et je ne vous embête plus, la possibilité, à terme, s'agissant du moteur de recherche de pouvoir effectuer des requêtes sur les mots présentant des accents (que l'on ait ou non indiqué lévêque ou leveque)...
Souci des accents en langue française ou encore dans d'autres langues comme l'espagnol par exemple)

I'll see about forking, but obviously my proposals should be validated by other French speakers...
I have modified as an experiment the section mentioned the Tag, Tags and taggués of the French language by "genre, genres and whose genre is".
I have of course saved the original php file.

Another subject and I don't bother you anymore, the possibility, in the long run, for the search engine to be able to make queries on words with accents (whether or not one has indicated lévêque or leveque)...
Concern about accents in French language or in other languages like Spanish for example)

Translated with www.DeepL.com/Translator (free version)

**Comment by rvolz** [comment]
Thanks for looking into the official process. I'm trying to reduce my workload, since there isn't much time available.

No problem, the unicode (accented characters) search is already implemented, #346. As soon as I have figured out the CSS, you can try it out.
