### ISSUE TITLE
Pictures & ver 1.5.1

### ISSUE THREAD

**Issue by pascal-louis** [rvolz/BicBucStriim#367]
Bonjour,

Depuis la mise à jour en 1.5.1 et si tout est OK pour le PHP 7.4, deux  petits soucis 
Dans la précédente version, lors de l'affichage sur smartphone, l'ouverture d'un livre adaptait le format de l'image (responsive), maintenant ce n'est plus le cas
Auparavant, sur PC, le texte apparaissait en regard de l'image

Cordialement

Pascal

Hello,

Since the update to 1.5.1 and if everything is OK for PHP 7.4, two small issues 
In the previous version, when displaying a book on a smartphone, the opening of the book adapted the image format (responsive), now it is not the case anymore
Previously, on PC, the text appeared next to the image

Sincerely

Pascal

**Comment by rvolz** [comment]
You are right, the packaging script changed the location of the CSS file and so it could not be loaded. I'll publish a new version today.

**Comment by rvolz** [comment]
This version fixes the style problems: https://projekte.textmulch.de/bicbucstriim/downloads/BicBucStriim-1.5.2.zip

**Comment by pascal-louis** [comment]
Bonsoir,
Juste pour signaler qu'il y a beaucoup de fichiers en double à l'intérieur du ZIP
Pascal

Good evening,
Just to point out that there are many duplicate files inside the ZIP
Pascal

**Comment by pascal-louis** [comment]
Bonjour,
La version 1.5.2 est opérationnel, la mise à jour a pu être effectuée après avoir recompressé les dossiers et fichiers et transféré sur mon nouveau domaine.
J'ai remplacé le fichier db par celui de l'ancien domaine en modifiant seulement dans db, via DB Browser for SQLite l'emplacement de calibre (calibre_dir)
Merci

Hello,
The version 1.5.2 is operational, the update could be done after having recompressed the folders and files and transferred to my new domain.
I replaced the db file by the one of the old domain by modifying only in db, via DB Browser for SQLite the location of calibre (calibre_dir)
Thanks

**Comment by rvolz** [comment]
Good to hear. Thank you for testing the update. I guess I can publish it now
