### ISSUE TITLE
DSM 7 and bicbumstrimm

### ISSUE THREAD

**Issue by johnnyisgoed** [rvolz/BicBucStriim#370]
Hi there
Is there already a solution or update to let bbs work with dsm 7
Thx johnny

**Comment by rvolz** [comment]
What problems are there? (My NAS is too old and cannot update to DSM7.)

**Comment by johnnyisgoed** [comment]
It say invalid file system contact developer

**Comment by rvolz** [comment]
That doesn't tell me anything. Is that an error during installation, or during runtime?

What version are you using? If it is the Synology package from https://synocommunity.com/ you should ask them to upgrade the package.

If not, you could enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) and check for the real error.

**Comment by surf33** [comment]
Hi, 
With the new DSM 7 and a fresh intall of the last version of BBS : 1.5.3, I have this error "Parse error: syntax error, unexpected ':', expecting '{' in /volume1/web/bbs/vendor/symfony/polyfill-php80/bootstrap.php on line 23 "

I have tried to enable the debug mode in the index.php but the same error still appears
Regards,

**Comment by surf33** [comment]
Solved : it was a problem of good configuration of PHP 7.4 (a new package in DSM) to add the good libraries.

**Comment by jpenguin** [comment]
> Solved : it was a problem of good configuration of PHP 7.4 (a new package in DSM) to add the good libraries.

Could you please explain?  What did you install.change? I'm having the same issue
