### ISSUE TITLE
books containing .rtf file not listed

### ISSUE THREAD

**Issue by Joduai** [rvolz/BicBucStriim#372]
After browsing couple book series and authors I noticed some books were missing.
The files were in place, searching for a certain book series showed the amount of books but didn't show any entries when clicking on it.
I discovered that all books containing rtf files have problems with being listed and displayed.
Adding proper mimetype and extension for rtf  in calibre.php and utilities.php had no effect.
Log file doesn't contain anything useful.
Currently on php. 7.3.13 as on 7.4.x and 8.0.7 BSS doesn't work at all.

Is there any way to see the books containing rtf file?

**Comment by rvolz** [comment]
As for running on 7.4+: you'll need version 1.5.3 for that. It includes workarounds for PHP 7.4 that seem to work for most people.  http://projekte.textmulch.de/bicbucstriim/downloads/

Concerning the RTF: BBS should take every format that Calibre offers and just list it. I'll check that

**Comment by Joduai** [comment]
I started right away with bbs 1.5.3
I'm checking currently what was going on  when I switched from php7.3 to 7.4(.16) and why it didn't work on 7.4 (sodium enabled)
Patience is the virtue - as always. It seems that apache webserver on my webhosting needed a bit more time to reload caches, couple minutes were too few. Now it works fine.

I will try to find out what is going on with books containing rtf, maybe some meaningful  error will pop out. I need to enable error reporting firstly. Maybe you implemented in source code some useful functions, just like there are production/development/debug modes.
Apache logs does not contain any info, thus I assume you disabled error reporting completely to log all errors in /data/*.log

Btw, I checked also how bbs works on  php 8 (got v8.0.7)
startpage and series show lists without problems, rest pages along with book details throws errors in template.
Settings pages also do not show any content.
Example of book details errors below:

```
Fatal error  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, Slim\Middleware\Flash given in /public_html/ebook/vendor/twig/twig/lib/Twig/Template.php:407
Stack trace:
#0 /public_html/ebook/vendor/twig/twig/lib/Twig/Environment.php(331) : eval()'d code(52): Twig_Template-&gt;getAttribute(Object(Slim\Middleware\Flash), 'error')
#1 /public_html/ebook/vendor/twig/twig/lib/Twig/Template.php(144): __TwigTemplate_51673a7795113b36e586cf05362d30dbb19b683b20aee441ceedef0ae9955806-&gt;block_content(Array, Array)
#2 /public_html/ebook/vendor/twig/twig/lib/Twig/Environment.php(331) : eval()'d code(181): Twig_Template-&gt;displayBlock('content', Array, Array)
#3 /public_html/ebook/vendor/twig/twig/lib/Twig/Template.php(279): __TwigTemplate_1f9587831e594ad2ffaa6c0478aef7506395433069399c3286662840aeac15ce-&gt;doDisplay(Array, Array)
#4 /public_html/ebook/vendor/twig/twig/lib/Twig/Template.php(253): Twig_Template-&gt;displayWithErrorHandling(Array, Array)
#5 /public_html/ebook/vendor/twig/twig/lib/Twig/Environment.php(331) : eval()'d code(25): Twig_Template-&gt;display(Array, Array)
#6 /public_html/ebook/vendor/twig/twig/lib/Twig/Template.php(279): __TwigTemplate_51673a7795113b36e586cf05362d30dbb19b683b20aee441ceedef0ae9955806-&gt;doDisplay(Array, Array)
#7 /public_html/ebook/vendor/twig/twig/lib/Twig/Template.php(253): Twig_Template-&gt;displayWithErrorHandling(Array, Array)
#8 /public_html/ebook/vendor/twig/twig/lib/Twig/Template.php(264): Twig_Template-&gt;display(Array)
#9 /public_html/ebook/vendor/slim/views/Slim/Views/Twig.php(91): Twig_Template-&gt;render(Array)
#10 /public_html/ebook/vendor/slim/slim/Slim/View.php(255): Slim\Views\Twig-&gt;render('title_detail.ht...', Array)
#11 /public_html/ebook/vendor/slim/slim/Slim/View.php(243): Slim\View-&gt;fetch('title_detail.ht...', NULL)
#12 /public_html/ebook/vendor/slim/slim/Slim/Slim.php(757): Slim\View-&gt;display('title_detail.ht...')
#13 /public_html/ebook/index.php(1185): Slim\Slim-&gt;render('title_detail.ht...', Array)
#14 [internal function]: title('777')
#15 /public_html/ebook/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('title', Array)
#16 /public_html/ebook/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route-&gt;dispatch()
#17 /public_html/ebook/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim-&gt;call()
#18 /public_html/ebook/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash-&gt;call()
#19 /public_html/ebook/lib/BicBucStriim/calibre_config_middleware.php(50): Slim\Middleware\MethodOverride-&gt;call()
#20 /public_html/ebook/lib/BicBucStriim/login_middleware.php(36): CalibreConfigMiddleware-&gt;call()
#21 /public_html/ebook/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware-&gt;call()
#22 /public_html/ebook/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware-&gt;call()
#23 /public_html/ebook/vendor/slim/slim/Slim/Slim.php(1271): CachingMiddleware-&gt;call()
#24 /public_html/ebook/index.php(210): Slim\Slim-&gt;run()
#25 {main}
  thrown in <b>/public_html/ebook/vendor/twig/twig/lib/Twig/Template.php</b> on line <b>407</b>
```

**Comment by rvolz** [comment]
I just tested RTF files with two scenarios with (1.4.1 and 1.5.3):
- RTF alone
- RTF and PDF

In both cases the files were visible and could be downloaded, no problems.  Sorry.

**Comment by rvolz** [comment]
Thanks for testing it with PHP8. They changed too much there, and the V1 libraries are too old, so PHP8 will only be supported by BBS V2. I would recommend to use with PHP7 with BBS V1.

**Comment by rvolz** [comment]
Since you seem to use a webhosting server: it could be that the webserver has restrictions for the RTF format. It is a word-processing format, not a real publication format ...

**Comment by Joduai** [comment]
After you mentioned that you checked rtf handling under 1.4.1 I tried this version.
Books containing rtfs work on 1.4.1 on my webhosting (had to revert to php 7.3)
Damn, have no idea at this point where to look at.
I will try with 1.5.0 and stay with this version if everything works on my webhost.
I would be fine even with 1.4, but thumbs have problems showing up which is a bit different than mentioned in my first, earlier thread.

I will let you know.
Btw, that's a great peace of software. I'm looking forward for v2 version.
Wanted to try it out, but latest changes were made in the same time as latest v1.5 release.
Is there a downloadable archive with current state of v2 or should i get it right from github's repository?
I could give it a try.

**Comment by rvolz** [comment]
I still have to work on the GUI/CSS for V2. It's too early to distribute it, the first alpha version was just for some backend testing ...

**Comment by Joduai** [comment]
K, no problemo for me.
Tried out raw version of 1.5.0 and books with rtf show up and works just like in 1.4.1
I will set this ip, and make some small changes to get the thumbs and covers working and stay with this version.
I feel a bit stupid for wasting your time to check this problem. I assumed latest version will work flawlessly out of box ;)
