### ISSUE TITLE
500 error Nginx from Pi4 to Synology with DSM7

### ISSUE THREAD

**Issue by fdfytr** [rvolz/BicBucStriim#373]
i successfully mounted nas web folder to pi4 and put a root on client address
ngnix running without errors...
root is to nas web folder (via client nfs directory)
url redirected
php 7.3 with modules installed

when i check /bbs folder on nas i get 500 error now...
data folder chmoded per instructions...

would appreciate an advice. thnx

**Comment by rvolz** [comment]
The normal approach is to place the app AND the library on  the same device, so either on the Synology or the Pi. And all the instructions on the website are meant for this case.

Networked folders add complexity. For example, you must make sure that the HTTP user (nginx) can access your Synology share properly.

Anyway, I would recommend enabling [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode), that will provide you with more detailed error messages.

**Comment by fdfytr** [comment]
I fixed that! :)
default root /var/www/html root @ /etc/nginx/sites-available/default
and correct path to /var/run/php/php7.3-fpm.sock

+ nfs mounting work without problem with chmod 777 for folder with books
