### ISSUE TITLE
[INFO] New DSM7 Package with new/custom Icon

### ISSUE THREAD

**Issue by andreas-becker** [rvolz/BicBucStriim#374]
Hey,
i'm currently trying to compile a package for my Synology Diskstation. Mostly, to learn how to do and due to the fact, that the old package from SynoCommunity didn't get updated for ages.
Because i didn't want to use the Calibre icon that was used before, and (sorry, but) i didn't really like the current BBS one, i created a new one:
 ![BicBucStriim Logo by Andreas Becker](https://andreasbecker.de/share/bicbucstriim/bicbucstriim-256.png)

If you like, feel free to contact me. I created it as vector, so resizing is no problem.

Kind regards,
Andreas

**Comment by cakleine** [comment]
Hello Andreas,

where can I find your compiled BBS-package running under DSM7? I‘m missing a working BBS after update to the actual version of DSM.

Thx

Caraten

**Comment by Axas** [comment]
Hello Andreas,

Could you send me some info about your compilation? I cannot make work my package, it's very old and i updated thank to a forum I was following but now the compilation I have installed is not working with DSM7. 

Thank you,
Javier

**Comment by andreas-becker** [comment]
Sorry guys, i wasn't able to invest time to the project at the moment. I will update this if i have a running build package.
