### ISSUE TITLE
"Invalid file format" when attempting to install

### ISSUE THREAD

**Issue by shanedk** [rvolz/BicBucStriim#378]
When I attempt to install this, either from the Community package system or manually from the .zip file, I get the error, "Invalid file format. Please contact the package developer."

This is on a new Synology DS1821+ running DSM 7.01-42218.

**Comment by rvolz** [comment]
If you use this [zip file](http://projekte.textmulch.de/bicbucstriim/downloads/BicBucStriim-1.5.3.zip), there is no installation. You just unpack it. So, there should be no such error.

About the SynoCommunity file I am not sure. I know it used to work, but it is older. You might contact them in their [Discord](https://discord.gg/nnN9fgE7EF) and ask there.

**Comment by shanedk** [comment]
Got it. Thanks!
