### ISSUE TITLE
Errors using PHP 8.1

### ISSUE THREAD

**Issue by Mathias-Ro** [rvolz/BicBucStriim#386]
Hello,
it was working fine with php 7.4, but after upgrading PHP to version 8.1.8 the install check is still green, but index.php stops with: 
`PHP Fatal error:  Uncaught TypeError: Attribute value must be of type int for selected attribute, string given in .../lib/BicBucStriim/bicbucstriim.php:58\nStack trace:\n#0 .../lib/BicBucStriim/bicbucstriim.php(58): PDO->setAttribute()\n#1 .../index.php(144): BicBucStriim->__construct()\n#2 {main}\n  thrown in .../lib/BicBucStriim/bicbucstriim.php on line 58`

Best regards,
Mathias

**Comment by ralfberger** [comment]
yes I can confirm that. Erros in version 1.5.3 under PHP 8.1.
Installation check shows everything green but it also shows many erros in the lexer.php from line 211.
With PHP 7.4 it runs without problems.

`Deprecated: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in /home/xyz/xyz/bbs/vendor/twig/twig/lib/Twig/Lexer.php on line 211`
`Deprecated: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in /home/xyz/xyz/bbs/vendor/twig/twig/lib/Twig/Lexer.php on line 223`

Nice Christmas
     
          
          
          
          
          
          
          





  

	
	
	
	
  
  
  
	


  

  
   

  
  


<div data-role="page" data-title="" data-url="/installcheck.php" data-external-page="true" tabindex="0" class="ui-page ui-page-theme-a ui-page-active" style="">
    <div data-role="header" data-position="inline" role="banner" class="ui-header ui-bar-inherit">                  
      <h1 class="ui-title" role="heading" aria-level="1">Installation check</h1>
    </div>
    <div data-role="content" class="ui-content" role="main">      
      <h2>Explanation</h2>
      <p>
        This page executes various checks regarding the environment and the installation 
        directory of BicBucStriim. It checks for typical problems that users had in the 
        past. The checks signal the outcome with a traffic light scheme:
      </p>
      

  | Everything ok.
-- | --
  | There could be a problem, click on the info button to see if it concerns you.
  | A problem was discovered, please click on the info button to find out more.

</div></div><hr>
      <h2>Environment checks</h2>
      <ul data-role="listview" data-split-icon="info" data-inset="true" class="ui-listview ui-listview-inset ui-corner-all ui-shadow"> 
        <li class="ui-li-has-alt ui-li-has-thumb ui-first-child">
          </li></ul>
          
          
          
          
          
          
          
          
          
          
          <br>
<b>Deprecated</b>:  preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in <b>/home/.../.../vendor/twig/twig/lib/Twig/Lexer.php</b> on line <b>211</b>`

**Comment by mikespub** [comment]
This was due to an outdated version of the twig/twig package included in the 1.5.3 release.

Updated in #391 and release 1.6.0 at https://github.com/mikespub-org/rvolz-BicBucStriim
