### ISSUE TITLE
Send to kindle should stop using .mobi

### ISSUE THREAD

**Issue by rauljmz** [rvolz/BicBucStriim#388]
Amazon has discontinued the ability to email .mobi and .azw documents from August 2022. They now support sending epub, and they are adding epub support to all their Kindle readers.

BicBucStriim should support this change and:
1. enable the send via email option as long as epub is available
2. send the epub version to the kindle address

**Comment by kmorber** [comment]
Hello,

this would be a pretty usefull improvement.

THX
