### ISSUE TITLE
An update to Synology DSM 7.2 reports an Error 502

### ISSUE THREAD

**Issue by KSchwaier** [rvolz/BicBucStriim#398]
After update my Synology Ds220+ to DSM 7.2 reports the before well working BicBucStriim an Error 502. Also the installcheck.php produces an Error 502.
What can I do??
Greetings

**Comment by rvolz** [comment]
Please look at https://github.com/rvolz/BicBucStriim/wiki/Debug-mode to find the problem

**Comment by mikespub** [comment]
Starting with DSM 7.2 only Apache 2.4 and Nginx are supported as back-end for Web Station, and no longer the previous Apache 2.2. Also the supported PHP versions are different, see https://www.synology.com/en-global/dsm/7.2/software_spec/web_station

So first make sure you can see *any* PHP page working before trying to diagnose specific BicBucStriim issues :-)

Then if you use PHP 8.x as new PHP back end, you'll need the updated code in #391 or release 1.6.x at https://github.com/mikespub-org/rvolz-BicBucStriim for now (at least until it has been merged into the v1 branch).

**Comment by ReWo77** [comment]
I followed the instructions for upgrading (https://github.com/mikespub-org/rvolz-BicBucStriim).
Then I changed something in the index.php from "development" to "production" and it works...
