### ISSUE TITLE
Virtual Libraries

### ISSUE THREAD

**Issue by MartinJJ** [rvolz/BicBucStriim#46]
Hi,

 Calibre just introduced 'Virtual Libraries' in Version: 0.9.28

```
     See: http://manual.calibre-ebook.com/virtual_libraries.html
```

It would be nice if in BBS you could choose a Virtual Library too.
And set one (or NONE)   that should be used as default.

Regards, Martin

**Comment by stucki** [comment]
Are there still no plans for this feature? Right now, filtering is only possible by tag and by language. What I need is a filter by a custom field, which does not seem possible right now...
