### ISSUE TITLE
Thumbnail size?

### ISSUE THREAD

**Issue by DreamStatic** [rvolz/BicBucStriim#59]
It would be cool if in the Admin section you could force thumbnail uniform sizes so you could see the full cover but they all would be the exact same size. This would give a nice uniform look while scrolling the list views. As some of my images are not uniform and it looks messy. Just being OCD. :) Loving the frontend for Calibre. Thank you so much for sharing it with the masses.

**Comment by rvolz** [comment]
The v2 version features a grid with larger image tiles, see the v2dev branch.
