### ISSUE TITLE
Configurable format of listview [Enhancement]

### ISSUE THREAD

**Issue by carlyman** [rvolz/BicBucStriim#75]
I would like to request the ability to configure the details shown on listview (i.e. home page) for each book shown; options could be included via the admin/settings tab.

By default, I believe the format is
     TITLE (YEAR)
     [epub, mobi]

I have manually edited the code to show author instead of the book formats (e.g. epub, mobi); I personally would also like to show the series if one exists, but haven't been able to figure out the correct data structure lookup.

This is obviously very much based on individual preference, thus I am requesting a configurable option on the settings page.

-JC

**Comment by robsonsobral** [comment]
I think the series should be shown by default. Sometimes, it's more important than the volume name. E.G.: The Hitchhiker's Guide to the Galaxy. For comics, it's essential.
