### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by bbs1970** [rvolz/BicBucStriim#99]
ich wünsche mir die sortierung der bücher nach datum der aufnahme in die bibliothek.

danke im voraus!

grüße
bbs1970

**Comment by koertc** [comment]
It would-be be nice to select more than one book when downloading. Now when you want to select more books you need to start your search all over again.

**Comment by rvolz** [comment]
This will probably be solved with #150

**Comment by rvolz** [comment]
@bbs1970 this is being implemented right now, follow  #116.
